### ISSUE TITLE
Static Lifetime on Managed State

### ISSUE THREAD

**Issue by elbaro** [SergioBenitez/Rocket#1035]
## Feature Requests

Currently managed states require `static'` lifetime. Can we remove this bound?
In the following code, the state `&store` lives longer than the rocket struct or `rocket.launch()`, so Rocket has no problem accessing the state.

```
let store = Store::new();
crossbeam::scope(|scope| {
    scope.spawn(|_| {

        let rocket = rocket::ignite()
            .mount("/", routes![index])
            .attach(Template::fairing())
            .manage(&store);

        rocket.launch();
    });

    scope.spawn(|_| {
        loop {
            store.update();
        }
    });
})
.unwrap();
```

**Comment by jebrosen** [comment]
I believe it's entirely impossible to do this today (see rust-lang/rust#41875). I think it would be sound for `.manage()` to transmute its argument to the `'static` equivalent and make sure it only gives it out as `'r` or similar, but there's no way that I know of to even express this in the language.

In this particular example, I don't see a benefit compared to using an `Arc`.

**Comment by jebrosen** [comment]
> I think it would be sound

I take this back. To be sound, I'm pretty sure we would need the `Rocket` type to be `Rocket<'x>` and `manage()` would require `T: 'x`.

Since `Arc` already solves this problem for most cases, I'm going to close this. If someone comes up with a more compelling example that would benefit from relaxing the `'static` bound, maybe we could look at what that would require.

**Comment by DavidZemon** [comment]
@jebrosen, would you be willing to share an example of how `Arc` solves the problem stated in the original question? I'm running into the same thing (I'm just learning Rust) and it's driving me bonkers. I'd like to initialize my state based on CLI arguments from `structopt`, but the values being retrieved from `structopt` are, of course, not `'static`, and so my app won't build.

**Comment by jebrosen** [comment]
@DavidZemon this (untested/unchecked) code is roughly what I had in mind:

```rust
let store = Arc::new(Store::new());
// create a second handle to keep in the main thread
let store2 = store.clone();

// Using Arc lets us avoid needing crossbeam::scope here
std::thread::spawn(|| {
    rocket::ignite()
        .mount("/", routes![index])
        .attach(Template::fairing())
        .manage(store) // As long as Store implements Sync, Arc<Store> should also be Send + Sync + 'static, as required by manage().
        .launch()
});

loop {
    // update() must take &self. If update() took &mut, the Store would have to be guarded
    // by a mutex or otherwise synchronized. (This was still the case in the example with crossbeam::scope.)
    store2.update();
}
```

---

> I'd like to initialize my state based on CLI arguments from structopt, but the values being retrieved from `structopt` are, of course, not `'static`

I don't see a reason what that should be happening: this example (<https://docs.rs/structopt/0.3.21/structopt/#how-to-derivestructopt>) shows owned values in the structure (owned data with no references fulfills the `'static` requirement), so they should be able to be moved into other structures and/or into managed state. `Arc` is useful for e.g. sharing state between the Rocket application and outside of it, but it does not otherwise add much compared to `manage()` and has roughly the same `Send + Sync + 'static` restrictions. So I am not sure if that is related to the actual problem you experienced.

**Comment by DavidZemon** [comment]
Hm... I'm still not understanding how `Arc` helps out here. I get the same error with or without an `Arc` wrapper around `TreeShaker`

```rs

#[derive(StructOpt, Debug)]
#[structopt(name = "obex-server")]
pub struct CliOpts {
    #[structopt(short, long, default_value = LevelFilter::Info.as_str())]
    level: LevelFilter,

    #[structopt(short, long, default_value = LevelFilter::Debug.as_str())]
    module_level: LevelFilter,

    #[structopt(short, long, parse(from_os_str), default_value = DEFAULT_STATIC_CONTENT_ROOT)]
    static_content_root: PathBuf,

    #[structopt(short, long, parse(from_os_str), default_value = DEFAULT_OBEX_ROOT)]
    obex_root: PathBuf,
}

#[get("/tree?<depth>")]
fn get_root_tree(
    depth: Option<u32>,
    tree_shaker: State<Arc<TreeShaker>>,
) -> Result<Json<Vec<TreeEntry>>, ResponseStatus> {
    tree_shaker.get_tree(&PathBuf::from(""), depth)
}

#[get("/tree/<root..>?<depth>")]
fn get_child_tree(
    root: PathBuf,
    depth: Option<u32>,
    tree_shaker: State<Arc<TreeShaker>>,
) -> Result<Json<Vec<TreeEntry>>, ResponseStatus> {
    tree_shaker.get_tree(&root, depth)
}

fn main() {
    let args: CliOpts = CliOpts::from_args();

    SimpleLogger::new()
        .with_level(args.level)
        .with_module_level("obex-server-rust", args.module_level)
        .init()
        .unwrap();

    let static_content_root = args.static_content_root.canonicalize().unwrap();

    let tree_shaker = Arc::new(TreeShaker {
        obex_path: args.obex_root.as_path(),
        cmd: Cmd {
            cwd: args.obex_root.as_path(),
        },
    });
    rocket::ignite()
        .mount("/", StaticFiles::from(static_content_root))
        .mount("/api", routes![get_child_tree, get_root_tree])
        .manage(tree_shaker)
        .launch();
}
```

```
error[E0597]: `args.obex_root` does not live long enough
  --> src/main.rs:76:20
   |
76 |         obex_path: args.obex_root.as_path(),
   |                    ^^^^^^^^^^^^^^----------
   |                    |
   |                    borrowed value does not live long enough
   |                    argument requires that `args.obex_root` is borrowed for `'static`
...
86 | }
   | - `args.obex_root` dropped here while still borrowed
```

**Comment by jebrosen** [comment]
The difficulty here is with the `TreeShaker` struct, not `structopt`:

```rust
let tree_shaker = Arc::new(TreeShaker {
        obex_path: args.obex_root.as_path(),
        cmd: Cmd {
            cwd: args.obex_root.as_path(),
        },
    });
```

`obex_path` seems to be defined to be `&'a Path`, which is what makes it impossible to be put into managed state unless you have an `&'static Path` (and the same for any other reference types). The only safe ways I know of to get an `&'static Path` are to use a string literal, or to leak it with something like `Box::leak()`. Is there any particular reason `TreeShaker` is defined to accept references, instead of owning a `PathBuf` itself? The owned `PathBuf` is less likely to cause other headaches similar to this one further down the line anyway, and I would expect the overall performance difference of using `&Path` in this situation to be minimal to none.

**Comment by DavidZemon** [comment]
Oh! I didn't realize `Path` had a fundamental difference compared to `PathBuf`. I've applied the change you suggested and _yes_, this is much better now. Thank you.
