### ISSUE TITLE
Update r2d2_mysql dependency version to 16.0

### ISSUE THREAD

**Issue by bostontrader** [SergioBenitez/Rocket#1077]
Hello Folks,

I'd like to request that the r2d2_mysql dependency be updated, by the doers of such things, from v 9.0.0 to v 16.0.0.  I'm guessing that this is a simple tweak for those in the know, but I'm willing to make a pull request if necessary.  Please advise.

More particularly...

I'm trying to use rocket_cors v5.0.0 and rocket_contrib v0.4.2 with default-features = false
features = ["json","mysql_pool"].  Cargo build is not happy and complains:

error: failed to select a version for `regex`.
    ... required by package `rocket_cors v0.5.0`
    ... which is depended on by <myproject>
versions that meet the requirements `^1.1` are: 1.2.1, 1.2.0, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0

all possible versions conflict with previously selected packages.

  previously selected package `regex v1.0.0`
    ... which is depended on by `mysql v14.0.0`
    ... which is depended on by `r2d2_mysql v9.0.0`
    ... which is depended on by `rocket_contrib v0.4.2`
    ... which is depended on by <myproject>

r2d2_mysql v9.0.0 dates from July 2018 and the latest edition is 16.0.0.
mysql v14.0.0 also dates from July 2018 and has a latest edition of 16.0.2.

So it looks like r2d2 is to blame for all this trouble, as c3po probably could have told me from the beginning and it sure would be nice to fix this.

Thanks in advance for your consideration.

**Comment by jebrosen** [comment]
This was done in 273c7a6 and will be included in 0.5. Unfortunately it cannot be included in 0.4 because it is a breaking change.

I am surprised that cargo is even trying to unify the versions of regex, and not just selecting `1.0.0` for `mysql` and `1.2.1` for `rocket_cors`. https://github.com/blackbeam/rust-mysql-simple/issues/162 was fixed for the 15.x branch of `mysql`, but not in the 14.x branch. You could request a patch or minor release of `mysql` to loosen the version requirement if that's a backwards compatible change for `mysql` to make.

You can also implement `Poolable` yourself to sidestep the version issues - see https://github.com/SergioBenitez/Rocket/issues/888#issuecomment-454616267, but it doesn't look like any actual code was posted there.

**Comment by bostontrader** [comment]
Thanks for the input @jebrosen. I fixed this by forking rocket_cors and downgrading the regex dependency version from 1.1 to 1.0.  Then: Edit my project's Cargo.toml dependency:

rocket_cors = { git = "https://github.com/bostontrader/rocket_cors", branch = "downgrade-regex" } 

Easy and effective... a generally rare combo!
