### ISSUE TITLE
doc examples for rocket_contrib JsonValue do not compile

### ISSUE THREAD

**Issue by bstpierre** [SergioBenitez/Rocket#1089]
1. The version of Rocket you're using. Ensure it's the latest, if possible.

0.4.2

  2. The operating system (distribution and version) where the issue occurs.

ubuntu 18.04.2

  3. A brief description of the bug that includes:

I expected that attempting to compile the examples given in:

https://api.rocket.rs/v0.4/rocket_contrib/json/struct.JsonValue.html#method.get

would compile and run. Instead I got compile errors:

```
17 |     assert_eq!(object[0]["x"]["y"]["z"], json!(null));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `serde_json::value::Value == rocket_contrib::json::JsonValue`
```

  4. How you uncovered the bug. Short, reproducible tests are especially useful.

This can be trivially reproduced by generating a new lib crate, adding rocket_contrib as a dep, and pasting the example code into the generated src/lib.rs. I put this into a gist: https://gist.github.com/bstpierre/8a8445e4d60d651ff7a79dc29bb961ce

  5. Ideas, if any, about what Rocket is doing incorrectly.

As suggested by jebrosen on irc, adding a `*` in front of the `json!` in the assertions fixes the error, it compiles, and the tests pass. This adjustment should probably be made in the docs.

**Comment by jebrosen** [comment]
> This adjustment should probably be made in the docs.

We actually can't change the docs, because those docs are part of `serde_json` and are being copied into ours automatically. But changing the docs is wrong for `serde_json`!

The docs *are correct* when `json!` refers `serde_json::json`. They are only not working for you because your `json!` refers to `rocket_contrib::json`. I remember `rocket_contrib`'s macro called `json!` that does almost but not exactly the same thing as `serde_json::json!` confusing people in the past, so maybe we should work on documentation or examples to make this less confusing.

In #968 I mentioned that we could add some `PartialEq` implementations for `JsonValue`, which would also fix this particular instance of the problem.

**Comment by bstpierre** [comment]
I guess I was led down the wrong path by parsing this sentence too closely:

> Usage
> A value of this type is constructed via the json! macro.

because that `json!` links to https://api.rocket.rs/v0.4/rocket_contrib/macro.json.html which *is* the rocket_contrib::json, so that's what I thought I was supposed to be using in that context.  I was aware they were different & potentially confusing -- this is documented somewhere else I think -- so I was on the lookout for which one I should specifically be using.

Thanks for mentioning that these docs are copied from serde_json -- I was going to look for the right place to patch the docs and open a PR.

**Comment by jebrosen** [comment]
I forgot to mention, the main indication the docs come from elsewhere is the header "Methods from `Deref<Target = Value>`": everything within this entire section, including `get`, is effectively copy-pasted from the docs for `serde_json::Value`.

**Comment by SergioBenitez** [comment]
This is no longer applicable/fixed as of the contrib graduation.
