### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by danielspk** [SergioBenitez/Rocket#1091]
Hello, where I work all the frameworks and libraries must have a stable version.  Is there a date for the release of stable version 1.0?

Thanks.

**Comment by jhpratt** [comment]
Check out #19. There's still some things that have to be done before it'll be able to compile on stable. Sergio doesn't want a 1.0 release prior to compiling on stable, so that's likely the largest blocker. There's still some work that has to be done on Rust's side, lest we resort to nasty workarounds to force it.

**Comment by SergioBenitez** [comment]
#19 is a big blocker, as is #1065. Both are being worked on now. Once these are done, we'll want to figure out #852, #501, #14 and a few more before a 1.0 is ready. I intend a 1.0 to be true indication that Rocket is ready to be used for almost any production web task, not just those possible today, with very high confidence in application security and correctness, far exceeding what is possible now. This is a monumental task.

Progress is steady, and we have an incredible group of folks (@jebrosen, @jhpratt, and many others) working on all fronts. A timeline is impossible; I'd surely be wrong were I to propose anything. It will be ready as soon as it is - no earlier and no later.
