### ISSUE TITLE
How can I prevent the welcoming screen

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#1113]
How can I prevent the `Rocket` welcoming screen from being displayed, not just preventing emoji and colors, preventing it completely, may be except the last line. 

![image](https://user-images.githubusercontent.com/46838626/64066402-c6095c00-cc21-11e9-91d1-da42ad149a4b.png)

**Comment by pzmarzly** [comment]
Here's what comes to my mind: since on Unix systems `stdout` is just a file descriptor, you can [swap it with a file](https://stackoverflow.com/q/26666012/5108318). It's a hack, but as a bonus you are getting simple logging (including `dbg!()` calls). If you want to discard these messages completely, just open `/dev/null`.

Perhaps there are other ways to do it, too. BTW if you write code I proposed (swapping file descriptors), could you share it here?

**Comment by jebrosen** [comment]
Rocket does goes a bit out of its way to make sure launch info is logged, unless logging is off entirely. You can probably do something with a custom logging implementation that ignores log messages with the target set to `launch` or `launch_`, but those are kindof implementation details.

We should consider this while working on #21.

**Comment by SergioBenitez** [comment]
We consider logging all configuration information a fairly important security feature during debug mode. It lets you ensure that your application is configured exactly as you expected. Nevertheless, yes, we should consider our options; punting to #21.
