### ISSUE TITLE
Feature request: implementing IntoIterator on http::header::HeaderMap

### ISSUE THREAD

**Issue by atroche** [SergioBenitez/Rocket#1137]
Hello! First some context:

I'd like to log request headers as JSON. I can't implement Serialize directly on HeaderMap, but I know if I can turn it into a `HashMap` I'll be fine. `HashMap` implements `FromIterator`, which means I can construct it easily from anything which implements `IntoIterator`.

`HeaderMap`'s underlying `IndexMap` implements it  `IntoIterator`, but is private. Meanwhile, `HeaderMap` has its own `into_iter` method, but not an implementation of `IntoIterator`.

So it's not like this is blocking me, it's just a little harder than it could be. Are you open to my making a PR with an `IntoIterator` implementation for `HeaderMap`?

Cheers.

edit: Hah! Just found [this TODO](https://github.com/SergioBenitez/Rocket/blob/master/core/http/src/header.rs#L609) in the code ;)

**Comment by jebrosen** [comment]
Every `Iterator` implements `IntoIterator`, so I believe something like `headers.iter().collect::<HashMap<_, _>>()` should work already. Implementing `IntoIterator` on `HeaderMap` itself wouldn't help much because none of Rocket's APIs ever give out a `HeaderMap` by value, but we could implement `IntoIterator` for `&HeaderMap`.

**Comment by SergioBenitez** [comment]
Agreed with @jebrosen. Happy to take a PR, but I don't think there's a need to track this.
