### ISSUE TITLE
Rocket doesn't recognise path ending by ":"

### ISSUE THREAD

**Issue by crone123** [SergioBenitez/Rocket#1141]
Hello,
For a file explorer test, I have tested to explore some folders with different names, and I discovered that a path ending by ":" is not recognized by rocket.
I use this URL catcher, and display an index page:
```
"/explore/<file..>"
```
Where file is an:
```
Option<PathBuf>
```
If the folder ends by ":", file contains None.
If it finish by another character after ":", the file contains Some(_).

A folder ending by ":" seems to be properly manager by the standard PathBuf, so I think it's a problem with the rocket-rs URL analyser.

In addition, the "%3A" character, who is the ":" but encoded, have exactly the same problem.

Can you fix this?
Thank you !

**Comment by SergioBenitez** [comment]
This is purposeful. See the [documentation](https://api.rocket.rs/v0.4/rocket/request/trait.FromSegments.html#foreign-impls). This is a security measure to prevent misuse of `PathBuf` in later parts of the application, i.e, to prevent path traversal attacks.

As an example, consider the following route:

```rust
#[get("/<path..>")]
fn hello(path: PathBuf) io::Result<File> {
    File::open(path.join("foo.html"))
}
```

If we allowed paths to end in `:`, the user could force your application to access files outside of the current working directory. On Windows, this would be as simple as the user sending `C:` (or `D:`, `E:`, etc. until one works). Then, you would return `foo.html` from the root of your file system. On Unix-ish systems, the problem is less pronounced. Still, the `:` character has special meaning in certain uses of paths. The canonical example is when separating paths, for instance, in `$PATH`.

On Windows, this behavior will not change as it is clearly a security issue. On Unix, I'm inclined to propose that we allow `:`, though I am not convinced of the utility. In either case, we should extending the [`Segments::into_path_buf()`](https://api.rocket.rs/v0.4/rocket/http/uri/struct.Segments.html#method.into_path_buf) method to make it easier to subvert certain sometimes-okay conditions, allowing you to implement your own slightly-less-safe `PathBuf`-like segments guard type.

**Comment by listofbanned** [comment]
> This is purposeful. See the [documentation](https://api.rocket.rs/v0.4/rocket/request/trait.FromSegments.html#foreign-impls). This is a security measure to prevent misuse of `PathBuf` in later parts of the application, i.e, to prevent path traversal attacks.
> 
> As an example, consider the following route:
> 
> ```rust
> #[get("/<path..>")]
> fn hello(path: PathBuf) io::Result<File> {
>     File::open(path.join("foo.html"))
> }
> ```
> 
> If we allowed paths to end in `:`, the user could force your application to access files outside of the current working directory. On Windows, this would be as simple as the user sending `C:` (or `D:`, `E:`, etc. until one works). Then, you would return `foo.html` from the root of your file system. On Unix-ish systems, the problem is less pronounced. Still, the `:` character has special meaning in certain uses of paths. The canonical example is when separating paths, for instance, in `$PATH`.
> 
> On Windows, this behavior will not change as it is clearly a security issue. On Unix, I'm inclined to propose that we allow `:`, though I am not convinced of the utility.
> 
> In either case, we should extend the [`Segments::into_path_buf()`](https://api.rocket.rs/v0.4/rocket/http/uri/struct.Segments.html#method.into_path_buf) method to make it easier to subvert certain sometimes-okay conditions, allowing you to implement your own slightly-less-safe `PathBuf`-like segments guard type.

Many thanks!

**Comment by SergioBenitez** [comment]
Closing as this is working as intended. Happy to take a PR for Unix-only option to `Segments::into_path_buf()`.
