### ISSUE TITLE
Rocket_contrib - Add FromParam and FromForm implementations for Uid<ObjectId> (MongoDB)

### ISSUE THREAD

**Issue by HindrikStegenga** [SergioBenitez/Rocket#1144]
## Feature Request

Hello, I would like it if trait implementations for Uid<T>, specifically MongoDB ObjectId's could be added to Rocket_contrib. This way we could use crates like avocado to immediately deserialize and serialize (B/J)SON data from formparams/URL parameters and so on directly from and to Rocket <-> MongoDB. I feel the best place for this would be in Rocket_contrib. Currently this cannot be done because we cannot implement traits foreign on foreign types. Adding such implementations to Rocket would solve this.

**Comment by Weasy666** [comment]
I guess you could do something similar to what i did for a SHA1 in a route

``` rust
pub struct Sha1(pub String);

impl<'a> FromParam<'a> for Sha1 {
    type Error = &'a RawStr;

    //^[a-fA-F0-9]{40}$ is the 
    fn from_param(param: &'a RawStr) -> Result<Sha1, Self::Error> {
        if param.len() != 40 {
            return Err(param);
        }

        let mut is_sha1 = true;
        for c in param.as_bytes() {
            match *c {
                b'0'|b'1'|b'2'|b'3'|b'4'|b'5'|b'6'|b'7'|b'8'|b'9' => (),
                b'a'|b'b'|b'c'|b'd'|b'e'|b'f'|b'g'|b'h'|b'i'|b'j'|b'k'|b'l'|b'm'|b'n'|b'o'|b'p'|b'q'|b'r'|b's'|b't'|b'u'|b'v'|b'w'|b'x'|b'y'|b'z' => (),
                b'A'|b'B'|b'C'|b'D'|b'E'|b'F'|b'G'|b'H'|b'I'|b'J'|b'K'|b'L'|b'M'|b'N'|b'O'|b'P'|b'Q'|b'R'|b'S'|b'T'|b'U'|b'V'|b'W'|b'X'|b'Y'|b'Z' => (),
                _ => is_sha1 = false,
            }
        }

        if is_sha1 {
            Ok(Sha1(param.to_string()))
        }
        else {
            Err(param)
        }
    }
}
```
I know that `match` is pretty ugly, but i didn't want to add a regex crate to my project just for this one use case.

**Comment by jebrosen** [comment]
That match should be simplifiable to something like `b'0'..b'9' | b'a'..'f' | b'A'..'F' => ()`, by the way (and g-z are invalid in a hex representation of a hash).

---

> Currently this cannot be done because we cannot implement traits foreign on foreign types. Adding such implementations to Rocket would solve this.

It's worth remembering here that `rocket_contrib` is not special, in the sense that it cannot implement `rocket`'s traits on foreign types either. For existing types like `Uuid` or `JsonValue`, `rocket_contrib` defines a wrapper e.g. `pub struct Uuid(pub uuid::Uuid);` and then implements some traits so that it works like a `Uuid`. I think that should work nearly seamlessly for most or all users of `FromParam`, but not `FormFormValue`.

Only `rocket` or the crate defining `Uid` can implement `FromFormValue for Uid`, and it's very unlikely that it will be implemented in `rocket` because of the added dependency. `Json` (in `rocket_contrib`) uses `Deserialize`, which is comparatively much more universal.

It may be worth looking into (optionally?) integrating `FromForm` with `serde`'s traits, which I imagine would solve issues like this more universally.

**Comment by Weasy666** [comment]
Oh damn....you are right...especially because i have the actual regex right above the method as comment...i was just so happy that the route was working with this FromParam 😅.
Edited the example.

**Comment by HindrikStegenga** [comment]
> That match should be simplifiable to something like `b'0'..b'9' | b'a'..'f' | b'A'..'F' => ()`, by the way (and g-z are invalid in a hex representation of a hash).
> 
> > Currently this cannot be done because we cannot implement traits foreign on foreign types. Adding such implementations to Rocket would solve this.
> 
> It's worth remembering here that `rocket_contrib` is not special, in the sense that it cannot implement `rocket`'s traits on foreign types either. For existing types like `Uuid` or `JsonValue`, `rocket_contrib` defines a wrapper e.g. `pub struct Uuid(pub uuid::Uuid);` and then implements some traits so that it works like a `Uuid`. I think that should work nearly seamlessly for most or all users of `FromParam`, but not `FormFormValue`.
> 
> Only `rocket` or the crate defining `Uid` can implement `FromFormValue for Uid`, and it's very unlikely that it will be implemented in `rocket` because of the added dependency. `Json` (in `rocket_contrib`) uses `Deserialize`, which is comparatively much more universal.
> 
> It may be worth looking into (optionally?) integrating `FromForm` with `serde`'s traits, which I imagine would solve issues like this more universally.

Hmm, interesting. I did not know rocket_contrib merely re-exported a particular crate, I thought it just included mongodb source in itself. 

I ended up implementing it using a wrapper over ObjectID's, which worked for my usecase. 
Your last suggestion would be a nice addition, but probably a good idea for a different PR. I will close this one for now.
