### ISSUE TITLE
Flash cookie doesn't return original string stored in it, if it contains percent signs

### ISSUE THREAD

**Issue by Boscop** [SergioBenitez/Rocket#1151]
When you store a string in a Flash cookie message and read it back, it's not always the same:
If your string contains percent sign chars, rocket won't encode them (e.g. if your value is a url that contains percent-encoded chars), but during decoding it will decode all percent-encoded chars!
E.g. if you want to store `%7B%22`, it will be stored the same in the cookie but when you read it back, you get `{"` instead of the original value `%7B%22`.

Please also percent-encode percent signs!
Probably non-flash cookies are also affected..

**Comment by jebrosen** [comment]
I believe the problem is at <https://github.com/SergioBenitez/cookie-rs/blob/e0f3e6c4daea108d55838c56da777b36898bd223/src/lib.rs#L934>: '%' is missing from the encode set.

It references <https://url.spec.whatwg.org/#userinfo-percent-encode-set>, which is also missing '%'.

That looks *very* wrong. The older standard https://tools.ietf.org/html/rfc3986#section-2.4 gets this right, specifying that '%' must always itself be percent-encoded when it appears as data.

**Comment by SergioBenitez** [comment]
This was fixed upstream!
