### ISSUE TITLE
Weird routing when route contains dot

### ISSUE THREAD

**Issue by ctjhoa** [SergioBenitez/Rocket#116]
Hi,
I want to create a stupid file server but I face a weird behaviour when I introduce `.` in my route.
Here is my code:
```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;

use std::fs::File;

#[get("/<name>.<ext>")]
fn index(name: &str, ext: &str) -> File {
    File::open(format!("public/img/status/{}.{}", name, ext)).unwrap()
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```
and logs when I hit `http://localhost:8000/unknown.png` :
```
GET /unknown.png:
    => Matched: GET /<name>.<ext>
    => Outcome: Forward
    => Error: No matching routes for GET /unknown.png.
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.
```
If I replace `/<name>.<ext>` by `/<name>/<ext>` file are served well.
For example with `http://localhost:8000/unknown/png`:
```
GET /unknown/png:
    => Matched: GET /<name>/<ext>
    => Outcome: Success
    => Response succeeded.
```

**Comment by ctjhoa** [comment]
And I know that I just could write
```rust
#[get("/<file>")]
fn index(file: &str) -> File {
    File::open(format!("public/img/status/{}", file)).unwrap()
}
```
but my first try bothering me.

**Comment by SergioBenitez** [comment]
It's not allowed to have more than one dynamic parameter in a path segment. In fact, it's not allowed to have anything but a dynamic parameter in a path segment. Well, at least that's what I imagined.

The reality is that the framework isn't convinced one way or another. The codegen lets this through erroneously, so it's certainly not fulfilling its intent. The core library, on the other hand, does _and_ doesn't. It matches routes with any number of parameters in any segment, so you see the match succeed, but it doesn't extract arguments for them from the URL, so you see it forward.

Even now it's not clear if paths like the one you've written should be allowed. Allowing this essentially gives you a weak form of pattern matching inside of a segment. But Rocket lets you accomplish this via `FromParam` as well, though more verbosely as it requires a new type and a trait implementation. In short, allowing this gives you concise matching for some patterns but makes the matching and parameter extraction implementation more complicated. It also, in my opinion, makes routes slightly harder to read since they are more expressive.

Any arguments for or again either proposal would be appreciated. Marking this as "feedback requested".

**Comment by ctjhoa** [comment]
That's fine for me. `FromParam` could fill the need.
You should probably add the `It's not allowed to have more than one dynamic parameter in a path segment` in [the documentation](https://rocket.rs/guide/requests/#dynamic-paths) and/or let the codegen throw an error at compile time.

Unwrap was just for testing purpose :)
Anyway great project and documentation 👍 .
Thanks.
