### ISSUE TITLE
Warning for each route annotation from clippy

### ISSUE THREAD

**Issue by evertvp** [SergioBenitez/Rocket#117]
[Clippy](https://github.com/Manishearth/rust-clippy) gives the following warning at each route annotation:
this expression borrows a reference that is immediately dereferenced by the compiler

It would be nice if this was fixed, it makes output from clippy that I can actually fix harder to find and it's always nice to get empty output from clippy.

**Comment by shssoichiro** [comment]
I have already opened PR #112 which should fix this.

**Comment by SergioBenitez** [comment]
17bbd41f73a67584665a3f7e40f48e655b3037e6 (by @shssoichiro) should have cleared this up. Will leave this open until I have confirmation.

**Comment by shssoichiro** [comment]
It looks like my previous PR did not actually fix this warning, although I've tracked down the actual cause and will open another PR to fix this issue (which I've tested locally). I thought that this would be fixed by running clippy against `rocket_codegen`, but it seems clippy didn't look inside `quote_expr` or `quote_stmt`, which is where this warning was originating from.

**Comment by SergioBenitez** [comment]
Alright. Got rid of some more in 59043e262a6b0f63b984bc224e152100234e3ec9 and b109bb41ff4d26b9e64324ee0586ec1b8f7a9abc. I ran clippy through several of the Rocket examples and found no warnings. Hopefully we got them all!

**Comment by SergioBenitez** [comment]
@evertvp Can you confirm all is well on your end?

**Comment by evertvp** [comment]
Yes, all clippy warnings on my project are gone now. Thanks!

**Comment by shssoichiro** [comment]
It looks like this is still happening for me on 0.1.5. **However**, what makes this interesting is that it only happens if I use the version of Rocket from crates.io. If I clone Rocket from git and tell Cargo to use the version of Rocket on my filesystem, or even if I tell Cargo to pull directly from Github, I don't see the clippy warnings anymore.

**Comment by SergioBenitez** [comment]
As noted in the CHANGELOG, 0.1.5 was purely a security hotfix release and includes no new features or enhancements. This change will ship in 0.2 soon. See the tagged `0.1.5` commit for the changes between `0.1.4` and `0.1.5`.
