### ISSUE TITLE
Documentation of FromDataSimple doesn't say it's only for debugging

### ISSUE THREAD

**Issue by malaire** [SergioBenitez/Rocket#1171]
The documentation of FromDataSimple doesn't mention that it's only for debugging. This is only mentioned at documentation of FromData.

Based on several closed issued about this and recent message at #beginners, this causes enough confusion that documentation of FromDataSimple should also mention this.

**Comment by jebrosen** [comment]
> The documentation of FromDataSimple doesn't mention that it's only for debugging.

FromDataSimple is not only for debugging. The implementations for `String` and `Vec<u8>` are only for debugging, and it's a coincidence that they both implement `FromDataSimple` instead of `FromData` directly.

I guess we could copy the explanation to the page for `FromDataSimple`, but I would personally rather remove those implementations entirely in favor of an approach like #990.

**Comment by SergioBenitez** [comment]
Closing as invalid. I agree that we should expose safer, harder-to-lead-to-DoS APIs for `Data`. I would also like to rename `FromDataSimple` to `FromData`, and `FromData` to `FromTransformedData`, to better explain the differences.
