### ISSUE TITLE
Template render Directly to String

### ISSUE THREAD

**Issue by ducharmemp** [SergioBenitez/Rocket#1177]
## Feature Request
  1. Why you believe this feature is necessary.
        In order to get a raw string from a template, a user must use the non-recommended `show` API which requires access to the underlying rocket instance. As far as I'm aware, it's not possible for any route to get access to the Rocket instance since FromRequest is rightfully not implemented for Rocket. 

  2. A convincing use-case for this feature.
    I'd like to be able to use the same Tera templating engine that is attached to the main Rocket application to send templated emails. Currently I'd have to set up another engine that's completely separate but has the same(ish) configuration via lazy_static or a custom guard.

## General Comments
I'm sure that this would require a lot of work after glancing at the API, but in the *general* case I'd like to be able to call `finalize` directly on the template and pass the context in. I'm also positive that it'll make for a somewhat confusing API since there are functions that you *can* call but shouldn't in the general case. I'd love to hear more discussion on this.

**Comment by timando** [comment]
I had a similar problem and I wrote the following code:
```rust
pub struct TemplateRenderer<'a,'r>(&'a rocket::Request<'r>);
impl <'_a, '_r> TemplateRenderer<'_a, '_r>{
    pub fn render<S,C>(&self,name: S, context: C) -> String
    where S: Into<std::borrow::Cow<'static, str>>, C: serde::Serialize, S: std::fmt::Display
    {
        use rocket_contrib::templates::Template;
        use rocket::response::Responder;
        let template = Template::render(name.into(), context);
        let mut response = template.respond_to(self.0).unwrap();
        response.body_string().unwrap_or_else(String::new)
    }
}
impl<'a, 'r> rocket::request::FromRequest<'a, 'r> for TemplateRenderer<'a,'r>{
    type Error = !;
    fn from_request(request: &'a rocket::Request<'r>) -> rocket::request::Outcome<Self, Self::Error> {
        rocket::request::Outcome::Success(TemplateRenderer(&request))
    }
}
```

**Comment by alexfromapex** [comment]
Not sure if helpful but I was able to use Askama and render() to a String, if a workaround is useful

**Comment by paul-hansen** [comment]
Note that the workaround @timando proposed doesn't work with 0.5-rc because the lifetime of the references held by the Request is no longer exposed in the trait's signature. It's now `FromRequest<'r>` instead of `FromRequest<'a, 'r>` which as far as I can tell means we can't hold onto a reference to the request because there isn't a way to tie the lifetime of our struct's (TemplateRenderer in timando's code) Request to the lifetime of the trait's Request references.

https://api.rocket.rs/v0.5-rc/rocket/request/trait.FromRequest.html
https://api.rocket.rs/v0.4/rocket/request/trait.FromRequest.html

You can use [Template::show](https://api.rocket.rs/v0.5-rc/rocket_dyn_templates/struct.Template.html#method.show), but it's not great since you have to build a whole new fake instance of Rocket to use it.

**Comment by Turakar** [comment]
Thanks! I like the ergonomics of the new solution.
