### ISSUE TITLE
TOML value parsing on parameters passed by environment

### ISSUE THREAD

**Issue by danipozo** [SergioBenitez/Rocket#1181]
When passing a dictionary (inline table in TOML's terminology) by environment in certain ways, I get behaviours that can be confusing at times:

```
ROCKET_EXAMPLE="{str=test}" cargo run
```

gives `example: { str = "test " }`, the same as

```
ROCKET_EXAMPLE="{str="test" }" cargo run
```

because this way the shell interprets that the quotes aren't nested and passes the concatenation of the strings, while the way to get correct behaviour seems to be to escape quotes inside the table:

```
ROCKET_EXAMPLE="{str=\"test\" }" cargo run
```

Maybe there should be a warning when parsing a value that is not a number or another value that doesn't require quotes? As far as I can tell from TOML's specification, this is not contemplated.

**Comment by jebrosen** [comment]
This is a somewhat confusing interaction between the shell and with one (afaict) unique feature of Rocket's TOML parser.

First, let's see what the environment variables contain after the shell has processed the strings:

* `ROCKET_EXAMPLE="{str=test}"` => `{str=test}`
* `ROCKET_EXAMPLE="{str="test" }"` => `{str=` `test` `}` => `{str=test}`
* `ROCKET_EXAMPLE="{str=\"test\" }"` => `{str="test"}`

I believe the TOML specification only considers the third one to be valid. Rocket, however, *does* allow "barewords" in values and treats them as strings (likely to help cases like #598), so the three are equivalent.

I think the long term solution to this would be part of #852, and possibly using a more authoritative TOML parser instead of having one inside Rocket.

**Comment by danipozo** [comment]
Yes, I think being fully TOML compliant would be the best solution.

**Comment by SergioBenitez** [comment]
Rocket doesn't claim to only accept TOML syntax for its environment variable parsing, though we do say "as if it were TOML", which might be misleading. Nevertheless, I don't believe we should be strict about what we accept here. It's far too convenient; having to escape `"` to get strings to work feels much more cumbersome than the rarely confusing behavior. Nevertheless, #852 has been notified, so we should consider our options then.
