### ISSUE TITLE
Expose pool directly from generated database pools

### ISSUE THREAD

**Issue by cassc** [SergioBenitez/Rocket#1187]
Rocket can create and manage a pooled database connection which can be accessed inside HTTP handlers. 

Can I access this database pool outside these handlers?

**Comment by jebrosen** [comment]
Not easily, unfortunately. The code generated by `#[database]` creates a hidden type for the connection pool and puts it in managed state, which makes sharing hard for two reasons:

* The name of this hidden type is technically an implementation detail.
* IIRC there's no way to get an `Arc<Pool>` out, just an `&Pool` or `State<'_, Pool>` that is tied to the lifetime of the `Rocket` instance. This makes it impossible to call `launch()`, which moves the `Rocket` instance.

In case you only need a single connection before launch (e.g. for initialization), `get_one` does currently exist for that purpose.

**Comment by eon8ight** [comment]
Follow-up question: so you've got `get_one`, but that requires a `Rocket` instance. What if you have a request guard that requires a database connection? How do you get the running `Rocket` instance to pass into it?

**Comment by jebrosen** [comment]
If you're already in a request guard, you can use [`request.guard::<ConnectionType>()`](https://api.rocket.rs/v0.4/rocket/struct.Request.html#method.guard) to get a connection.

**Comment by eon8ight** [comment]
Worked perfectly - thank you!

**Comment by SergioBenitez** [comment]
@cassc Do you have a case where you need access to the actual pool as opposed to a connection from the pool (which we allow, via `get_one()`)?

**Comment by cassc** [comment]
@SergioBenitez 
My application has an HTTP server and also a UDP server, both need to access the database.

**Comment by KitaitiMakoto** [comment]
I have the same desire. I'm developing a web application [Plume][] using Rocket and [Riker][], an actor library. Actors are running on other threads and some actors need to connect to database. In this case, we want to make actors retrieve database connections from the pool on demand rather than hold connection for each. If we cannot share database pool between Rocket and actors, we need build two pools.

[Plume]: https://joinplu.me/
[Riker]: https://riker.rs/
