### ISSUE TITLE
Template::render still expects Tera 1.0 contexts to be serializable

### ISSUE THREAD

**Issue by lukexor** [SergioBenitez/Rocket#1236]
Rocket Version: 0.4.2
CentOS Linux release 7.6.1810
Tera Version: 1.0.2

It seems since Tera v0.11.3, tera::Context does not implement Serialize in order to avoid excess allocations. It may be related to Issue #1195 (I'm not sure), but updating Tera to 1.0 is incompatible with the rocket_contrib 0.4.2 Template::render function which still expects contexts to be Serializable.

The error message you get is:

```
error[E0277]: the trait bound `tera::context::Context: response::_IMPL_DESERIALIZE_FOR_Success::_serde::Serialize` is not satisfied
   --> src/routes/root.rs:13:40
    |
13  |         Template::render("root/index", Context::new())
    |                                        ^^^^^^^^^^^^^^ the trait `response::_IMPL_DESERIALIZE_FOR_Success::_serde::Serialize` is not implemented for `tera::context::Context`
```

**Comment by jebrosen** [comment]
What happened is this:

* When template handling was first set up (and up through handlebars `3.*` and tera `0.11.*`), both `Handlebars` and `Tera` had an interface that required `T: Serialize`. `tera` also had a `Context` type that implemented `Serialize`.
* In tera 1.0 (not 0.11), `tera` switched to requiring a `Context`, and added `Context::from_serialize`. This is what `rocket_contrib` was updated to use.

This is unfortunate because it no longer matches `tera`'s normal API, but `Serialize` is the common denominator - note that it's not decided whether the chosen template will be tera or handlebars until the `Responder` implementation for `Template`, since both can be used in the same application.

Some equivalents of `Context::new()` that are still `T: Serialize` are `Context::new().into_value()`, `serde_json::json!({})`, or `BTreeMap::<String, serde_json::Value>::new()`.

**Comment by SergioBenitez** [comment]
Looks like this has been answered!
