### ISSUE TITLE
Rocket in different file instead of main

### ISSUE THREAD

**Issue by manio** [SergioBenitez/Rocket#1269]
Hello guys,
I am trying to compile the following code (ignore the branch name):
https://github.com/manio/hard/tree/rust-panic
using Rocket.
As I don't want to put the rocket in main I just put the:
```
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use]
use rocket;
```
in the webserver.rs file, but there are two problems:

```
error: cannot find attribute `get` in this scope
  --> src/webserver.rs:15:3
   |
15 | #[get("/<name>/<age>")]
```

Is it possible to have the rocket handler functions in different file then main?

Second problem is when I enabled those macros in my main and the "extern crate rocket", then I have plenty of errors from my logging, like:
```
error: cannot find macro `warn` in this scope
  --> src/main.rs:71:9
   |
71 |         warn!("Will do console logging only...");
   |         ^^^^ help: a macro with a similar name exists: `warn_`
   |
  ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.4/src/logger.rs:82:1
   |
82 | macro_rules! warn_ { ($($args:expr),+) => { log_!(warn: $($args),+); }; }
   | ------------------ similarly named macro `warn_` defined here
```
So it is probably conficting with my simplelog. Should I change it to the slog to be able to use Rocket?

**Comment by MikailBag** [comment]
If you use Rust 2018 (i.e. Cargo.toml contains `edition = "2018"`), then you can use
either 
```rust
#[rocket::get("/foo")]
fn my_route() {}
```
or 
```rust
// in each module which defines routes
use rocket::get;

#[get("/foo")]
fn my_route() {}
```

In both cases, you do not need legacy `#[macro_use]`.

Same applies to logging macros: in rust 2018 they can be work just like functions or traits.

**Comment by jebrosen** [comment]
You haven't uploaded `webserver.rs` to that git repository so I may have missed some details, but these are the two ways to import macros:

* `#[macro_use] extern crate rocket;`, which is only allowed in the crate root (`lib.rs` or `main.rs`). This will make all of rocket's macros visible throughout that crate.
* `use rocket::get;`, as the previous comment explains. The individual macros imported this way are only available in the current module, just like other things that are `use`d.

Notably, both forms work in both the 2015 and 2018 editions.

`#[macro_use] use rocket;` is the same as `use rocket;`, since `#[macro_use]` does nothing on a `use`. You should get a warning message saying that the `#[macro_use]` attribute is unused.

---

Rocket does attempt to set up its own logger, but that would be something you would see at runtime, not compile-time - I assume the issues with the `warn` macro are the same (i.e. you need either `#[macro_use] extern crate log;` or `use log::warn;`)


I don't think there is anything to fix in Rocket here, but maybe some things can be explained more completely in the documentation?

**Comment by manio** [comment]
Hi guys,
Thank you for explanations.
Maybe the documentation needs to be fixed as I am just doing everything according to the: https://rocket.rs/v0.4/guide/getting-started/

I am using edition = "2018" in Cargo toml and I've switched the project to nightly compiler.
I did everything according to your points (removed the proc_macro_hygiene and decl_macro) from main and put it in the webserver.rs, and also did:
use rocket::get and then

```#[get("/<name>/<age>")]``` before function

Unfortunatelly I've got this error now:
```
  Compiling hard v0.1.0 (/home/manio/IdeaProjects/hard)
error[E0658]: `macro` is experimental
  --> src/webserver.rs:14:1
   |
14 | #[get("/<name>/<age>")]
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #39412 <https://github.com/rust-lang/rust/issues/39412> for more information
   = help: add `#![feature(decl_macro)]` to the crate attributes to enable
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `hard`.

To learn more, run the command again with --verbose.
```

Whole source is now here (with webserver.rs):
https://github.com/manio/hard/tree/rocket-launch-test

**Comment by SergioBenitez** [comment]
@manio The documentation is correct. In fact, it must be: it's tested by the CI to compile and run correctly before being allowed to be published. Your issue is as follows: feature flags must be written in the crate root regardless of anything else. Thus, you must have the following in `main.rs`:

```rust
#![feature(proc_macro_hygiene, decl_macro)]
```

**Comment by manio** [comment]
Thank you very much Sergio!
After moving this to main.rs I've finally managed to compile my project and Rocket has launched!
```
2020-04-08, 18:37:43.290 [INFO] 🔧 Configured for development.
2020-04-08, 18:37:43.290 [INFO] address: localhost
2020-04-08, 18:37:43.290 [INFO] port: 8000
2020-04-08, 18:37:43.291 [INFO] log: normal
2020-04-08, 18:37:43.291 [INFO] workers: 4
2020-04-08, 18:37:43.291 [INFO] secret key: generated
2020-04-08, 18:37:43.291 [INFO] limits: forms = 32KiB
2020-04-08, 18:37:43.291 [INFO] keep-alive: 5s
2020-04-08, 18:37:43.291 [INFO] tls: disabled
2020-04-08, 18:37:43.291 [INFO] 🛰  Mounting /hello:
2020-04-08, 18:37:43.293 [INFO] GET /hello/hello (hello)
```

Thank you all guys. I am closing this issue...
