### ISSUE TITLE
h2spec tests

### ISSUE THREAD

**Issue by rustrust** [SergioBenitez/Rocket#1281]
For reliability and correctness rocket should add h2spec to testing

https://github.com/summerwind/h2spec

**Comment by jebrosen** [comment]
I haven't looked to closely at `h2spec`, but it appears to test mostly connection-level conformance. Rocket 0.4 does not support HTTP/2 at all, and even in the `async` branch this would probably all be handled by hyper. I'm going to close this as an upstream issue that should be opened against hyper, but I'm happy to reopen if it turns out that rocket does make a difference impact on test outcomes.
