### ISSUE TITLE
Registering a Tera template function with Rocket 

### ISSUE THREAD

**Issue by hyousef-rusty** [SergioBenitez/Rocket#1300]
I've the below Tera function, that I want to register with Rocket:
```rust
fn make_url_for(urls: BTreeMap<String, String>) -> GlobalFn {
    Box::new(move |args| -> Result<Value, Error> {
        match args.get("name") {
            Some(val) => match from_value::<String>(val.clone()) {
                Ok(v) => Ok(to_value(urls.get(&v).unwrap()).unwrap()),
                Err(_) => Err("Oops".into()),
            },
            None => Err("Oops".into()),
        }
    })
}
```
Usually it can be registered as:
```rust
    let mut tera = Tera::default();
    tera.register_function("url_for", make_url_for(urls));
```
I tried the below, but got an error:
```rust
#![feature(decl_macro, proc_macro_hygiene)]

use rocket_contrib::templates::Template;
use std::collections::{HashMap, BTreeMap};
use rocket_contrib::templates::tera::{GlobalFn, Tera, Value, from_value, to_value, Error};

use rocket::*;

fn make_url_for(urls: BTreeMap<String, String>) -> GlobalFn {
    Box::new(move |args| -> Result<Value, Error> {
        match args.get("name") {
            Some(val) => match from_value::<String>(val.clone()) {
                Ok(v) => Ok(to_value(urls.get(&v).unwrap()).unwrap()),
                Err(_) => Err("Oops".into()),
            },
            None => Err("Oops".into()),
        }
    })
}

fn main() {
    let mut tera = Tera::default();
    tera.register_function("url_for", make_url_for(urls));

    rocket::ignite()
    .mount("/", routes![root])
    .attach(Template::fairing())
    .launch();


}

#[get("/")]
fn root() -> Template {
    let mut context = HashMap::<&str, i32>::new();
    context.insert("value", 3);
    Template::render("index", context)
}
```

The error I got is:
```bash
error[E0425]: cannot find value `urls` in this scope
  --> src\main.rs:22:52
   |
22 |     tera.register_function("url_for", make_url_for(urls));
   |                                                    ^^^^ not found in this scope

error: aborting due to previous error
```

**Comment by jebrosen** [comment]
I see a few different problems here:

* You are trying to use `Template::fairing()`, which sets up `Tera` itself, and also your own `Tera` instance. You should use one or the other:
  * `Template::custom` instead of `Template::fairing`, will let you call `register_function`: https://api.rocket.rs/v0.4/rocket_contrib/templates/struct.Template.html#method.custom
  * You could also put your custom instance of `Tera` into managed state, but `-> Template` would not work if you do it that way. From your example, I think this approach would end up being more trouble and `Template::custom` fits your use case better.
* In `tera.register_function("url_for", make_url_for(urls))`, you are immediately calling `make_url_for` on some `urls`. But `register_function` needs the function itself: `tera.register_function("url_for", make_url_for).
  * The [helper function](https://docs.rs/tera/0.11.20/tera/struct.Tera.html#method.register_function) should take a `HashMap<String, Value>`, but yours takes a `BTreeMap<String, String>`.

I hope these help you find a solution.

**Comment by hyousef-rusty** [comment]
I defined it as:
```rust
fn main() {
    rocket::ignite()
    .mount("/", routes![root, hi])
   // .attach(Template::fairing())
    .attach(Template::custom(|engines|{
        let url = BTreeMap::new();
        engines.tera.register_function("url_for", make_url_for(url))
    }))
    .launch();
}
```

Thanks for your support
