### ISSUE TITLE
Cannot use Diesel embedded_migrations with rocket DbConn

### ISSUE THREAD

**Issue by miiila** [SergioBenitez/Rocket#1406]
## Bug Reports

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
0.4
  2. The operating system (distribution and version) where the issue occurs.
macOS Catalina 10.15.6
  3. A brief description of the bug that includes:
I want to run Diesel Embedded migrations macro (https://docs.diesel.rs/1.4.x/diesel_migrations/macro.embed_migrations.html) together with Rocket way of handling db connection (https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html).

However, I am getting an error:
```
error[E0614]: type `fn(db::embedded_migrations::diesel::r2d2::PooledConnection<<db::embedded_migrations::diesel::PgConnection as rocket_contrib::databases::Poolable>::Manager>) -> db::PostgresDbConn {db::PostgresDbConn}` cannot be dereferenced
```

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
```
use rocket_contrib::database;
use rocket_contrib::databases::diesel;

#[database("postgres")]
pub struct PostgresDbConn(diesel::PgConnection);

embed_migrations!("./migrations/");

pub fn run_migrations() {
    embedded_migrations::run_with_output(&*PostgresDbConn, &mut std::io::stdout()).unwrap()
}
```
  5. Ideas, if any, about what Rocket is doing incorrectly.

I also posted on Diesel GH (https://github.com/diesel-rs/diesel/issues/2477), getting a comment it is more a Rocket issue, therefore moving here.

Thank you for the help and thank you for a great framework to work with.

**Comment by jebrosen** [comment]
The problem is in this expression:

```rust
&*PostgresDbConn
```

`PostgresDbConn` is a type, and shouldn't be dereferenced. Since `PostgresDbConn` is of the form `struct X();` with parentheses, there is a [corresponding function](https://doc.rust-lang.org/reference/expressions/struct-expr.html#tuple-struct-expression) named `PostgresDbConn` - that function is what the misleading error message refers to.

What you are missing is a call to `PostgresDbConn::get_one`, to actually connect to the database. An example of this can be found in the `todo` example: <https://github.com/SergioBenitez/Rocket/blob/v0.4/examples/todo/src/main.rs#L81>

**Comment by miiila** [comment]
@jebrosen Thank you very much for an explanation. I got confused by examples at https://api.rocket.rs/v0.4/rocket_contrib/databases/index.html and I didn't realise the difference between using the value and the type (which sounds very silly and obvious from the current perspective :-). Thanks again for your help.
