### ISSUE TITLE
How to always redirect /foo to /foo/?

### ISSUE THREAD

**Issue by happycoder97** [SergioBenitez/Rocket#1415]
I need this functionality so that I can issue relative redirects.
I have this route:
```rust
// admin.rs

#[get("/")]
fn index() -> Redirect {
    if (is_logged_in) {
        Redirect::to("dashboard")
    } else {
        Redirect::to("login")
    }
}
```
which I mount like this: `.mount("/admin", admin::routes())`

The problem is that `index()` gets called when user navigates to both `localhost:8000/admin` and `localhost:8000/admin/`.
But the redirects have different behaviors in those two cases. The former redirects to `localhost:8000/login`, while the latter redirects to `localhost:8000/admin/login`, which is what I want. 

Is there any way to control this behavior?
I was thinking of some way to always redirect `/admin` to `/admin/` to avoid the former case. Is this possible?

---
I'm using Rocket v0.4.5.  
I've searched the Issues extensively. I could only find the converse of what I was trying to do: #1212   
It would be nice if Requests section of rocket.rs guide explains how trailing slashes in the url are handled.

**Comment by jebrosen** [comment]
The workarounds suggested in #1212 should still be usable here, by switching the redirect logic around. Another option might be to build the `Redirect`s with `uri!`, which always produces an `Origin` uri, instead of using relative locations: `Redirect::to(uri!("/admin", dashboard))`.

> I was thinking of some way to always redirect /admin to /admin/ to avoid the former case. Is this possible?

If you *only* need this for `admin`, you could also put the logic into the `index()` route (pseudocode):

```rust
#[get("/")]
fn index(uri: &Origin<'_>) -> Redirect {
    if !uri.path().ends_with('/') {
        return Redirect::to(uri + "/");
    }
    // ...
}
```

Of course, this gets pretty noisy if you need it in more places.


(cc #998; normalization and trailing slashes may need additional consideration for some of those issues)

**Comment by happycoder97** [comment]
This was exactly what I needed. Thanks :)
