### ISSUE TITLE
question about the hello_world examples

### ISSUE THREAD

**Issue by stardustman** [SergioBenitez/Rocket#1427]
environments  ares:
1. Rocket version is v0.4.5
2. OS: windows10
3. rustc 1.39.0 (4560ea788 2019-11-04)

when I run the hello_world example , the `subtle` crate has something wrong. 

![image](https://user-images.githubusercontent.com/22998204/92672868-4772ee80-f34c-11ea-8cfa-3ec4ea3b5903.png)
I'm learing to use Rocket. It seems the crate subtle has something wrong. how to fix this ? Thanks a lot.

**Comment by SergioBenitez** [comment]
The issue template asks you for extra information when reporting an issue; please read the issue template and post the requested information. Future reports without this information will be closed immediately.

I cannot replicate this with `rustc 1.48.0-nightly (e2be5f568 2020-09-09)` on macOS or Linux. Furthermore, the issue is in another crate, `subtle`.

**Comment by SergioBenitez** [comment]
Rocket requires an up-to-date version of `rustc`; so does `subtle`. See the [Getting Started Guide](https://rocket.rs/v0.4/guide/getting-started/) for details.
