### ISSUE TITLE
Registering a handlebars template from a String

### ISSUE THREAD

**Issue by bytebuddha** [SergioBenitez/Rocket#1446]
I'm trying to load a single template in the Template::custom closure like this:
```rust
.attach(Template::custom(|engines| {
        let template = include_str!("../frontend/static/index.html");
        engines.handlebars.register_template_string("index", template).unwrap();
}))
```
And the route i'm using to test is this:
```rust
#[rocket::get("/")]
pub fn index() -> Template {
    Template::render("index", &())
}
```

but when i attempt to open in the browser i get this error
```
GET / text/html:
    => Matched: GET / (index)
    => Error: Template 'index' does not exist.
    => Known templates:
    => Searched in '"/home/bytebuddha/Projects/rAdmin/templates"'.
    => Outcome: Failure
    => Warning: Responding with 500 Internal Server Error catcher.
    => Response succeeded.
```

So it seems my custom template string is not in the template engine.
Is there an example somewhere showing how to render a custom template string?

**Comment by jebrosen** [comment]
I believe this is the same as <https://github.com/SergioBenitez/Rocket/issues/850#issuecomment-447676229> and #462: the way `Template` works today is that it loads files from the `templates/` directory (or a different path if configured). So, `Template` doesn't know about the `index` template you added later that's not on disk.

For this example it doesn't look like you need to use templates at all, but if you do need a lot of templates registered as strings instead of files it *may* make more sense for your application to put an instance of [`Handlebars`](https://docs.rs/handlebars/3.5.0/handlebars/struct.Handlebars.html) in managed state instead of using `Template`.

**Comment by bytebuddha** [comment]
Ah i see, I only plan on having 3-4 templates anyway so using Handlebars as a managed State would work just fine
