### ISSUE TITLE
[Question] Dynamic mount path

### ISSUE THREAD

**Issue by marioreggiori** [SergioBenitez/Rocket#1463]
Is it possible to have dynamic segments in the mount path?
  1. The version of Rocket this question is based on, if any.
       **current**
  2. What steps you've taken to answer the question yourself.
     **Searched source code, api docs, guide & github issues**
  3. What documentation you believe should include an answer to this question.
     **Rocket guide (... if supported)**

I want to achieve something like this:
```rust
fn main() {
    rocket::ignite()
        .mount("/", routes![index])
        .mount("/users", routes![user_add, user_edit, user_delete])
        .mount("/project/<project_id>/events", routes![event_add, event_edit, event_delete])
        .mount("/project/<project_id>/something_else", routes![something_else_add, something_else_edit, something_else_delete])
        /* ... */
        .launch();
}
```
As far as I can tell this isn't possible. Are there any workarounds like internal forwarding or other ways to do this kind of 'route namespacing'?

**Comment by jebrosen** [comment]
In some ways this looks similar to #394 and #472; it's not possible to do this today.

There's at least one significant design question for supporting this: how would `event_add` know about `project_id`? Here's one example that does not compile today:

```rust
.mount("/project/<project_id>/events", routes![event_add])

#[get("/")]
fn event_add(project_id: &str) { }
```

This `#[get("/")]` fails to compile, because the values passed to `event_add` are based on where they appear in the route: the path or query parameter (`FromParam`, `FromQuery`), or the `data = "<param>"` syntax (`FromData`). Since `project_id` isn't in the path, it is treated as a [request guard](https://rocket.rs/v0.4/guide/requests/#request-guards) and must implement `FromRequest`, which `&str` doesn't.

In order to support specifying those in `mount` instead, `#[get()]` would need to instead generate some kind of "partial route", and `mount` would need to make sure all the missing inputs were actually given in the mount path. This would be a pretty significant change, and it seems to conflict pretty badly with other features (such as request guards). I'm not sure it would even be possible, since `#[get("/")]` needs to generate code to call `FromParam`, `FromData`, `FromRequest`, etc. -- but it's not known until `mount()` what code needs to be generated.

**Comment by marioreggiori** [comment]
Hi @jebrosen! Thank you for taking the time to write this answer!
What about only providing the mount segments via custom request guards like so:
```rust
struct Project {
    id: String,
};

#[derive(Debug)]
enum ProjectError {
    Missing,
}

#[rocket::async_trait]
impl<'a, 'r> FromRequest<'a, 'r> for Project {
    type Error = ProjectError;

    async fn from_request(req: &'a Request<'r>) -> Outcome<Self, Self::Error> {
        req
            .mount_segment("project_id")
            .map_or_else(
                || Outcome::Failure((Status::BadRequest, ProjectError::Missing)), 
                |project_id| Outcome::success(Project{id:project_id})
            );
    }
}

#[get("/")]
async fn index(project: Project) -> String {
    project.id
}

#[rocket::main]
async fn main() {
    rocket::ignite()
        .mount("/project/<project_id>", routes![index])
        .launch();
}
```

**Comment by jebrosen** [comment]
Sorry for the very belated response on this.

That looks plausible, although potentially a pretty big/complex feature to add. I think my main concerns are the complexity of supporting this and the runtime cost of matching on string-based keys (perhaps by hashing them). The current approach only matches the strings at compile-time and the lookup is done by a simple index.

**Comment by SergioBenitez** [comment]
I don't believe "mount points" themselves will ever be allowed to be dynamic, nor will I advocate for mechanisms to retrieve dynamic parameters without static typechecking. However, I have considered new mechanisms, which I internally refer to as "resources", to accomplish something similar in a fully static, type-safe manner. I will say more once I've worked out the solution a bit more.

Nevertheless, the question at hand has been answered.
