### ISSUE TITLE
Env configuration broken if spaces in databases

### ISSUE THREAD

**Issue by Razican** [SergioBenitez/Rocket#1470]
Using the latest master (https://github.com/SergioBenitez/Rocket/commit/fa77435187aaedda73b0caad0ab5bfdb24a8b476), I'm getting an error when using this environment variable:

```
ROCKET_DATABASES='{main={url="sth",pool_size=20 }}' cargo run
```

The error:
```
Error: database config error for pool named `main`
    => Error: invalid type: found string "20 ", expected u32: `POOL_SIZE` in /home/razican/.cargo/git/checkouts/rocket-bd3b2e391c4bd238/b638533/core/lib/src/config/config.rs:194:14
Error: Rocket failed to launch due to failing fairings:
    => 'main' Database Pool
```

Nevertheless, if I remove the space after the pool size, it works fine. It seems it's not correctly deserializing the JSON in the variable.

**Comment by jebrosen** [comment]
I *think* this is because figment's value parser is not treating `' '` as a separator in `is_not_separator` (<https://docs.rs/figment/0.9.4/src/figment/value/parse.rs.html#17>), or alternatively that it should call `trim()` before parsing.

**Comment by SergioBenitez** [comment]
That's interesting. This is certainly by design, but perhaps it's a rather deficient one. The question is: is `hi ` (with a trailing space) the string `"hi"` (without a trailing space) or the string `"hi "` (with a trailing space)? If it's the latter, should `20 ` really be an integer, or should it be the string `"20 "` as it is now? If the former, do we give up the ability to have significant leading and trailing space without quotes?

My answers are: `hi ` is `"hi"`, `20 ` is `20`, and you must use quotes to preserve leading/trailing whitespace: `"hi "` = `"hi "`.

**Comment by SergioBenitez** [comment]
This has been changed upstream: https://github.com/SergioBenitez/Figment/commit/23e4d7b26f79eb949330dca718ad49b7b8251e30
