### ISSUE TITLE
[Question] Using constant as path in route definition

### ISSUE THREAD

**Issue by tritone11** [SergioBenitez/Rocket#1473]
* Version: 0.4  
  
I am trying to use a constant definition or a field of struct in a lazy_static to define a post route, this way:  

```
....
const MY_PATH: &'static str = "/test";  

#[post(MY_PATH, data = "<request>")]
pub fn my_function(
....
```

However I get "expected literal or key/value pair".  
I read this documentation https://api.rocket.rs/v0.4/rocket/attr.post.html and tried with this:  

```
....
const MY_PATH: &'static str = "/test";

#[post(path=MY_PATH, data = "<request>")]
pub fn my_function(
....
```  
but with the same result.  
  
Is this even possible to do? Any suggestion? I would like to have all my paths stored in an external toml file to be loaded and edited without recompiling.  
  
Thanks

**Comment by jebrosen** [comment]
> I would like to have all my paths stored in an external toml file to be loaded and edited without recompiling.

This isn't easily possible in rocket's current design, because `#[post]` generates code at compile time and needs to know which parameter matches which type. Depending on what you are doing and how much of the path you need to be able to change in the configuration file, you might be able to use [`Route::new`](https://api.rocket.rs/v0.4/rocket/struct.Route.html#method.new) in some way to implement a similar feature.

**Comment by SergioBenitez** [comment]
> Is this even possible to do? Any suggestion? I would like to have all my paths stored in an external toml file to be loaded and edited without recompiling.

This isn't possible. If the path changes, it may change in a manner incompatible with the function definition. Without recompilation, we wouldn't be able to catch this before runtime, which would lead to confusing behavior at runtime at best, or soundness issues at worst. If compilation speed is the main concern, perhaps [tuning your config](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional) might prove helpful.
