### ISSUE TITLE
[Question] Rocket Simple Hello World with wascc (wasm)

### ISSUE THREAD

**Issue by david6983** [SergioBenitez/Rocket#1474]
I would like to know if the library is working with wasm using[wascc](https://wascc.dev/). My goal is to [krustlet](https://github.com/deislabs/krustlet) at the end. 

Thanks by advance

**Comment by jebrosen** [comment]
How were you thinking of putting these all together? I am not familiar with waSCC or krustlet, so I might misunderstand the question.

It looks like like there might be a few different ways to use waSCC, either alongside or instead of Rocket. The main example uses waSCC's HTTP server though, and I don't really know how difficult it would be to switch that part out for a Rocket-based server.

I have doubts that Rocket can run inside Krustlet without some pretty big changes. It looks like Rocket would have to compile to WASM in order to use it in krustlet, but WASM in rust doesn't seem to support the direct network connectivity that Rocket uses from `std` (and, in 0.5 once it's released, the `tokio` runtime - see also tokio-rs/tokio#1597).

**Comment by david6983** [comment]
Ok thank you for your response I just wanted to ask if it was possible and I understand what you mean.
