### ISSUE TITLE
No default toolchain

### ISSUE THREAD

**Issue by reportbase** [SergioBenitez/Rocket#148]
New user here.   I closely followed the installation instructions at https://rocket.rs/guide/overview/#routing.

I'm getting the following error:
no default toolchain configured

when I run the following command.
sudo ROCKET_ENV=stage cargo run

**Comment by impowski** [comment]
Are you using Rustup? And to you `ROCKET_ENV` you need to have a `Rocket.toml` where your `Cargo.toml`. [This](https://rocket.rs/guide/overview/#configuration) is covering it.

**Comment by SergioBenitez** [comment]
@impowski You don't need a `Rocket.toml` file to use the `ROCKET_ENV` variable. There are default values for all parameters, as mentioned in the documentation you linked.

@reportbase Did you follow https://rocket.rs/guide/getting-started/? In particular, the command `rustup default nightly` should resolve your issue.

**Comment by impowski** [comment]
@SergioBenitez Ah, forgot about default.

**Comment by mehcode** [comment]
Just want to chime in that the problem is rustup is a *user* installation and is affecting only your user's profile (perhaps this operates differently on Mac). I actually have the same issue.

Something like [using `env_keep`](http://stackoverflow.com/a/20540145) is needed here. I'd be nice if rustup took care of this automatically but it'd require sudo permissions and they wanted to avoid that.

**Comment by reportbase** [comment]
When I run:
rustup default nightly
rustc -V

the following is returned:
rustc 1.16.0-nightly (a52da95ce 2017-01-20)

When I run:
sudo env "PATH=$PATH" ROCKET_ENV=stage cargo run

the following is returned:
error: no default toolchain configured

**Comment by reportbase** [comment]
@SergioBenitez 

When I run:
rustup default nightly

the following is returned:
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.16.0-nightly (a52da95ce 2017-01-20)

**Comment by impowski** [comment]
@reportbase This question is related to `rustup`, so try to ask there or read their guide on it.

**Comment by mehcode** [comment]
@reportbase I'm going to guess something is up from your rustc / rustup configuration. I don't know enough about that to answer in more detail. Sorry, I did have the same problem as you and my work around worked for me.

**Comment by mgattozzi** [comment]
If you run cargo with sudo involved and you installed rust via rustup then it executes that command as root. Since root hasn't installed cargo or rust then it will fail. You'll need to install rust via rustup for root as well so you can run sudo commands.

**Comment by SergioBenitez** [comment]
@reportbase Have any of these suggestions resolved your issue?

**Comment by SergioBenitez** [comment]
Let us know if you weren't able to get this working, @reportbase!

**Comment by haheute** [comment]
I have the same issue on arch linux and did this: `sudo rustup default nightly-2017-03-16` to solve, which helped.
It installed everything again, so I think I have 2 installations of rust now, but don't know how to launch stage otherwise. The `nightly-2017-03-16` is because of [this](https://github.com/SergioBenitez/Rocket/issues/235)

**Comment by alexozer** [comment]
@haheute I think you're correct that bad terminfo settings on my part was causing problems (was manually setting TERMINFO to something else in zshrc). Sorry about this, I'll retract my comment.
