### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by thedrow** [SergioBenitez/Rocket#150]
Proper RESTful servers are able to receive and provide multiple representations of the same resource.
Since we'd rather avoid duplicating code or creating an endpoint per representation we should create a responder that resolves the correct de/serialization format using the Accept header.
The syntax should look like:
```rust
#[get("/todo")]
fn todo() -> AnyOf<JSON<Task>, Template> { ... }
```
With the `Status` and `Failure` types implicitly included in the set of possible return values.

As for the request body, we need to provide an API that specifies which Content-Types are allowed and deserialize accordingly.

**Comment by marcusball** [comment]
If the data struct—`Task` in your example—is the same regardless of the return representation, I think you could achieve this with a custom [Responder](https://api.rocket.rs/rocket/response/trait.Responder.html) wrapper. 

You could create an `Accept` request guard which would validate the requested content-type. In pseudocode, you could use a struct like `pub struct RestResponse<T>(T, ContentType) where T: Serialize;` then implement Responder for `RestResponse` which would `match` on the content-type, and then just return the result of the `.respond()` method for each supported type.

**Comment by thedrow** [comment]
I know it's possible to implement manually but I think that a web framework should be able to handle this.

**Comment by SergioBenitez** [comment]
With https://github.com/SergioBenitez/Rocket/commit/c58ca894b78eacce484316bd4856f7efca4efb8d, you can now handle this in one of two ways.

First, you can now set `format` in the route attribute for a `Get` request and it will match against the client's preferred media type in the `Accept` header. You can implement your small example as:

```rust
#[get("/todo", format = "application/json")]
fn todo_json() -> JSON<Task> { .. }

#[get("/todo", format = "text/html")]
fn todo_html() -> Template { .. }
```

Second, you can get the `Accept` header directly in the handler and return the appropriate response. Here, I'm using some fictional "Either" type:

```rust
#[get("/todo")]
fn todo_json(accept: Accept) -> Option<Either<JSON<Task>, Template>> {
    if accept.preferred() == MediaType::JSON {
        Some(JSON(...))
    } else if accept.preferred() == MediaType::HTML {
        Some(Template::render(...))
    } else {
        None
    }
}
```

With these, you can create a type like the one you propose, though it's probably not what you really want. I believe having a different route for each type you accept is the right way to go here: it's free documentation that's immediately obvious. Otherwise, a custom responder feels like the right thing here, too, and having `request.format()` makes one that does content negotiation really simple to implement.

**Comment by SergioBenitez** [comment]
With this, I feel like this issue can be closed. I'll wait a bit for feedback.

**Comment by thedrow** [comment]
I guess both options are Ok but sometimes you just want your API to respond with multiple encodings without any special behavior. It just feels that we're introducing boilerplate code for no reason.

**Comment by SergioBenitez** [comment]
@thedrow You can easily create a type that takes in the `Accept` header and returns one of several representation. I imagine that this kind of thing will be handled on a per `Responder` level. But, if there is a nice generalization of the idea, which at the moment I'm somewhat convinced there isn't, I'd be happy to revisit. In light of this, I'm closing this issue. Please do let me know if you find a nice, clean, general implementation!
