### ISSUE TITLE
Cache-Control and other headers for static served files.

### ISSUE THREAD

**Issue by Iqon** [SergioBenitez/Rocket#1522]
## Questions
Hello, I have a question (or if not possible a feature request).

I am using `rocket_contrib::serve::StaticFiles` to serve static files. However, I can't find anything on how to set the `control-control` header or any other header for that matter.

I would like to specify the `Cache-Control` header for the files to be immutable. to improve caching. 

The background: We have a server to render a static website, which should be cached using AWS Cloudfront. All static files will be generated to use unique names. The easiest way to use Cloudfront as a CDN is to set the `Cache-Control` header.

Rocket.rs (Serving the files with Cache-Control Header immutable) -> CloudFront is reading the files and caching them according to the header -> The user receives the files (and can cache them locally as well, as those files are immutable).

The current headers set in the response are:
![image](https://user-images.githubusercontent.com/3912681/106494883-42f5d080-64bb-11eb-8587-bf501808cc2c.png)

Any questions _must_ include:

  1. The version of Rocket this question is based on, if any.
```toml
rocket = "0.4.6"
[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["handlebars_templates", "json", "serve"]
```

  2. What steps you've taken to answer the question yourself.
I've done online research and looked in the docs, but couldn't find anything.

  3. What documentation you believe should include an answer to this question.
Either a link to an example, an example, or an explanation on how to achieve this. 

Thanks, and great work! I really enjoy using Rocket.rs.

**Comment by jebrosen** [comment]
I believe this is a new feature request.

We do have #1219 open, which would handle `Last-Modified` and `If-Modified-Since`. That optimizes caching a little bit by returning `304` when the file is unmodified instead of sending it to the client again.

`Cache-Control` (at least `max-age`) would be a nice addition, to tell clients to not even request the files at all for a certain time. With more of these requests it might be time to review all the headers `StaticFiles` could/should send, in case there are any problem combinations to think about before committing to supporting too many.

**Comment by Iqon** [comment]
@jebrosen Thanks for the quick feedback. So as a quick workaround, until the discussion on which headers should be supported is resolved, the only way is to implement this manually?

For reference, I've used a similar feature in `express.js` [Documentation](http://expressjs.com/en/resources/middleware/serve-static.html)


```ts
const options: ServeStaticOptions = {
    cacheControl: true,
    etag: false,
    immutable: true,
    index: false,
    maxAge: ms('1 year')
 };
app.use('/', express.static(path.join(basePath(), 'landing'), options));
```

It's quite similar to the config `rocket.rs` allows, plus cache control headers:

```js
/**
 * Enable or disable setting Cache-Control response header, defaults to true.
 * Disabling this will ignore the immutable and maxAge options.
 */
cacheControl?: boolean;

/**
 * Set how "dotfiles" are treated when encountered. A dotfile is a file or directory that begins with a dot (".").
 * Note this check is done on the path itself without checking if the path actually exists on the disk.
 * If root is specified, only the dotfiles above the root are checked (i.e. the root itself can be within a dotfile when when set to "deny").
 * The default value is 'ignore'.
 * 'allow' No special treatment for dotfiles
 * 'deny' Send a 403 for any request for a dotfile
 * 'ignore' Pretend like the dotfile does not exist and call next()
 */
dotfiles?: string;

/**
 * Enable or disable etag generation, defaults to true.
 */
etag?: boolean;

/**
 * Set file extension fallbacks. When set, if a file is not found, the given extensions will be added to the file name and search for.
 * The first that exists will be served. Example: ['html', 'htm'].
 * The default value is false.
 */
extensions?: string[] | false;

/**
 * Let client errors fall-through as unhandled requests, otherwise forward a client error.
 * The default value is true.
 */
fallthrough?: boolean;

/**
 * Enable or disable the immutable directive in the Cache-Control response header.
 * If enabled, the maxAge option should also be specified to enable caching. The immutable directive will prevent supported clients from making conditional requests during the life of the maxAge option to check if the file has changed.
 */
immutable?: boolean;

/**
 * By default this module will send "index.html" files in response to a request on a directory.
 * To disable this set false or to supply a new index pass a string or an array in preferred order.
 */
index?: boolean | string | string[];

/**
 * Enable or disable Last-Modified header, defaults to true. Uses the file system's last modified value.
 */
lastModified?: boolean;

/**
 * Provide a max-age in milliseconds for http caching, defaults to 0. This can also be a string accepted by the ms module.
 */
maxAge?: number | string;

/**
 * Redirect to trailing "/" when the pathname is a dir. Defaults to true.
 */
redirect?: boolean;
```

Additionally they allow to provide a callback to modify the response:

```js
function setCustomCacheControl (res, path) {
  if (serveStatic.mime.lookup(path) === 'text/html') {
    // Custom Cache-Control for HTML files
    res.setHeader('Cache-Control', 'public, max-age=0')
  }
}
```

The callback would allow for any customization. Plus, the framework has not to think about any incompatibilities or other problems. If the user wants to override the internal mechanism, any problems are up to the user.

I don't have enough rust experience to say if this config and a callback like this would be feasible or advisable.
But I am happy to contribute.

**Comment by jebrosen** [comment]
> So as a quick workaround, until the discussion on which headers should be supported is resolved, the only way is to implement this manually?

Yes. There are several ways you might implement this in the meantime:

* Fork `rocket-contrib` (or only `StaticFiles`) and make modifications there. Those same changes could be integrated into `rocket_contrib` if you or someone else submits a PR
* Create your own wrapper type implementing [`Handler`](https://api.rocket.rs/v0.4/rocket/trait.Handler.html) and `Into<Vec<Route>>` and owning a `StaticFiles` instance. The `Handler` method would call the `Handler::handle` method on `StaticFiles` and then set the cache-control headers
* Write an [`on_response`](https://api.rocket.rs/v0.4/rocket/fairing/trait.Fairing.html#method.on_response) fairing to set the cache-control header on routes you want it on

> I don't have enough rust experience to say if this config and a callback like this would be feasible or advisable.
> But I am happy to contribute.

Adding some configuration for `Cache-Control` headers does seem reasonable. A callback I am slightly less sure about since there are already several other approaches that could be used, but we can always try it and see what the API would look like with one.

**Comment by Iqon** [comment]
Great, I'll see what I can do. I would be happy to contribute. 

I don't think the callback is necessary, the workarounds, especially the `on_response` fairing should be more than enough to cover all special cases.

**Comment by SergioBenitez** [comment]
Accepted, and moving to tracking in #95.
