### ISSUE TITLE
about rocket!

### ISSUE THREAD

**Issue by puffanddmx** [SergioBenitez/Rocket#1525]
i have several questions about rocket!

1. If you run the rust executable file after creating the webserver using rocket, web access logs are kept. Can I change the setting so that only a specific log is left each time I run it? So that get/post logs are not left for every call.
2. Is a function like pm2 in nodejs available in rocket? Can I use crontab too? How many API connection requests can loadbalance be available? In rocket, workers seem to play a loadbalance role...
3. If you use rocket template, you can access html, can you put vue or react javascript-based language into rocket? If I build, can it be rolled up as a dist file? php lalavel using artisan to do such things, is it possible for rocket as well?

**Comment by jebrosen** [comment]
> If you run the rust executable file after creating the webserver using rocket, web access logs are kept. Can I change the setting so that only a specific log is left each time I run it? So that get/post logs are not left for every call.

I'm not sure I understand the question. Are you trying to change the log level so that you only see warnings and errors? The default log settings for debug builds include every route hit, but release builds shouldn't. The log level can also be changed in the [configuration](https://rocket.rs/v0.4/guide/configuration/).

> Is a function like pm2 in nodejs available in rocket? Can I use crontab too?

The closest equivalent is probably a system service or init script, depending on the operating system being deployed to. Rust binaries can be run directly, so `systemd` (for example) provides a lot of similar functionality to what `pm2` does for node.js.

> How many API connection requests can loadbalance be available? In rocket, workers seem to play a loadbalance role...

In Rocket 0.4, the maximum number of active connections is the number of `workers`. In Rocket 0.5 (the `master` branch) with `async` I/O, the number of connections is nominally unlimited but will be affected by available system resources. In any case we generally recommend running Rocket behind a reverse proxy such as `nginx` or `HAProxy`, in part because those tools have extensive and well-tested support for configuring details such as the number of simultaneous connections and timeouts.

> If you use rocket template, you can access html, can you put vue or react javascript-based language into rocket?

Sure, you can put whatever you like into templates or into static files! The main things you will need to do are set up the endpoints you want and make sure the right `Content-Type` is set for javascript files. [`rocket_contrib::serve::StaticFiles`](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html) does this automatically. You may need a separate step to compile your vue or react application if you are using webpack, in which case the contents of the `dist/` (or similar) directory are what you would need to serve.

> If I build, can it be rolled up as a dist file? php lalavel using artisan to do such things, is it possible for rocket as well?

Are you referring to this project: <https://github.com/satriaajiputra/laravel-dist>? It seems to make several zip files, but I'm not familiar with how one would go from those two files to a running installation on a server. Hopefully this can answer your question though: there is nothing "built-in" to automatically collect all files that are required at runtime. For a typical rocket application though, this would include at least:

* The compiled binary (e.g. `target/debug/package-name` or `target/release/package-name`).
* `Rocket.toml`, unless you use environment variables for configuration
* Templates. The default path is `templates/`, relative to the working directory at runtime.
* Static files. Files are searched in whatever directory was passed in to [`StaticFiles::new`](https://api.rocket.rs/v0.4/rocket_contrib/serve/struct.StaticFiles.html), which can be either a relative or absolute path.
* Runtime files needed for any other libraries you are using. This could be data files or files read at runtime similarly to templates - localization files, configuration, etc.
* Another common requirement is the client libraries for a database driver, if you are using a library that makes use of pre-existing C libraries that are dynamically linked.

**Comment by puffanddmx** [comment]
Thank you for a detailed description.

In fact, from a service point of view, is there a lot of difference when measured from a performance point of view when comparing nodejs express based webserver and rocket rust based webserver?

**Comment by puffanddmx** [comment]
Is there a function that automatically creates a default template (mysql controller/model/vue html/default login csrf/api/socket) when creating a project using rocket? It would be nice to make things that people use often.

**Comment by jebrosen** [comment]
> Is there a function that automatically creates a default template (mysql controller/model/vue html/default login csrf/api/socket) when creating a project using rocket? It would be nice to make things that people use often.

That's not currently a part of rocket, but it has been requested before in #701

**Comment by SergioBenitez** [comment]
Looks like this Q/A is complete! :)
