### ISSUE TITLE
Restrict Fairing to a route range

### ISSUE THREAD

**Issue by Iqon** [SergioBenitez/Rocket#1539]
Hello,
the title is maybe misleading. I am not sure what the best solution to my problem is:

I want to apply changes to all requests in a specific route range. I.E. set a specific header for all handlers matching `/api/*` or converting the result of all `/api/*` handlers to either JSON or XML depending on the request header.

The documentation states `Fairings are Rocket's approach to structured middleware`. The alternative `request guards` or `data guards` don't seem to be fitting either. But from what I understand, fairings can only be attached globally.

I want to attach something like a fairing, either:
- per mount
- or to anything matching `/base/` 

What would be the Rocket.rs way to implement this.

Sorry if this is a beginner question, but I couldn't find anything in the documentation and couldn't find a nice solution.
Thanks.

**Comment by jebrosen** [comment]
> I want to apply changes to all requests in a specific route range. I.E. set a specific header for all handlers matching `/api/*`

One way to do this would be with an `on_request` fairing. You can then check `request.uri()` against the base, and use methods like `request.add_header()` to modify the request. Another approach would be to use some kind of request guard in each `/api` route instead of modifying the original request.

> But from what I understand, fairings can only be attached globally.

I believe this is actually an intended limit in the original design of fairings (https://github.com/SergioBenitez/Rocket/issues/55#issuecomment-274687140). The more flexibility there is in which fairings are applied to which routes, the harder it becomes to trace the path from "start request" all the way to "route handler" for any one specific request.

> converting the result of all /api/* handlers to either JSON or XML depending on the request header.

This part is not easily done with a fairing: by the time `on_response` fairings run, the data to be sent to the client has already been generated from the responder type. A better solution for this might be a wrapping responder `JsonOrXml<T>` which responds with either JSON or XML:

```rust
pub struct JsonOrXml<T>(pub T);

// Note: untested, and rocket_contrib already provides a Json but not an Xml serializer
impl<'r, T: Serialize> Responder<'r> for JsonOrXml<T> {
    fn respond_to(self, req: &Request) -> response::Result<'r> {
        match todo!("check Accept or other header to determine how to respond") {
            Xml => something::Xml(self.0).respond_to(req),
            _ => rocket_contrib::json::Json(self.0).respond_to(req),
        }
    }
}
```

And use it in routes:

```rust
#[derive(Serialize)]
struct Numbers {
    pub small_number: u8,
    pub big_number: u32,
}

#[get("/numbers")]
fn numbers() -> JsonOrXml<Numbers> {
    JsonOrXml(Numbers { small_number: 5, big_number: 1000000 })
}
```

I hope this helps!

**Comment by Iqon** [comment]
@jebrosen Thank you very much for this elaborate response. This answers all my questions. Thanks!

Should I close this issue then?

**Comment by jebrosen** [comment]
> This answers all my questions. Thanks!

Glad I was able to help!
