### ISSUE TITLE
Rocket should log attaching fairings just like it logs when it mounts routes

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1543]
Version: 0.5.0-dev, latest

I have two fairings I attach. I see Rocket logs when I mount my routes, but no info is shown when fairings are attached.

At the very least I would like to log the fairing info at launch.

This seems like it would be useful for debug/support. You wrote a fancy new fairing, but Rocket isn't using it? Ooops, forgot to attach.

**Comment by jebrosen** [comment]
Implementation note: currently, non-attach fairings are listed by `Fairings::pretty_print_counts()` *after* checking that all fairings attached without errors. The names of attach fairings could be either 1) printed in `attach()` at the time they are attached or 2) stored to be printed later (before canceling the launch due to any errors).
