### ISSUE TITLE
Implementation of `FromDataSimple` for `Vec<u8>` and `String` in Release Build

### ISSUE THREAD

**Issue by davxy** [SergioBenitez/Rocket#1558]
I know that the issue was already been submitted in #1490 but currently I cannot find any reference to the solution/workaround to this.

If Rocket shall be build in debug mode only, is there a way to specify debug mode only for Rocket crate while build the rest of my application in release mode? (maybe a key in my project's Cargo.toml file?)

Thanks a lot

**Comment by jebrosen** [comment]
Building Rocket in debug mode is not a good choice here either: accepting an "unlimited size" `String` or `Vec<u8>` as a `Data` parameter in Rocket 0.4 allows any client to trivially cause the server to use arbitrary amounts of RAM until it crashes, at basically no cost to the client. That's why it was limited to only debug builds.

This happens to be one of the things that has been better resolved just recently, as part of commit 63a1452 in master! `String` will implement `FromData` in both debug and release modes, with an 8KiB limit by default (changeable via the ["string" limit in configuration](https://api.rocket.rs/master/rocket/data/struct.Limits.html)).

In Rocket 0.4, if you truly need this functionality I would recommend implementing it yourself via `data.open()` and only reading up to a limited total number of bytes.

**Comment by SergioBenitez** [comment]
Thanks for updating this, @jebrosen! Closing out.

**Comment by davxy** [comment]
Thank you, especially for your awesome work. Cheers
