### ISSUE TITLE
default config re-read for runtime setup fails when custom secret key is used

### ISSUE THREAD

**Issue by teymour-aldridge** [SergioBenitez/Rocket#1564]
## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible.

Rocket from the `master` branch

  2. The operating system (distribution and version) where the issue occurs.

MacOS, Catalina (I think)

  3. A brief description of the bug that includes:
    * The nature of the bug.
    * When the bug occurs.
    * What you expected vs. what actually happened.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.

I tried to launch the application with a custom secret key using the `lauch` proc macro. This failed.

See https://github.com/lovelace-edu/lovelace/blob/ui/main/src/main.rs#L45 for a use of the launch macro and how it overwrites the secret key set in https://github.com/lovelace-edu/lovelace/blob/ui/main/src/utils/mod.rs#L48.

  5. Ideas, if any, about what Rocket is doing incorrectly.

Apparently the configuration is overwritten by `async_main` before the application is launched which means that the secret key is not defined when trying to launch.

**Comment by SergioBenitez** [comment]
Context:

> Sergio
In fact, it's the difference between Tokio::main and Rocket::main that causes the issue. We read the config one more time just before we launch the runtime to set workers. In your case, you set the secret key programmatically, which isn't part of the default figment, so it isn't read by this second config, and hence the error.
The reason we do this, by the way, is because Tokio provides no way to set workers once the runtime is started.
> Teymour Aldridge
Ah right
> Sergio
https://github.com/tokio-rs/tokio/issues/3329
