### ISSUE TITLE
Disable "limits" in rocket

### ISSUE THREAD

**Issue by sergiupopescu199** [SergioBenitez/Rocket#1583]
Hi is there a way in rocket to disable all limits?Before asking here I searched a lot on internet. Currently I'm creating an API server which accepts a file and gives back the sha256sum, I don't know the file size so in limits I must provide a capacity

```rust
#[post("/hash", data = "<file>")]
pub async fn hash(file: TempFile<'_>) -> std::io::Result<()> {
    let o = file;
    println!("{:?}", o.path());
    let w = fs::read(o.path().unwrap()).unwrap();
    // println!("{:?}", w);
    let hasher = Sha256::new().chain(&w);
    let result = hasher.finalize();
    println!("hash sha256: {:x}", &result);

    Ok(())
}
```
this is my code, I'm using  TempFile, is there another way to handle files and limits? 
Thanks in advance any help for me is incredibly usefull!

**Comment by SergioBenitez** [comment]
There is not, and there won't be. Without a limit, your server is trivially susceptible to DoS attacks. Consider a large upload that exhausts the disk space on your machine, for example.

You should consider what the maximum file size you're willing to accept is and set your limit accordingly.

P.S: For your case, if you're really just computing a hash, you're almost certainly better off accepting a `Data` directly to avoid writing to disk at all. Then you could stream the bytes as they come in. If you're writing a streaming version of this, then you could theoretically set no limit and be somewhat okay as your memory usage will be about constant, but that request will still tie up considerable CPU and I/O resources, which are still useful to limit. Nevertheless, it seems that Rocket should provide an escape hatch here for streaming algorithms with constant memory usage.

**Comment by sergiupopescu199** [comment]
Thank you very much for your reply @SergioBenitez. I appologize for my lack of knolege but I slowly getting better with Rocket, I used `Data` as you sugested as example I used a simple txt file with "Hello Rocket!" inside of it, but every time I did a POST request was getting a different hash of the same file, which is very odd, then I converted the bytes in utf8 to see the content and I get this.
```
----------------------------809749238332470397950418
Content-Disposition: form-data; name="hello"; filename="o.txt"
Content-Type: text/plain

Hello Rocket!
----------------------------809749238332470397950418--
```
Now my question is how can I get only the content of my file?
I used nodejs and expressjs a lot to create api servers and there to extract the data I used `req.body` 

```rust
#[post("/hash", data = "<file>")]
pub async fn hash(file: Data) -> std::io::Result<()> {
    // println!("{:?}", w);
    let byt = file.open(10.megabytes());
    let o = byt.into_bytes().await.unwrap().to_vec();
    // println!("{:?}", o);
    let we = String::from_utf8(o.clone()).unwrap();
    println!("utf8-> {}", we);
    let hasher = Sha256::new().chain(&o);
    let result = hasher.finalize();
    println!("hash sha256: {:x}", &result);
    Ok(())
}
```
After resolving this I'll do everything non blocking as you suggested.
Thank you in advance for your help.

**Comment by SergioBenitez** [comment]
Are you submitting a form or are you uploading a raw file? If the former, which you need to do if you want to present an HTTP form to a user over a browser, then you need to use `Form`. Otherwise, you can use `Data`.

While your implementation is now a bit better as it won't trivially exhaust memory/disk space, it's still reading 10MiB into memory unnecessarily. You should read small-ish chunks of the data into a buffer (say `4k` or `16k` in size), call `update()` on the `Sha256` struct, and finally `finalize()` when you've read everything. There's also _no_ reason to call `from_utf8()`, and calling `unwrap()` on in a handler is a bad idea; it is trivial to make your handler panic.

If you're submitting a `Form`, you'll need to implement `FromFormField` to safely retrieve the internal data. Otherwise, you can do what you're doing now.

Here's pseudocode for an implementation:

```rust
struct Sha256Hash(GenericArray<u8, Sha256::OutputSize>);

#[rocket::async_trait]
impl<'r> FromFormField<'r> for Sha256 {
    async fn from_data(field: DataField<'v, '_>) -> rocket::form::Result<'v, Self> {
        use rocket::tokio::io::BufReader;
        use bytes::BytesMut;

        let limit = field.request.limits()
            .get("sha256")
            .unwrap_or(10.mebibytes());

        let stream = field.data.open(limit);
        let mut buffer = BytesMut::with_capacity(8.kibibytes().as_u64() as usize);
        while stream.read_buf(&mut buffer).await? != 0 {
            sha256.update(buffer.split());
        }

        Sha256(sha256.finalize())
    }
}

#[post("/", data = "<form>")]
fn sha256<'r>(form: Form<Sha256>) {
    /* ... */
}
```

You could also implement `FromData` for `Sha256` instead and then call that implementation inside `FromFormField`, allowing you to use `Sha256` both as a direct data guard (raw upload) or a form guard (form upload).

**Comment by sergiupopescu199** [comment]
Thank you for your suggestion I'll try it out. This is the only way to handle this?

**Comment by SergioBenitez** [comment]
> This is the only way to handle this?

No, but any correct, safe, and secure solution will resemble this. Note that only ~4 of those lines are Rocket-specific, and once they're written, they can be reused over and over.
