### ISSUE TITLE
How to write simple post method which returns String or Error status

### ISSUE THREAD

**Issue by Qeenon** [SergioBenitez/Rocket#1586]
I've use to read documentation twice but haven't found solution.

I was trying many ways

```rust
#[post("/go", format = "application/json", data = "<rp>")]
fn go(cookies: &CookieJar<'_>, _user: User, rp: Json<Login>) -> Status {
  if rp.password == "paswword" {
    cookies.add_private(Cookie::new("user_id", 1.to_string()));
    Status::new(200, "Successfully logged in.")
  } else {
    Status::NotFound
  }
}
```

or with `Result<String, Debug<String>>`

but all the time I'm getting Error:

```rust
POST /go application/json:
    => Matched: (login) POST /go application/json
    => Outcome: Forward
    => Error: No matching routes for POST /go application/json.
    => Warning: No 404 catcher registered. Using Rocket default.
```

and it's just confusing, it's matched but there is no matching routes, what? why?

**Comment by SergioBenitez** [comment]
Have you read through the guide? The handler is not running because a guard caused a forward. The log output here is quite close to perfect. Let's look at it:

  * POST /go application/json:

    This is the request that came in. Okay.

  * => Matched: (login) POST /go application/json

    We matched the `login` route!

  * => Outcome: Forward

    The login route forwarded. `Json` logs when it forwards, so it must be the
    `User` guard that forwarded. Okay, Rocket tries to find the next matching
    route.

  * => Error: No matching routes for POST /go application/json.

    There were no further matching routes. Time to 404.

  * => Warning: No 404 catcher registered. Using Rocket default.

    No 404 catcher was registed, so Rocket will issue its default.

**Comment by Qeenon** [comment]
Thank you, User was not needed as argument there, I just was thinking wrong about it.
