### ISSUE TITLE
Add Serialize/Deserialize support to rocket::http::uri::Uri enum

### ISSUE THREAD

**Issue by DanielJoyce** [SergioBenitez/Rocket#1593]
This would make loading of Uris from config files, etc nicer.

I looked at the Url crate, but it's api is a mess and it has some very unintutiive behaviors.

**Comment by DanielJoyce** [comment]
I looked at the Url crate, but it's api is a mess and it has some very unintutiive behaviors.

**Comment by SergioBenitez** [comment]
We should absolutely do this. Note that we _don't_ use the `Url` crate; we have our own implementation of URIs.

I'm happy to accept a PR for this. Implementation should be rather straightforward to/from a string.

Some notes for those wishing to submit a PR:
  * The changes should be reflected in `rocket_http`.
  * The changes should be gated by the `http` crate's `serde` feature.
  * The implementation should likely be a manual implementation of `(De)Serialize` to/from string.
  * All of the `Uri` variants should support (de)serialization.
  * Tests should be added.
  * The URI docs should be updated to mention support for (de)serialization of `Uri` and friends.

**Comment by the10thWiz** [comment]
I'm interested in working on this issue. I have taken a look at the rocket_http crate, and it is fairly straight forward to add the serde traits to `Uri`. I have not touched the http crate outside of Rocket, since it doesn't appear to have a serde feature.

Implementing Serialize and Deserialize is easy, especially since a Uri is always serialized as a string. This is especially easy since I am relying on the existing `TryFrom` and `Display` impletations to do the heavy lifting. I have added serde_json as a dev-dependency to make testing the Serialize and Deserialize implementations easier.

I have discovered that the existing `Uri` parsing doesn't seem to be as stable as it should be. There are a number of edge cases my testing has found, see [https://github.com/the10thWiz/Rocket/blob/2b82ec9bd1aaeed75f02ec78d791f69fe1cf69b4/core/http/src/uri/uri.rs] for the full tests. The current implementation accepts '&', '.', and a range of other odd uris as valid, as well as a curious set of empty parts. For example, 'example.com/test?' is not a valid Uri, but '/test?' is. You can take a look at `serde_invalid_uri` and `serde_empty_parts` to see which Uris cause errors, and which don't.

There are a few other quirks of the Uri parsing I discovered, that are documented in the `serde_quirks` test.
