### ISSUE TITLE
Unused routes don't generate unused warnings

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#1598]
Functions decorated with a Rocket route attribute do not generate a warning, even if they are otherwise unused:

```rust
#[rocket::get("/")]
fn foo() { }
```

This is a "regression" of sorts introduced by the mechanism in 092e03f7207941f9585db4a2d04dbc08c731e5db. It would be more than ideal if we could emit code that results in `rustc` generating the appropriate warning.

**Comment by the10thWiz** [comment]
I'm interested in working on this issue. I'm not super familiar with proc macros, or rocket's internals, but it looks to me like the fact that the function is used within the implementation of `From<route> for ::StaticInfo` prevents the compiler from providing an unused warning.

One way to avoid this is to implement the methods on the struct itself, rather than as a trait. This does solve this issue (with a reasonably small patch to the codegen), but I suspect it might cause other issues with more complex codebases. It does expose 1 or 2 methods to the user, in a way that doesn't feel like it should make sense, but I think this might be a reasonable trade-off.

Can you provide some guidance on what issues this patch might cause?

I will be submitting the patch as a pull request shortly.
