### ISSUE TITLE
Serving static files with multiple segments

### ISSUE THREAD

**Issue by Megidd** [SergioBenitez/Rocket#1607]
I'm using Rocket [multiple segments](https://rocket.rs/v0.4/guide/requests/#multiple-segments) to serve static files, by this code:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

use std::path::PathBuf;
use rocket::response::NamedFile;
use std::path::Path;

#[get("/public/<file..>")]
fn files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}

fn main() {
    rocket::ignite()
        .mount("/public", routes![files])
        .launch();
}
```

With the above server, requests for files at `/public/<path..>` should be handled by returning the contents of `/static/<path..>`, right?

Then on my browser, I enter the domain name along with `/public/` and a multipe-segment route path, for example, a `*.jpg` file, but it cannot serve the file:

[![404 error][1]][1]

As far as I check, the JPG file exists. I cannot figure out what I'm missing!

  [1]: https://i.stack.imgur.com/l2ABX.png

**Comment by Megidd** [comment]
UPDATE
--

I also tried to use a builtin module to do so:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

use rocket_contrib::serve::StaticFiles;

fn main() {
    rocket::ignite()
        .mount("/public", StaticFiles::from("/static"))
        .launch();
}
```

But it's not working either. Not sure why!

**Comment by jebrosen** [comment]
> With the above server, requests for files at /public/<path..> should be handled by returning the contents of /static/<path..>, right?

Not quite: with that handler, a request for `/public/a/b.txt` would be served by the file `static/a/b.txt` relative to the current working directory at the time of calling `NamedFile::open`, not necessarily `/static/a/b.txt`.

> As far as I check, the JPG file exists. I cannot figure out what I'm missing!

I can't tell much from that screenshot, except that it looks like `assets` is repeated.

> But it's not working either. Not sure why!

Unlike your first code sample, this one *would* respond to `/public/a/b.txt` with the file `/static/a/b.txt`, because you gave an absolute path (`/static`).


My best guess so far is that it's either the double `/assets/assets/`, a relative path where you wanted an absolute, or not starting the server in the expected working directory. If it's not one of those things, the log output would be helpful for troubleshooting this further.

**Comment by Megidd** [comment]
Thanks to @jebrosen problem got resolved.

To resolve:

1. Notice the absolute vs relative path difference: `.mount("/", StaticFiles::from("static"))` means static folder should be next to the server executable.
2. Run the server executable in the proper working directory and place `static` folder next to it.
