### ISSUE TITLE
Cannot handle an HTTP URL as a query parameter in Rocket

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [SergioBenitez/Rocket#1609]
Hello, hope you're doing well.
To be clear I am a beginner. I'm using the latest version of both Rocket and Rust nightly to create a simple web app and here's where I got stuck.

```rust
#[post("/make/<link>")]
fn shorten_link(link: String) -> String {
    // Some other code
}
```

The problem is when I post to let's say `http://localhost:8000/make/https://youtube.com/` I get redirected to the Rocket `404` page but when I do something like `http://localhost:8000/make/hello` everything works fine. I don't understand what I am doing wrong here so any help will be appreciated, thank you.

Before opening this issue I have asked this question on StackOverflow also. 

Here's the link: https://stackoverflow.com/questions/67130874/cannot-handle-a-http-url-as-a-query-parameter-in-rocket

**Comment by jebrosen** [comment]
> I don't understand what I am doing wrong here so any help will be appreciated, thank you.

The answer to the linked post is right: the 404 is because `<link>` matches exactly one segment of a path. Note that the a multi-segment path may fix this particular example, but it would still do the wrong thing with a URL with a query string such as `https://www.youtube.com/watch?v=fFDbzbHjaZQ`. percent-encoding (aka url-encoding) is the canonical approach to sending URLs inside other URLs.

> > Edit: My full code looked like this (it was just a simple test):
> > ```rust
> > #![feature(decl_macro)]
> > 
> > use rocket::{local::Client, post, routes};
> > 
> > #[post("/make/<link>")]
> > fn shorten_link(link: String) -> String {
> >     link
> > }
> > 
> > fn main() {
> >     let rocket = rocket::ignite().mount("/", routes![shorten_link]);
> > 
> >     let client = Client::new(rocket).expect("valid rocket instance");
> >     let req = client.post(format!(
> >         "/make/{}",
> >         urlencoding::encode("https://youtube.com/"),
> >     ));
> >     let mut resp = req.dispatch();
> >     println!("{}", resp.body_string().unwrap());
> > }
> > ```
>
> Isn't there any other way of doing this? I don't want to declare a separate variable for all my routes

There probably are other ways to do this depending on what exactly you are trying to do, but the suggested approach looks pretty close to what I would have suggested first myself. Which particular line of the example is the "separate variable" that you don't like about this solution?

**Comment by MichaelGrigoryan25** [comment]
To be honest I don't like this part

```rust
    let client = Client::new(rocket).expect("valid rocket instance");
    let req = client.post(format!(
        "/make/{}",
        urlencoding::encode("https://youtube.com/"),
    ));
    let mut resp = req.dispatch();
```

I have to do this just to make the parameter urlencoded and I mean, it's somehow long and messy.

**Comment by jebrosen** [comment]
> I have to do this just to make the parameter urlencoded and I mean, it's somehow long and messy.

This is test code to demonstrate that the approach works; the code you would actually use to encode the URL depends on the programming environment on the client side. For example, in browser JavaScript you might use `encodeURIComponent`:

```javascript
let uri = "https://example.com/make/" + encodeURIComponent("https://youtube.com/...");
fetch(uri, { method: "post" });
```

**Comment by MichaelGrigoryan25** [comment]
Yeah you're right, I can do that on the client side. I'll close this issue now

**Comment by SergioBenitez** [comment]
> To be honest I don't like this part
> 
> ```rust
>     let client = Client::new(rocket).expect("valid rocket instance");
>     let req = client.post(format!(
>         "/make/{}",
>         urlencoding::encode("https://youtube.com/"),
>     ));
>     let mut resp = req.dispatch();
> ```
> 
> I have to do this just to make the parameter urlencoded and I mean, it's somehow long and messy.

On `master`, this is simply:

```rust
client.post(uri!(shorten_link: "https://youtube.com/"));
```

This is type-safe and URI safe, does exactly what you want, is shorter to type, and easier to maintain.

**Comment by markg85** [comment]
Second old rocket issue i'm replying on.. Second rocket bug i encounter that's closed but not with a solution that works for me.

I too want to pass a full url as argument and i too hit against the issue that it's.. well.. not possible.
Yes, with processing. But that adds a layer of complexity at another level. I can't control that a url coming in conforms that standard or not. But then again, a url like `https://youtube.com/https://youtube.com/` is completely valid syntactically.

I'm hoping for an option that effectively translates to "give me everything after `/` in a variable". However i handle the data in that variable is of no concern to rocket.

So i expect with this curl request:
`curl -s -X POST http://127.0.0.1:8000/https://youtube.com/`

To have this function work:
```
#[post("/<link..>")]
fn foo(link: String) -> String {
    // link = "https://youtube.com/"
}
```

That's not such a weird request or expectation, is it?

**Comment by neilskilling-overskilling** [comment]
I think if you pass it as an actual query parameter (following a '?') then this should all just work. At the moment you are specifying a path which is too complicated. Something like this should work:

```http://<myserver>/?url=https://foo.tld/image.png```

Would it be difficult to pass it as a query parameter?

**Comment by markg85** [comment]
> At the moment you are specifying a path which is too complicated.

Do elaborate on that please. Nginx can handle that just fine. Many many many frameworks can handle that just fine. Is it too complicated?

I would expect that:
```
#[post("/<link..>")]
fn foo(link: String) -> String {
  // ..
}
```

or 
```
#[post("/*")]
fn foo(link: String) -> String {
    // ..
}
```

I would expect that either one of these options is semantically perfectly fine to handle this.

I doubt the query route to be stable. What if the url itself has a query in there somewhere? Yeah, i'm guessing that will break. So i prefer to not go the query argument route. The fix you'd then suggest is url encoding which would put me back to the start as that isn't an option.

In fact - and i'd hate to use this - i am already using this very mechanism in nginx where i'm proxying the passed url to a backend server. Which is as simple as just passing on the `$request_uri` in nginx. You probably agree with me that it would be complete nonsense to use another webserver to work around a limitation of the other, right? ;)

**Comment by neilskilling-overskilling** [comment]
The query parameter value for the URL should definitely be encoded otherwise it might break somewhere else down the chain. That is fairly standard practice which is the way that all adtrackers bounce you from server to the next by taking the next bit of a URL query parameter and then passing on to the next one in the chain. 

If you go down the query parameter route you will avoid a lot of problems. My comment on the path being too complicated is not necessarily on the capability of expression a method for that in Rocket as you have shown. But the parsing of what is part of the actual method path and what is in your case clearly a parameter to that method should not be combined into a single whole as that makes it very difficult to extract one from the other. You are fighting one of the most useful parts of the URI syntax and putting "https://" partway through a path is just asking for trouble. Make life easier for yourself and use a query parameter.

**Comment by markg85** [comment]
I don't see how using a query parameter make my life any easier at all.

I'm using this mechanism to cache images. But i'm also using this very same mechanism to "download an image locally". Same server, dual purpose. I simply can't urlencode the url as it comes from outside the codebase that handles the query. Or do you suggest me to urlencode in every place where i might be using it. Thus completely losing the ability to simply `<prefix>/<url>` an existing url like in my browser.

It **has** to be the url as a whole for my usecase without urlencode requirement.

So i really do have to use another server to urlencode it just to satisfy how Rocket works... Rocket is an amazing framework that makes it super simple to do webserver tasks but i **really** need to have this feature to work. If a patch is acceptable that implements it in one of the ways i showed then i'd be more then happy to work on that and contribute it. But if rocket is of the opinion that this is a hard no then i might have to reconsider using this.

**Comment by the10thWiz** [comment]
There are a number of safety concerns with the implementations you suggest.

First, the 'proper' solution. Assuming the client is in js, encoding the url for use in a query parameter is accomplished via `encodeURIComponent()`. When Rocket parses the query parameters from the URL, it'll automatically decode it. This is generally the industry standard. For example, most modern email clients replace all URLs in the body of an email with a url safety checker. For example, Gmail uses urls like this: `https://www.google.com/url?q=https://www.ups.com&source=gmail&ust=1743287277041000&usg=AOvVaw2nTW6r_0m9XhIq5GHlogsF`.

Now the actual issues with your proposed solutions:

You suggest the following code should simply return everything after the `/` as a string:
```rust
#[post("/<link..>")]
fn foo(link: String) -> String {
  // ..
}
```

However, there are a couple issue here. First, Rocket done a number of pre-processing steps to a URL before passing it to the user. A number components are stipped out, including empty components (e.g. `https://yt` -> `https:/yt`), single dots (e.g. `/a/./b` -> `/a/b`), and double dots, along with the segment before them (e.g. `/a/b/../c` -> `/a/c`). The first one already causes issues for your use case, but is defined as part of the url spec.

Second `<link..>` takes path components *up to the query `?`*. This means that `/https://youtube.com/watch?v=dQw4w9WgXcQ` loses the `v=dQw4w9WgXcQ`.

URL encoding might potentially also throw a wrench into this idea as well, since the browser applies some (nessecary) url encoding, and rocket decodes it. I'm not sure what issues this might cause.

All that being said, if you have some external spec to meet, or some other really good reason to try this, there is a work around. You could bypass Rocket's url decoding by adding `url: &Origin<'_>` as a request guard, and parsing the url yourself, something like:

```rust
#[post("/<_..>")]
fn foo(url: &Origin<'_>) -> String {
  format!("{}", url).strip_prefix("/").unwrap().to_string()
}
```

This is somewhat more difficult to use (the origin contains the mount point, so you also have to remove that), and you do lose the benefits of Rocket's strict URL parsing.

**Comment by markg85** [comment]
> First, the 'proper' solution. Assuming the client is in js, encoding the url for use in a query parameter is accomplished via `encodeURIComponent()`. When Rocket parses the query parameters from the URL, it'll automatically decode it. This is generally the industry standard. For example, most modern email clients replace all URLs in the body of an email with a url safety checker. For example, Gmail uses urls like this: `https://www.google.com/url?q=https://www.ups.com&source=gmail&ust=1743287277041000&usg=AOvVaw2nTW6r_0m9XhIq5GHlogsF`.

As i told before, the whole notion of url encoding is irrelevant and impossible. I intent to use this on a server where essentially anyone can prefix any url with this server. I want that to work hence urlencoding is simply not a thing because putting that as a requirement makes it's use not as straightforward as just prefixing an existing url.

Now realistically i'd be the only user of this (a tool for me to cache images) and i'd probably be using it in some other programming languages (likely Rust and Dart). JS is just completely irrelevant, i never hinted at it and it's not my intent to use. I do however not want to rule out direct in=browser usage (in the url bar) hence i **require** it to work from there too. And that frankly simplifies my tool use a lot too.

> All that being said, if you have some external spec to meet, or some other really good reason to try this, there is a work around. You could bypass Rocket's url decoding by adding `url: &Origin<'_>` as a request guard, and parsing the url yourself, something like:
> 
> #[post("/<_..>")]
> fn foo(url: &Origin<'_>) -> String {
>   format!("{}", url).strip_prefix("/").unwrap().to_string()
> }
> This is somewhat more difficult to use (the origin contains the mount point, so you also have to remove that), and you do lose the benefits of Rocket's strict URL parsing.

Thank you so much for that little snippet! I couldn't find that kind of detail in the API so this really helps a lot! I just tried it and this does exactly what i need!

Could you perhaps explain where and how you found it? I personally just can't get used to Rust's documentation, it's so vague compared to what i know (C++). But knowing that there is an `url` argument with an `Origin` object is simply something i couldn't find and still can't find... The very page where i would expect `url` to be mentioned is [this one](https://api.rocket.rs/v0.5/rocket/route/struct.Route#routing) but the whole word `url` (nor `Origin`) even occurs...

**Comment by the10thWiz** [comment]
Your using the `#[get]` and `#[post]` macros, so you would actually want to check the documentation for them: https://api.rocket.rs/v0.5/rocket/attr.get. Under the typing requirements, it explains how each parameter is decoded. In this case, since `url` doesn't have an associated declaration in the pathc or data, it is constructed using it's `FromRequest` implementation.

If you check the `FromReqeust` docs (https://api.rocket.rs/v0.5/rocket/request/trait.FromRequest#implementors) under implementors, you'll see a list of all types defined by Rocket that can be used as a request guard.

**Comment by markg85** [comment]
Ahh, i found those pages too. What confuses the hell out of me is the complete arbitrary use of `url` which seems to be coming out of nowhere and still somehow magically works. Even with the links you provide, `url` is just not there.

Now i'm curious if i'm reading this specific logic in Rust wrong. Should i read it as "there is a implementation for `Origin`, you can use it however you see fit". Thus merely using an argument that has the `Origin` type fills that argument (`url` in this case, but might as well be `foo` or `bar` or `wtf`)?  Is that how i should read it?

**Comment by markg85** [comment]
Oke, nevermind that, figured it out. Yes, it's working based on the type. The argument name is irrelevant (might as well be `something_completely_different`, it would've worked exactly the same).

Perhaps this is a getting used to how things work.. I'm not a fan of this magic syntax. It makes sense to have a argument of a certain type, that's how programming works in many languages (rust too). Ugh... no i don't like this. Oh well, i do get it now, guess that's a win ;)

**Comment by blackghost1987** [comment]
This "magic syntax" is what the `get` macro does, basically you annotate your custom function with it + give it a route specification string, then it will "wrap" the function in a way that it will be called with the proper arguments. For that to work, you have to make sure the function arguments match the parts in the route specification you gave.
Also the name of the argument is NOT irrelevant, it has to match the name of the dynamic route segments! The documentation mentions it here: https://api.rocket.rs/v0.5/rocket/attr.get#typing-requirements

You can think of your function as a lambda / callback / function pointer or something like that you might be familiar with from other languages. It doesn't have a fixed signature, it just have to match whatever will call it, but the calling code is not your concern in this situation.

In the function signature you also have to specify the types of those parameters, and each of those have to be a "guard" of a certain type, depending on where it gets the data from (path, query params, request body, etc.). You could also optionally add more guards that are not specified in the `get` macro, e.g. to automatically process request headers or provide global context and such.

So a guard is defining a "conversion" of a HTTP request (or a part of it) to a value of a given type. The "magic" in the macro is just looking at the names and types of the guards and calling them one by one, to convert the request (or the global state) into a list of arguments that can be digested by your function.

This is just a simplified overview of how Rocket works, I'm not sure it 100% matches the things under the hood, but I hope it helps with understanding the concept.

**Comment by markg85** [comment]
@blackghost1987 Thank you for that! That helps a lot in understanding this.

Regarding the name relevance. Am i correct that in _this_ case it's irrelevant? As `url` doesn't exist.

I still find it super weird and just fugly that rust even allows this kind of syntax. Sure, it "looks" nice and tidy when you can rely on the examples. But when those aren't there and you want something that is just slightly different (like my case) then that very same syntax bites back. Mind you, code completion also doesn't work on it. It's as if it doesn't exist at all yet it compiles/runs. I would find it less of a "wtf is this?" when tooling would explain me what the heck went on. [Zed](https://zed.dev/) at least doesn't know.

Oh well, i'm happy it works! I have a lot to learn in the black magic arts of Rust and libraries using it to their full extend like Rocket.

**Comment by the10thWiz** [comment]
Yes, in this case, the name `url` doesn't matter. The only time the parameter names matter to the get macro (or other route macros) is when it's matching against the name in the route's path.

Sadly, Rust macros are hard to offer full code completion for. This is true for other languages, since macros can offer arbitrarily complex replacements. This is also why we try to keep the macro syntax to a minimum.
