### ISSUE TITLE
secrets feature handling too restrictive for workspace users

### ISSUE THREAD

**Issue by toxeus** [SergioBenitez/Rocket#1630]
I have a cargo workspace with lots of crates. Many of them spin up a rocket server. *One* of them spins up a rocket server with the `secrets` feature enabled. Due to how feature unification in cargo currently works it also enables the `secrets` feature for all other crates. This by itself is fine. 

But [this check](https://github.com/SergioBenitez/Rocket/blob/3a7559edcec7c443e68e22e038aaa2d90ef27c23/core/lib/src/rocket.rs#L476-L481) forces me to add a dummy `secret_key` to all crates that use rocket that don't intend to use the `secrets` feature which is a bit ugly.

Moreover, I would argue that because of the dummy key workaround the intend of the check is compromised: once a user decides to actually use the `secrets` feature in an additional create he might forget to change the dummy key altogether.

**Comment by SergioBenitez** [comment]
Can you clarify your project structure? Cargo only unifies across a workspace when you run commands on the workspace itself. If you build each crate individually, it shouldn't unify. However, if crates are depending on each-other, then a single crate enabling the feature causes all transitive dependents to also have the feature enabled. What is your structure?

Nevertheless, why not specify a valid, secure key instead of a dummy key? If one project is using a real key, then surely key management of some sort is already occurring and adding another key wouldn't be too laborious.

**Comment by toxeus** [comment]
> Cargo only unifies across a workspace when you run commands on the workspace itself

Exactly, that's what I'm occasionally doing and that's what most CI systems always do.

> adding another key wouldn't be too laborious

That is debatable. Key management by itself is laborious. Also, even if the key is not dummy it will be treated as such.

**Comment by SergioBenitez** [comment]
> Exactly, that's what I'm occasionally doing and that's what most CI systems always do.

The CI does exactly what you want it to do. Still, `secrets` checking only happens when compiling in release or when running in a non-debug profile, which shouldn't be the case during development.

> That is debatable. Key management by itself is laborious.

I never claimed otherwise. My claim is that if you're managing one key, then managing two is an incremental change.

> Also, even if the key is not dummy it will be treated as such.

I'm sorry, I don't follow. An unused but secure key is still secure.

In all, if the `secrets` feature is enabled, then your application can encrypt/decrypt secrets. Without a safe, secure key, the application is liable to being trivially insecure. I cannot imagine changing my stance to one where Rocket allows shows trivial insecurity to proceed without failure. Were a warning sufficient, we'd have a solution. Alas, even errors go unnoticed if not fatal.

Cargo gives us workspace-level feature granularity with an opt-out of building individual crates. Alternatively, you can define a secure secret key even if it goes unused. There are two solutions to your problem, neither of which I find overbearing giving the advantage to Rocket's current functionality.

**Comment by toxeus** [comment]
> I'm sorry, I don't follow. An unused but secure key is still secure.

You are right on a technical level but it this will not work on a human level. People will generate keys with infinite lifetime, they will share it across all instances that require a dummy key, etc., etc.

> Cargo gives us workspace-level feature granularity with an opt-out of building individual crates.

I didn't know about that. How do I opt-out? I only know about the opt-in via `default_members`. 

> Alternatively, you can define a secure secret key even if it goes unused.

Yes, this is the dummy key workaround I'm currently applying. Maybe we don't use the same terminology but for me "unused" == "dummy". Doing that feels like a hack.

> There are two solutions to your problem, neither of which I find overbearing giving the advantage to Rocket's current functionality.

I don't feel strong about this and can live with the dummy key hack. I'm just one of the few users using rocket master and wanted to share my experience. If you want to force your users to apply dummy keys then that's your choice. I'm pretty sure other users will be surprised by this too once 0.5 is released.

**Comment by SergioBenitez** [comment]
> I didn't know about that. How do I opt-out? I only know about the opt-in via `default_members`.

Simply call `cargo` on individual crates instead of the entire workspace. Again, Rocket only does this check for production build/deploys. Writing a script that builds each crate individually is rather straightforward and would assuage all of your concerns. You would never need to run the script during development since Rocket emits only a warning then, and you can make the script part of your release cycle otherwise.

> If you want to force your users to apply dummy keys then that's your choice.

I want encourage good practices, and make bad practices impossible when possible. No software can force you not to mismanage keys, but we can encourage good behavior.

> I'm pretty sure other users will be surprised by this too once 0.5 is released.

Your situation is rather atypical. Nevertheless, I suspect most users will simply say, "oh, yeah, I guess I need a key here too," and proceed to generate/manage a new key securely, or at least as securely as they were before. This is exactly the desired effect.

I hope you find at least one of the now three solutions to be amenable to your situation. If there's something we can do to make this easier without removing the check, please feel free to comment.

**Comment by toxeus** [comment]
> Writing a script that builds each crate individually is rather straightforward and would assuage all of your concerns. You would never need to run the script during development since Rocket emits only a warning then, and you can make the script part of your release cycle otherwise.

That's just another workaround rather than a solution. I was hoping to learn something that I didn't already know.

> Your situation is rather atypical. 

I think mono-repos a quiet popular.

Just one more thing I'd like to clarify: For non-release builds an unset key triggers the generation of a random key. What is insecure about that random key that it's forbidden to be used in a release build?

**Comment by SergioBenitez** [comment]
> > Writing a script that builds each crate individually is rather straightforward and would assuage all of your concerns. You would never need to run the script during development since Rocket emits only a warning then, and you can make the script part of your release cycle otherwise.
> 
> That's just another workaround rather than a solution. I was hoping to learn something that I didn't already know.

There is nothing to workaround. This is the way cargo works. You have the option to use a workspace and run commands for the entire workspace with features unified across it, use a workspace and run commands individually when needed, or not use workspaces at all. 

> > Your situation is rather atypical. 
> 
> 
> 
> I think mono-repos a quite popular.

This has nothing to do with monorepos and everything to do with a workspace; use of one does not implicate the use of the other. You have multiple crates in a single workspace that, it sounds like, could easily be made into multiple workspaces or simply individual crates.


> Just one more thing I'd like to clarify: For non-release builds an unset key triggers the generation of a random key. What is insecure about that random key that it's forbidden to be used in a release build?

It's not forbidden to use a generated key per-launch; you can do that yourself rather trivially. Rocket already provides all the needed functionality. Simply, Rocket doesn't do this by default. The issue is - and the reason Rocket denies this by default - that a restart of the server would yield all previous secrets unusable. That is, one of confusion and usability. This isn't a conjecture: Rocket initially generated a key in all profiles, then environments, when one wasn't given, with a warning, of course. The warning was ignored, and folks were confused when a restart meant that users were logged out of their session. Hence the current behavior.
