### ISSUE TITLE
[Feature] Access to managed objects on Rocket shutdown

### ISSUE THREAD

**Issue by JarvisCraft** [SergioBenitez/Rocket#1707]
# Feature Requests

## Description

In #1079 the [shutdown mechanism](https://docs.rs/rocket/0.5.0-rc.1/rocket/struct.Shutdown.html) was added in order to allow API users to:

- trigger shutdown via `Shutdown::notify(self)`
- wait for shutdown via `Shutdown::await`

The latter is the subject of this feature request.

While the await approach seems to be a common one, it still does not cover cases in which the shutdown awaitor requires access to Rocket and especially its managed states:

Currently there can be two approaches for finalization:
- spawning a tokio task awaiting on the shutdown object done in a faring's closure in its `on_ignite` or `on_liftoff`:
```rust
AdHoc::on_ignite("Add finalizer", |rocket| {
    let shutdown = rocket.shutdown();
    rocket::tokio::spawn(async {
        shutdown.await;
        /* shutdown action */
    });

    Ok(rocket)
)
```
This is the most obvious approach but it cannot capture `rocket` into closure body due to an obvious lifetime conflict.

- register a finalizer-state whose destructor will perform the finalization action:

```rust
AdHoc::on_ignite("Add finalizer", |rocket| {
    struct Finalizer;
    impl Drop for Finalizer {
        fn drop(&mut self) {
            /* shutdown action */
        }
    }

    Ok(rocket.manage(Finalizer))
)
```

This approach looks like a dirty hack and still does not provide a way to access Rocket's state.

## Motivation

There are cases in which it is needed to run finalization which requires access to Rocket-managed states such as a database.

## Example

In my use-case a Rocket-powered service generates a temporary API token on startup via a managed database instance (currently, a `&State<sqlx::PgPool>` until #1696 gets integrated) which I would like to revoke on Rocket shutdown. In order to do it I need both access to the `rocket.shutdown().await` mechanism and `rocket.state::<sqlx::PgPool>()`. The only place in which this can be done are:
- Fairing's `on_`s which yet have to complete without indeterminate awaits thus making it impossible to use `rocket.shutdown().await`.
- Route functions, but these obviously correspond to separate requests.

The only ways in which this *may* be implemented is by:
- wrapping the managed database object into a smart-pointer like `Arc` and using it with the `spawn`-based approach, but this requires `Arc` overhead for all operations on this object while it is needed (except for its regular usage) only once on shut-down; moreover this may only work for some specific use-cases and would not work with `rocket(_sync)_db_pools`; generally it would be an architecture design error as it would require the required object to be aware of the need to be `Arc`ed which would also make this approach unusable with foreign crates
- **a really dirty hack**: provide a *private* route (such as guarded by an `AtomicBool` CASed to `false` on first request) as routes do have access to both `Shutdown` and `State` / `impl FromReqest` and perform `await` and shutdown action in this route and *ping* this route on Rocket's liftoff in a `spawn`ed task.

## Reasons to be part of Rocket

This feature has to be implemented as part of Rocket itself rather than as a separate crate as it is related to core Rocket functionality (especially its lifecycle) and requires access to members currently unavailable in the API (i.e. rocket instance on shutdown).

## Possible design

This may be implemented as an additional method of `trait Fairing` such as `async fn on_shutdown(&self, _rocket: &Rocket<Parachute>) { }` and the corresponding `AdHoc` function which was suggested in #1576.

**Comment by jebrosen** [comment]
> In order to do it I need both access to the `rocket.shutdown().await` mechanism and `rocket.state::<sqlx::PgPool>()`. The only place in which this can be done are:

For database pools (maybe not all, but certainly `sqlx`), there is another option already available: retrieve and clone the `PgPool` after it has been added to managed state, and use the clone after shutdown. The connection pool already uses `Arc` (or something similar) internally. I've also tentatively made "you can easily get to and/or clone the database pool itself" part of the public API for `rocket_db_pools` in #1696.

That aside, I do think that having access to managed state is sufficient reason to reconsider adding a method `Fairing::on_shutdown()`.

**Comment by JarvisCraft** [comment]
> For database pools (maybe not all, but certainly sqlx), there is another option already available: retrieve and clone the PgPool after it has been added to managed state, and use the clone after shutdown.

Thanks, this worked :rocket:

However, this leads to another problem, async task does not seem to be executed after `shutdown.await` returns the control flow (yet, it may be just me doing something wrong): 
![image](https://user-images.githubusercontent.com/7693005/122317547-6713f480-cf26-11eb-8b22-c1900225f969.png)
![image](https://user-images.githubusercontent.com/7693005/122317532-60857d00-cf26-11eb-85e3-23e34327f972.png)

**Comment by jebrosen** [comment]
Hm, right. I see at least two issues with that approach if you are using `#[launch]`. First, the "main" task (running the rocket server) exits and the program stops; it does not wait for spawned tasks to exit. This can be solved by using `#[rocket::main]` instead of launch, and putting shutdown code after `.launch().await`. The second issue you might run into is <https://api.rocket.rs/v0.5-rc/rocket/config/struct.Shutdown.html#runaway-io> - by default, once connections and requests are finished (or the grace period is over), the server will be force-killed shortly after.

e.g. (pseudocode):

```rust
#[rocket::main]
async fn main() {
    let rocket = rocket::build().manage(/* database pool */);
    let db_pool = rocket.state::<PgPool>()

    rocket.launch().await;

    let connection = db_pool.get().await;
    // ...
}
```

**Comment by j4ger** [comment]
I also encountered this issue recently when I was trying to save the state of a serial generator on server shutdown, and had to take a different approach by performing the serialization to file in the `fn drop`. Nevertheless a proper shutdown listener or something like that would be much more elegant for such occasions. It could be a trait which can be implemented by managed states, providing a function to do clean-ups on shutdown.

**Comment by the10thWiz** [comment]
This is an interesting case. Out of curiosity, what actions are you hoping to take between Rocket starting shutdown, and the db connection being closed? I'm assuming you want to write some entries into a database table (e.g., logging the shutdown event).

I do think this is something we should support if possible, but I'm not convinced there is a simple option. Perhaps this should be handled by some kind of pool specific feature, since it could then provide trivial access to the db.

**Comment by cormacrelf** [comment]
Yeah, it's a matter of flushing a last batch of queued writes. Queueing and executing later on a background task is faster than round tripping in situ. It's not a huge issue if the writes are lost (hence just yeeting into a queue) but it's nice to try to write them since there is a batch waiting. 

The workaround (dedicating a pool connection to the background task, which survives beyond pool close) did work. It's a bit of a waste of a pool connection but not a big deal.
