### ISSUE TITLE
`Serialize` bound on rocket_contrib::Template::render is too broad, allows passing invalid context

### ISSUE THREAD

**Issue by shepmaster** [SergioBenitez/Rocket#175]
This came up in a [Stack Overflow question](http://stackoverflow.com/q/42063537/155423). The OP was doing something like:

```rust
fn index() -> Template {
    let serialized = "hello".to_string();
    Template::render("index", &serialized)
}
```

Which has a run-time error of

```
Error: Error rendering Tera template 'index': Failed to value_render 'index.html.tera': context isn't an object
```

**Comment by SergioBenitez** [comment]
Unfortunately, as far as I can see, there's nothing great Rocket can do here. `Serialize` is the trait that Tera/Handlebars require, and so that's essentially what we have to use. We could imagine adding a new trait to Rocket, `ObjectLikeSerialize`, that implies `Serialize` and can only be implemented for "object-like" items, but I imagine that would be cumbersome at best and very confusing at worst.

If you have any suggestions about how we might improve this, please do let me know. Otherwise, I'm inclined to close this issue.

**Comment by SergioBenitez** [comment]
Unfortunately I don't think there's anything reasonable we can do to make this less error-prone. Closing the issue as result.
