### ISSUE TITLE
db_pools: Unwrapping Connection<T> into T

### ISSUE THREAD

**Issue by roy-ganz** [SergioBenitez/Rocket#1790]
**Allow unwrapping `Connection<T>` into T  in `db_pools`**

I'm developing an ORM that uses `mysql_async` and the new async `dp_pool` crate. Currently I experience some friction between both Rocket's `db_pool` and `mysql_async`. 

- `mysql_async` provides the  [Queryable](https://github.com/blackbeam/mysql_async/blob/master/src/queryable/mod.rs) trait to abstract over a connection and a transaction. The trait is only implemented for a value, not for a mutable reference.
- `Connection<T>` from `db_pools` only implements `deref` and `deref_mut`.  It's not possible to unwrap it into its inner value.

**Suggested Changes**

Add `into_inner()` to `Connection<T`> so that it's possible to unwrap.

**Alternatives Considered**

It would also be possible change mysql_async's side and to implement the `Queryable` trait for `&mut Conn`. I made a [request](https://github.com/blackbeam/mysql_async/issues/165) for that. This would be more ergonomic for Rocket users, because of `deref` support from the Rust language. However in Toql (my ORM), I have to wrap the connection/transaction to actually call the library methods and I prefer wrapping values to references. 

**Context**
Currently I have a locally patched version of db_pool and added the function. I could provide you a pull request. I'm testing my ORM and plan to release a beta on `crates.io` once I'm done. Until then I'm looking for an ergonomic Api for users.

**Comment by jebrosen** [comment]
> * mysql_async provides the Queryable trait to abstract over a connection and a transaction. The trait is only implemented for a value, not for a mutable reference.
> * Connection<T> from db_pools only implements deref and deref_mut. It's not possible to unwrap it into its inner value.

Can you show a short example of something you want to be able to write today but can't because of this missing functionality? I'm not sure I understand what the proposed change accomplishes, since `DerefMut` *should* already provide access to any methods that take `&mut self`.

**Comment by roy-ganz** [comment]
This is my situation:
```
// ...
#[get("/<id>?<query..>")]
pub async fn get( id: u64, conn: Connection<DbConn>, cache: &State<Cache>){
    let mut toql =  MySqlAsync::from( ???, &cache);    
    //                                 ^-- Here I get sqeezed between Rocket and mysql_async, see below
    
    let u = toql.load_one( query!(User, "*, id eq ?", id)).await?;
    Ok(Json(u))
}
// ...
```
The backend driver (here MySqlAsync) must be able to wrap a connection or transaction. On the `toql` object the ORM functions can then be called.
The Problem: From `Rocket` I can only get a `&mut DnConn`. But `mysql_async` implements the [Queryable](https://docs.rs/mysql_async/0.28.0/mysql_async/prelude/trait.Queryable.html) trait only for `DbConn` (value). 

Right now, I have solved it like this:
```
//...
  let mut toql =  MySqlAsync::from( conn.into_inner(), &cache);    
//...
```
I cloned the Rocket repo and added the `into_inner()` function to `Connection`, so that I can unwrap it.
- Not ergonomic for users
- However I think unwrapping `Connection` should still be allowed to get a value, for the usual Rust tradeoff (Less troubles than &mut, but also less performance)

Personally I preferred this
```
//...
  let mut toql =  MySqlAsync::from(&mut conn , &cache);    
//...
```
- Better ergonomics
- Needs [Queryable](https://docs.rs/mysql_async/0.28.0/mysql_async/prelude/trait.Queryable.html) implemented on [&mut Conn](https://docs.rs/mysql_async/0.28.0/mysql_async/struct.Conn.html)
- More coding work than solution above

Frankly, either way, I don't really mind. But without a solution I cannot depend my crates on public dependencies, which blocks the upcoming beta release. 
It's my last day before vacation today. I will have time to work on this in the beginning of september. So there is no rush.

Have a nice summertime.

**Comment by jebrosen** [comment]
Okay, I think I understand the mismatch now. This problem is not relevant for all engines, but might affect a few more besides `mysql_async`:

* The equivalent `sqlx` methods take an `E: Executor`, which is implemented for references to connections or transactions, and therefore doesn't have this problem
* The equivalent `diesel` methods (not relevant, but for comparison's sake) take an `&Connection`, and wouldn't have this problem
* `tokio-postgres` has a similar trait, `GenericClient`, which may have the same problem
* `redis` has a similar trait, `ConnectionLike`, which may have the same problem

There are a few different kinds of solutions here:

* Your APIs might be able to use e.g. `&mut X where X: Queryable` instead, similarly to `diesel`. This may not be as ergonomic as the other approaches, but it should be doable without modifying either `rocket` or `mysql_async`
* `mysql_async` could implement `Queryable for &mut Q where Q: Queryable`, along the same lines as traits such as `std::io::{Read,Write}`, `serde::{Serialize,Deserialize}` which make use cases including this one more ergonomic
* `rocket_db_pools` could add an `into_inner()` method. I actually don't see any immediate problems with doing this today; my only hesitation is that it would not play nicely with an `impl Drop for Connection` should we want to add one in the future. I don't expect that we would need that, so in my eyes this is probably worth doing.
