### ISSUE TITLE
Better caching in Json::from_data?

### ISSUE THREAD

**Issue by JonasCir** [SergioBenitez/Rocket#1795]
Hi,
thank you for creating this awesome crate! While playing around with the `FromData` trait, I noticed the following (potential) missed opportunity for better caching in `Json::fromData`.

**Existing Functionality**
Take a look at the code [here](https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/serde/json.rs#L192). What strikes me as odd is:

1. that the loading of the string contained in the request body is _done every time_  the function is called
2. that the unparsed string is cached with `local_cache` instead of the _result_ of `Self::from_str` which does the actual work

**Suggested Changes**

1. Try to cache the parsed _result_ of  `Json::from_str` and not the _input_
2. Maybe there is a chance to cache the complete function altogether

```rust
    async fn from_data(req: &'r Request<'_>, data: Data<'r>) -> Result<Self, Error<'r>> {
        request.local_cache(|| {
              let limit = req.limits().get("json").unwrap_or(Limits::JSON);
              let string = match data.open(limit).into_string().await {
                 Ok(s) if s.is_complete() => return Self::from_str(s.into_inner());
                 Ok(_) => {
                    let eof = io::ErrorKind::UnexpectedEof;
                    return Err(Error::Io(io::Error::new(eof, "data limit exceeded")));
                 },
                Err(e) => return Err(Error::Io(e)),
             };
        });
    }
```
I didn't test this code, though.

**Alternatives Considered**

I might be completely wrong with what I just wrote and everything is fine :)

**Comment by SergioBenitez** [comment]
> * that the loading of the string contained in the request body is _done every time_  the function is called

The function is called _at most once_ per request, so work is never duplicated. This is guaranteed by the type-system due to `Data` being owned.

> * that the unparsed string is cached with `local_cache` instead of the _result_ of `Self::from_str` which does the actual work

This _has_ to be the case. The string is stored in `local_cache` so that references to it live as long as the request itself. This allows the deserialized value to borrow from the string as opposed to requiring it to own all parts of the string it references thereby reducing allocations. Storing the _result_ of de-serialization would mean either _not_ allowing borrows to the string in the deserialized value, defeating the purpose entirely, or creating a use-after-free when the buffered string is dropped.

**Comment by JonasCir** [comment]
@SergioBenitez Thank you for your explanation! I understand it now :smiley:
