### ISSUE TITLE
Is it possible to share something like Crossbeam's MsQueue between rocket routes?

### ISSUE THREAD

**Issue by stephanbuys** [SergioBenitez/Rocket#188]
Hi, I'm trying to create a production app that accepts data from various endpoints, I parse the requests into some data that I then want to forward to a thread that will commit the data to disk or an external source. I was hoping to use `crossbeam::MsQueue` for the purpose (http://aturon.github.io/crossbeam-doc/crossbeam/sync/struct.MsQueue.html)

I'm not really experienced with concurrency and its limitations with rust (and rocket by implication), but I seem to have been able to get the `MsQueue` shared via rocket's new `State`, but I can't get my consuming thread to work.

Is this possible? Am I on the wrong track? Any recommendations for this kind of scenario?

Thanks!

**Comment by SergioBenitez** [comment]
This should totally be possible, and it's kind of a neat demonstration! What issue are you having on the consuming side? Presumably you're not seeing messages being pushed? How are you sharing the queue across multiple threads? Maybe you can post a simplified version of your code!

**Comment by stephanbuys** [comment]
Hi sure, here is what I was going for, the idea is to have the one thread consume and do something with the data received. `MsQueue` is `Sync` and `Send`:

```rust
extern crate crossbeam;

use crossbeam::scope;
use crossbeam::sync::MsQueue;
use rocket::State;

struct LogChannel(MsQueue<Event>);

#[post("/test?<event>")]
fn test(event: Event, queue: State<LogChannel>) -> &'static str {
    queue.0.push(event);
    "got it"
}

fn main() {
    let q : MsQueue<Event> = MsQueue::new();

    scope(|scope| {

        scope.spawn(|| {
            loop {
                match q.try_pop() {
                    Some(e) => println!("{:?}",e),
                    _ => {}
                }
            }
        });

        scope.spawn(|| {
            rocket::ignite()
                .mount("/", routes![test])
                .manage(LogChannel(q))
                .launch();
        });

    });
}
```

**Comment by SergioBenitez** [comment]
It looks like you're moving `q` to the `LogChannel` in the `manage` call, but you're also borrowing it in `scope.spawn`; does this code compile? You might be using two completely different queues?

Looking at the `MsQueue` documentation, it looks like the way you're supposed to share the queue is via an immutable reference. I don't see a `Clone` or `Copy` implementation which is really odd for this type of structure. If this is indeed the case, then you need to ensure you're using the same reference in the managed state and in your other thread, and you'll need to ensure that the reference has a `'static` lifetime since this is required for managed state.

I'm not sure why `MsQueue` doesn't have a `Clone` implementation that allows you to easily share the structure, it's certainly a bit odd. Maybe you're meant to put it behind an `Arc`? That should solve the sharing and reference problems.

**Comment by stephanbuys** [comment]
@SergioBenitez awesome, that works, my concurrency foo ran short to figure the `Arc<...>` requirement out, but the following code works fine, I'll so a PR for an example app if you want?

```rust
extern crate crossbeam;

use crossbeam::scope;
use crossbeam::sync::MsQueue;
use rocket::State;
use std::sync::Arc;

struct LogChannel(Arc<MsQueue<RawEvent>>);

#[post("/test?<event>")]
fn test(event: Event, queue: State<LogChannel>) -> &'static str {
    queue.0.push(event);
    "got it"
}

fn main() {
    let q : Arc<MsQueue<Event>> = Arc::new(MsQueue::new());

    scope(|scope| {

        scope.spawn(|| {
            loop {
                match q.try_pop() {
                    Some(e) => println!("{:?}",e),
                    _ => {}
                }
            }
        });

        scope.spawn(|| {
            rocket::ignite()
                .mount("/", routes![test])
                .manage(LogChannel(q.clone()))
                .launch();
        });

    });
}

```

**Comment by SergioBenitez** [comment]
Sure, a PR for an example would be great! The hardest part is naming the example...

**Comment by stephanbuys** [comment]
Hope the example name doesn't seem to trivialize the other example, I couldn't come up with a better name after 5 minutes 😄

**Comment by SergioBenitez** [comment]
Looks like this question is answered! Let's get the example in soon. :)
