### ISSUE TITLE
support variant forms at a single url

### ISSUE THREAD

**Issue by rbtcollins** [SergioBenitez/Rocket#1937]
**Is your feature request motivated by a concrete problem? Please describe.**

We wanted to implement an https://datatracker.ietf.org/doc/html/rfc6749 (Oauth2) server in rocket but ran into a challenge with the token endpoint that accepts several different types.

If forwarding of Form worked - rather than it returning an error and shortcutting the forwarding process, then this would work:
```
#[post("//form", data = "<somedata>", rank = 1)]
fn body1(somedata: Form<Body1>) -> String { ... }

#[post("//form", data = "<somedata>", rank = 2)]
fn body1(somedata: Form<Body2>) -> String { ... }
```

Where Body1 / Body2 etc are the different possible token endpoint call types.

Alternatively, if deriving a data-containing FromForm enum worked then that would be fine:
```
#[post("//form", data = "<somedata>", rank = 1)]
fn body1(somedata: Form<Body>) -> String { 
   match somedata {
      Body::Case1(data) => {}
      Body::Case2(data) => {}
      ...
   }
}
```

We're currently working around it all with a form that has every field, then serialising it to json and deserialising to a type with variants. But https://github.com/nox/serde_urlencoded looks interesting.

**Why this feature can't or shouldn't live outside of Rocket**

This is a feature request on the core capability of processing forms. 

**Ideal Solution**

I think permitting forwarding between routes with a Form<> guard will result in cleaner code, so would prefer that to work.

@ngerstle-cognite who started this project.

**Alternatives Considered**

**Additional Context**

Add any other context here, for example, descriptions of elegant solutions in other software.

**Comment by SergioBenitez** [comment]
> If forwarding of Form worked - rather than it returning an error and shortcutting the forwarding process, then this would work:

This is incompatible with Rocket's enforcement of data streaming. Rocket's doesn't buffer the incoming data: it's parsed as it's read. As a result, a forward to another route because a form failed to parse would imply that the data has been consumed. Thus, the second route would always fail. Of course, this is statically disallowed in Rocket to prevent such an issue.

> Alternatively, if deriving a data-containing FromForm enum worked then that would be fine:

This would require the `FromForm` implementation itself to buffer data to try multiple parses, again something we'd like to avoid. `serde` suffers greatly from trying to implement such a strategy: see all of the [`enum` issues in the `serde` repository](https://github.com/serde-rs/serde/issues?q=is%3Aissue+is%3Aopen+enum).

A "good" solution would allow you to determine which form you'd like parse using information that's available early on. The information would be in a header, the URL, or even the form itself. For the latter, you'd need to implement a custom data guard that uses the [`Data::peek()`](https://api.rocket.rs/master/rocket/data/struct.Data.html#method.peek) to determine if it should try to parse the form and if so use the form's `FromData` implementation or otherwise forward.

The other alternative is to implement a buffering version of the `Form<T>` data guard which can try multiple instances. I think this is too error-prone to include in Rocket itself, but it's entirely possible to implement outside of Rocket via the available `From::parse()` and `Form::parse_encoded()` methods or the `FromData` implementation of `Form<T>`.

**Comment by SergioBenitez** [comment]
Unfortunately I don't see Rocket adopting a buffered approach anywhere, so I'm closing this issue.

**Comment by thomasmost** [comment]
@SergioBenitez does this also mean that request forwarding with cascading Json data guards is impossible?

My use-case is implementing a Plaid webhook, like so:

```rs

#[derive(Deserialize)]
pub struct TransactionsUpdateWebhookPayload {
  pub webhook_type: String,
  pub webhook_code: String,
  pub item_id: String,
  pub error: Option<String>,
  pub new_transactions: u128,
}

#[post("/webhook", data = "<payload>", rank = 1)]
pub async fn webhook_transactions_update(
  payload: Json<TransactionsUpdateWebhookPayload>,
) -> Status {
  ...
}

#[derive(Deserialize)]
pub struct SyncUpdatesAvailableWebhookPayload {
  pub webhook_type: String, // "TRANSACTIONS"
  pub webhook_code: String,
  pub item_id: String,
  pub error: Option<String>,
  pub historical_update_complete: bool,
  pub initial_update_complete: bool,
}

#[post("/webhook", data = "<payload>", rank = 2)]
pub async fn webhook_transactions_sync(
  payload: Json<SyncUpdatesAvailableWebhookPayload>,
) -> Status {
  ...
}```
