### ISSUE TITLE
Multiple files in multipart form when using fields of type `&'r str` are not parsed correctly

### ISSUE THREAD

**Issue by pnevyk** [SergioBenitez/Rocket#1987]
**Description**

When parsing multiple files sent through `multipart` form request into fields of type `&'r str`, all fields are populated with contents of the first file if the form parameters are passed with `filename` directive (i.e., in curl terms using `param=@file.txt`, not `param=<file.txt` or `param=contents`). The behavior is correct if the fields have type `String`. I would expect all the fields having the file contents of respective form parameters, as is the case when using `String`.

**To Reproduce**

*Cargo.toml*

```toml
[package]
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
```

*main.rs*

```rust
#[macro_use]
extern crate rocket;

use rocket::form::Form;

#[derive(Debug, FromForm)]
struct BadData<'r> {
    foo: &'r str,
    bar: &'r str,
}

#[post("/bad", data = "<data>")]
fn bad(data: Form<BadData<'_>>) -> String {
    format!("{:?}\n", data)
}

#[derive(Debug, FromForm)]
struct GoodData<'r> {
    foo: &'r str,
    bar: String,
}

#[post("/good", data = "<data>")]
fn good(data: Form<GoodData<'_>>) -> String {
    format!("{:?}\n", data)
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![bad, good])
}
```

*foo.txt*

```
Hello
```

*bar.txt*

```
World
```

*Requests*

```bash
curl -X POST --form "foo=@foo.txt" --form "bar=@bar.txt" http://localhost:8000/bad
curl -X POST --form "foo=@foo.txt" --form "bar=@bar.txt" http://localhost:8000/good
```

The request on the "bad" endpoint gives:

```
Form(BadData { foo: "Hello\n", bar: "Hello\n" })
```

whereas the request on the "good" endpoint gives:

```
Form(GoodData { foo: "Hello\n", bar: "World\n" })
```

as I expected.

**Expected Behavior**

The request `curl -X POST --form "foo=@foo.txt" --form "bar=@bar.txt" http://localhost:8000/bad` should return this response:

```
Form(BadData { foo: "Hello\n", bar: "World\n" })
```

**Environment:**

 - OS Distribution and Kernel: Arch Linux 5.13.12
 - Rocket Version: 0.5.0-rc.1

**Additional Context**

* If owned type (`String`) is used for either field, it works as expected.
* If either parameter is not sent as a file (i.e., not including `filename` directive in the request), it works as expected. That is, all these combinations give expected, correct response:
```bash
curl -X POST --form "foo=<foo.txt" --form "bar=@bar.txt" http://localhost:8000/bad
curl -X POST --form "foo=@foo.txt" --form "bar=<bar.txt" http://localhost:8000/bad
curl -X POST --form "foo=<foo.txt" --form "bar=<bar.txt" http://localhost:8000/bad
```

**Comment by pnevyk** [comment]
I have no familiarity with Rocket codebase, but with some pointers and advice, I can give fixing it a try, if it is confirmed as a bug.

**Comment by SergioBenitez** [comment]
Confirmed. Working on a fix now.

**Comment by SergioBenitez** [comment]
This bug occurs because of an interaction with `local_cache!()`. Namely, we have:

```rust
#[crate::async_trait]
impl<'r> FromData<'r> for Capped<&'r str> {
    type Error = std::io::Error;

    async fn from_data(req: &'r Request<'_>, data: Data<'r>) -> Outcome<'r, Self> {
        let capped = try_outcome!(<Capped<String>>::from_data(req, data).await);
        let string = capped.map(|s| local_cache!(req, s).as_str());
        Success(string)
    }
}
```

In this bug, the above implementation is called _twice_, once for each `&'r str` field. The field's `Data` is read and then stored into local cache. This way, the string can be retrieved with an `'r` lifetime. Local-cache is type-based, so at-most one value of a given type can be stored in the cache per request. The `local_cache!()` macro exists to create a locally anonymous type to prevent type conflicts, but that type is created once at compile-time per use. As a result, in the second invocation of this `from_data`, instead of storing a new string in local cache, we simply retrieve the existing string.

Thus means that a similar bug exists for other types such as `&'r RawStr` and in other contexts. Effectively all instances of calls to `local_cache!()` which produce a reference intended to be unique per invocation are incorrect.

I'm working on an extension to local cache to resolve this kind of issue. Once implemented, the extension can be applied to this method, resolve this issue. I'll also audit the entire codebase for other calls to `local_cache!()` which may be incorrect.
