### ISSUE TITLE
Derive `Eq` on `ContentType`

### ISSUE THREAD

**Issue by Jlobblet** [SergioBenitez/Rocket#2132]
**Existing Functionality**

`ContentType` currently derives `PartialEq` but not `Eq`. This is problematic to deal with when many `ContentType`s have to be ingested and used in some way. For example:

```rs
if ContentType::Binary == content_type {
    "bin"
} else if ContentType::HTML == content_type {
    "html"
} else if ContentType::Plain == content_type {
    "txt"
} else if ContentType::JSON == content_type {
    "json"
} // etc
```

What would be nicer is to be able to match:
```rs
match content_type {
    ContentType::Binary => "bin",
    ContentType::HTML => "html",
    ContentType::Plain => "txt",
    ContentType::JSON => "json",
}
```

**Suggested Changes**

Deriving `Eq` would allow using `ContentType`s  in a `match` expression.

**Alternatives Considered**

A method such as `ContentType::to_extension` would also work for the example outlined here.

**Additional Context**

[`Eq` requires the equality comparison to be an equivalence relation.](https://doc.rust-lang.org/std/cmp/trait.Eq.html) Since `PartialEq` is derived rather than implemented manually, `ContentType` should satisfy these requirements.

**Comment by kennethallen** [comment]
I think `Eq` is not derived on `ContentType` because it is not derived on the inner `MediaType`, for which the rationale is [here](https://api.rocket.rs/master/rocket/http/struct.MediaType.html#comparison-and-hashing).

I think the current implementation is incorrect--`PartialEq` should be used when there are could be values for which `a != a`, but that's not possible with the [implementation of `PartialEq`](https://github.com/SergioBenitez/Rocket/blob/efce2bc958d25065584ce01982ff4f1dd9c84750/core/http/src/header/media_type.rs#L568). I think the same code would fulfill the `Eq` contract fully.
