### ISSUE TITLE
Allow for disabling of HEAD requests and method reinterpretation. 

### ISSUE THREAD

**Issue by Directory** [SergioBenitez/Rocket#2184]
no need for a template
the [guide](https://rocket.rs/v0.5-rc/guide/requests/#head-requests) describes how rocket automatically handles HEAD requests and method reinterpretations for forms. Rocket shouldn't assume that this is wanted behavior by the developer. Please consider in a future major version to allow for disabling of this (and anything similar rocket may automatically do). Particularly for head requests, some endpoints could be api's that do a lot of heavy backend io/proccesing to produce a body of data, only for that to of been for nothing when the body is stripped. i know you can make a manual head endpoint to override this functionality, but 99 times out of 100 nobody's application/client actually uses HEAD's. so you would end up making a HEAD handler for every endpoint which is tedious boilerplate. (maybe u can have a single dynamic path endpoint that catches all but you get the point). I believe functionality that the client does not utilize but an attacker can should not be exposed.

As for how to disable it, im not sure. either through config variables or in the rocket builder. but that would add bloat to both.

**Comment by SergioBenitez** [comment]
Per the HTTP spec, HEAD request responses cannot have bodies, so Rocket _not_ stripping the body would mean that it directly violates the HTTP standard. I cannot foresee Rocket enabling a feature that directly contradicts standardized correctness. What's more, the server is always at the mercy of the client: the server can't care whether the client sends a GET or HEAD request because the client is free to choose. Also note that any computation done by a GET handler may be required to produce the correct HEAD response anyway, so viewing the computation time as "wasted" is disingenuous. You should also understand that Rocket strips the body of data without the data needing to be produced (only the stream need exist), so in a well written Rocket application, it is rarely the case that work to produce the body of data is wasted. And in the rare occasion that there are important optimizations to be made and clients can be expected to perform HEAD/GET requests fairly for some reason, then Rocket allows you to write that optimization. 

Form reinterpretation is necessary to allow the submission of HTTP requests from a browser context with verbs other than GET and POST. There is no security, usability, or performance penalty for this feature, and disabling the feature makes what this feature enables impossible, so this too will likely stick around. Furthermore, this is opt-in behavior, so if a developer disagrees then they don't need to use it, and they lose nothing from having it exist in general.

I appreciate the concerns, however I do not believe that they are well founded. As such, I am closing this issue.
