### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by italomaia** [SergioBenitez/Rocket#2247]
**Is your feature request motivated by a concrete problem? Please describe.**

One of the most interesting aspects of the flask framework is the possibility of attaching blueprints to your project, where those blueprints are self contained apps that add functionality to your flask project, like an admin interface or an wiki. It would be nice if rocket had something similar. You create a crate and just "attach" it to rocket, where the crate knows how to "exist" within the rocket ecosystem. 

**Why this feature can't or shouldn't live outside of Rocket**

Seems like rocket has a very tight scope (which does not mean it is small) so being able to add "modules" to the "rocket"would for certain have some appeal. 

**Ideal Solution**

During rocket initialization, if we could just attach some crates to paths, that would be very helpful and allow for scalable development (less copy-paste).

**Alternatives Considered**

Not really.

**Additional Context**

Flask and django have very good examples of those.

**Comment by the10thWiz** [comment]
This is already possible in the current version of Rocket. A crate intending to add support for mounting a set of routes can simply expose a function that returns `Vec<Routes>`, and it can generate the vector routes using the `routes!` macro.

```rust
fn get_routes() -> Vec<Route> {
   routes![route_1, route_2]
}
```

On ignite fairings can also add managed state, and more or less anything else, since they are just provided the raw `Rocket<Build>`. The one thing they can't do is interact with other fairings and previously managed state. I'm thinking about how to implement this, but your use-case almost certainly doesn't require it.

**Comment by SergioBenitez** [comment]
> A crate intending to add support for mounting a set of routes can simply expose a function that returns `Vec<Routes>`, and it can generate the vector routes using the `routes!` macro.

In fact, any `Into<Vec<Route>>` type works. This is why you can do the following, for example:


```rust
rocket.mount(""/foo", FileServer::from("..."))


As @the10thWiz notes, I think this is already possible in Rocket with the combination of fairings and `Into<Vec<Route>>` working as above. Fairings even use the `attach` verb already! #394 might complete this support, however.
