### ISSUE TITLE
Implement futures::stream::Stream on TempFile

### ISSUE THREAD

**Issue by frogtd** [SergioBenitez/Rocket#2296]
**Is your feature request motivated by a concrete problem? Please describe.**
When you receive a TempFile, you can do almost nothing with it. Very often you do actually want to read the file you've received and sent it somewhere else, but the current API forces you to persist it to somewhere if you want to read it. 

**Why this feature can't or shouldn't live outside of Rocket**
Because TempFile is a type owned by rocket, you can't implement Stream on it without being rocket, and you also probably don't want to persist the file to then read it again, which you should do unless you want to rely on the #[doc(hidden)] elements of the enum. 

**Ideal Solution**
Implement Stream on TempFile so people can read it and stream it places to their heart's content.

**Alternatives Considered**
You could have an async method that returns a Vec<u8> of the file's contents, but this forces the contents of the entire file to go into memory.
You could also add another type like `Buffer` that just holds the entire file in memory.

**Additional Context**
This helps #2148 and doesn't require another type for being a buffer, and doesn't buffer the entire file in memory.

**Comment by chinoto** [comment]
I believe your intention is to read the file as it's being uploaded so that it doesn't need to be stored in memory or on disk, but I don't think that's possible in Rocket because that would mean other parts of the multipart/form-data that come after the file can't be processed.
What you could do instead is make the post body be the file verbatim, rather than a multipart/form-data containing the file, then you can read the file off the network via the AsyncRead trait on DataStream. If there is any other data you need, you'll have to put it in the route.
https://api.rocket.rs/v0.5-rc/rocket/data/struct.DataStream.html
```rust
use rocket::data::{Data, DataStream, ToByteUnit};
use rocket::response::stream::ReaderStream;
#[post("/echo_body", data = "<body>")]
fn echo_body(body: Data<'_>) -> ReaderStream![DataStream] {
    let reader: DataStream = body.open(2.mebibytes());
    ReaderStream::one(reader)
}
```

**Comment by SergioBenitez** [comment]
> When you receive a TempFile, you can do almost nothing with it. Very often you do actually want to read the file you've received and sent it somewhere else, but the current API forces you to persist it to somewhere if you want to read it.

This is by design. The idea is to demotivate exactly this and instead advocate for custom `FromFormField` implementations that directly stream the data to their final source. In any case, this has been requested quite a bit, so I've added a `TempFile::open()` method that's about to land.
