### ISSUE TITLE
duplicate url params will be ignored even if they are equal

### ISSUE THREAD

**Issue by LuckyTurtleDev** [SergioBenitez/Rocket#2329]
**Description**

If the same parameter is passed multiple times to the url it will be ignored even if they have the same value.

**To Reproduce**
open https://stickerpicker.luckyturtle.dev/?theme=dark&theme=dark and https://stickerpicker.luckyturtle.dev/?theme=dark
main.rs: https://github.com/LuckyTurtleDev/mstickerpicker/blob/v0.1.0/src/main.rs
```rust
#[get("/?<theme>&<user>")]
async fn index(theme: Option<Theme>, user: Option<&str>) -> Result<Template, Status> {
	let style: Style = theme.unwrap_or_default().into();
	...
}
```
**Expected Behavior**
using always the first/last value
or ignoring only  **if the they are note equal**

**Environment:**

 - OS Distribution and Kernel: docker alpine:latest ghcr.io/luckyturtledev/mstickerpicker:v0.1.0 , kernel: 5.10.0-17-amd64
 - Rocket Version: 0.5.0-rc.2

**Additional Context**
Because of client limitations I can not remove only one `theme` parameter of the url.

**Comment by LuckyTurtleDev** [comment]
I notify that you can also use a `Vec` instead of an `Option`:
```rust
#[get("/?<theme>&<user>")]
async fn index(theme: Vec<Theme>, user: Option<&str>) -> Result<Template, Status> {
	let style: Style = theme.into_iter().next().unwrap_or_default().into();
	...
}
```
This does fix the issue.

**Comment by SergioBenitez** [comment]
This isn't a bug, but it may be a surprising consequence of the [strict/lenient form parsing dichotomy](https://rocket.rs/v0.5-rc/guide/requests/#parsing-strategy) implemented by Rocket.

`Option<T>` parses as `None` if `T` fails to parse. What's happening here is that [`Option<T>` always tries to parse `T` strictly](https://api.rocket.rs/v0.5-rc/rocket/form/trait.FromForm.html#provided-implementations) unless `T` overrides the parsing strategy. So if `T` is parsed strictly, when does `T` fail to parse? The docs answer this as:

> A strict parse errors when there are missing or extra fields [...]

In your example, `Theme`, when parsed strictly, clearly only expects one field. Thus in your example, it'll fail to parse due to extra fields; thus `Option<Theme>` parses as `None`. It doesn't  simply keep the first field: this is considered ambiguous. It also doesn't try to use a default because an option of `Some` when there are _no_ fields can be surprising.

So what to do? Effectively, it seems you want `Theme` to parse leniently. If `Theme` would parse leniently, then extra fields would cease to be an issue. You can either 1) ensure that the `FromForm` implementation for `Theme` doesn't error when more than one field is passed in, or 2) override the parsing strategy for the inner `Theme` in `Option<Theme>` by asking for an `Option<Lenient<Theme>>` instead:

```rust
use rocket::form::Lenient;

#[get("/?<theme>&<user>")]
async fn index(
    theme: Option<Lenient<Theme>>,
    user: Option<&str>
) -> Result<Template, Status> {
    let style: Style = theme.unwrap_or_default().into();
    ...
}
```
