### ISSUE TITLE
Feature request: support non-responding on routes

### ISSUE THREAD

**Issue by Alvenix** [SergioBenitez/Rocket#2367]
**Is your feature request motivated by a concrete problem? Please describe.**

I am running a rocket server and I want the server to not reply in certain routes or catchers.  Mainly to avoid detection for http scanners.

I don't think the feature is possible without modifying Rocket but it may not be worth it.

**Comment by the10thWiz** [comment]
This is not possible without modifying Rocket, since Rocket puts in quite a bit of effort to ensure a response is sent. In theory, something similar could be achieved by simply blocking the request handler until the client gave up, but this probably isn't ideal. Obviously, blocking is bad in async, but something like `std::future::pending().await` avoids blocking the runtime while preventing the handler from returning. However, the much larger issue is the client overhead, between an open connection and the cryptographic state associated with a TLS connection (if enabled). A much better solution (if this is a desired feature) is to modify Rocket to drop the connection in some specific case. Perhaps some kind of special Responder, or a Fairing?

However, I'm not convinced this is a worthwhile feature. I'm curious why you want to avoid detection from http scanners. Something simpler, such as running Rocket on a non-standard port should easily confuse automated systems.

**Comment by Alvenix** [comment]
> This is not possible without modifying Rocket, since Rocket puts in quite a bit of effort to ensure a response is sent. In theory, something similar could be achieved by simply blocking the request handler until the client gave up, but this probably isn't ideal. Obviously, blocking is bad in async, but something like `std::future::pending().await` avoids blocking the runtime while preventing the handler from returning. However, the much larger issue is the client overhead, between an open connection and the cryptographic state associated with a TLS connection (if enabled). A much better solution (if this is a desired feature) is to modify Rocket to drop the connection in some specific case. Perhaps some kind of special Responder, or a Fairing?
> 
> However, I'm not convinced this is a worthwhile feature. I'm curious why you want to avoid detection from http scanners. Something simpler, such as running Rocket on a non-standard port should easily confuse automated systems.

I was developing an API server where there is no need for 404 catcher or any manual browsing. So I had to an empty 404 catcher but it feels inelegant replying with empty response.

**Comment by the10thWiz** [comment]
> I was developing an API server where there is no need for 404 catcher or any manual browsing. So I had to an empty 404 catcher but it feels inelegant replying with empty response.

In this case, I would still suggest including a 404 catcher (even if it just returns a static string or something, especially if you aren't the only one interacting with the API. Rocket does provide a default 404 catcher, although it does (by default) send an HTML response.

**Comment by SergioBenitez** [comment]
I'm not really sure what "non-responding" would mean; force close the connection?

This might be something we can support in some way, but it's not obvious to me how, especially when you consider how careful Rocket is to always make an `&Request` refer to a live request.

I don't think the motivation is strong enough to do this for this reason alone, borrowing from @the10thWiz . If there's some general mechanism that would encompass this request and others, I'd be interested in considering it. Until then, I'll close this issue out.
