### ISSUE TITLE
Option<String> field in Form results in Some("")

### ISSUE THREAD

**Issue by Nutomic** [SergioBenitez/Rocket#2372]
**Existing Functionality**

```
#[derive(FromForm)]
pub struct PostForm {
    subject: String,
    message: Option<String>,
}
```

I use the struct above with a normal HTML form and text input. When the form is submitted with message being unset, the message field always ends up as `Some("")` which is really awkward to handle.

**Suggested Changes**

I would expect that Rocket automatically converts values of `Some("")` to `None`.

**Alternatives Considered**

The alternative is to check each field with an if statement to see if its empty or not. This gets very verbose. 

For now I have written my own helper function to handle the conversion, but this shouldnt be necessary.

```
pub fn empty_to_opt(value: String) -> Option<String> {
    if value == "" {
        None
    } else {
        Some(value)
    }
}
```

**Comment by SergioBenitez** [comment]
> When the form is submitted with message being unset

What do you mean by this? Which form is being submitted, exactly? Ideally you would supply a failing test (using Rocket's test facilities) that you expect to pass.

**Comment by Nutomic** [comment]
Basically any HTML form with a text input, where the input field only contains an empty string. Here is a test case: https://github.com/Nutomic/Rocket/commit/ab3a5740b13da947375d55e2449ce4961b0dfaa6

By the way, a similar problem seems to happen with `Option<TempFile<'r>>` in form, using HTML `<form enctype="multipart/form-data">` and `<input type="file">`. If no file is selected, this sometimes results in `Some(File)` where File.len = 0 and FileName = "". 

By the way Im using Firefox 105 as browser.

**Comment by SergioBenitez** [comment]
The issue is that the field is indeed present. If you simply had `message: String` and sent a form with `message=`, would you expect form validation to fail? That would mean treating the empty string as not a string, which is strictly incorrect. Building on this, if we say that `message=` should be a valid `String`, then it should also be a `Some(String)`.

I think what you want is to validate the string as non-empty. Here's one way to do that:

```rust
#[derive(FromForm)]
pub struct PostForm {
    subject: String,
    #[field(validate = len(1..))]
    message: String,
}
```

You could also define a custom `NonEmptyString` to reuse this idea over and over:

```rust
#[derive(FromForm)]
#[field(validate = len(1..))]
struct NonEmptyString(String);

#[derive(FromForm)]
pub struct PostForm {
    subject: String,
    message: NonEmptyString,
}
```

These are both significantly better options than the `if` approach.
