### ISSUE TITLE
`url` is not passed to rusqlite anymore

### ISSUE THREAD

**Issue by rikhuijzer** [SergioBenitez/Rocket#2439]
The SQLite database settings are passed to rusqlite via 
```toml
[default.databases.rusqlite]
url = "file:rusqlite?mode=memory&cache=shared"
```
in `Rocket.toml` according to the examples.

However, it looks like the `url` is not used by rusqlite anymore since https://github.com/rusqlite/rusqlite/pull/1248. Specifically, according to the tests in that PR, `Connection::open("")` now has the same effect as `Connection::open("file:dummy.db?mode=memory&cache=shared)`. In other words, the `url` is ignored:

```rust
    #[test]
    fn test_path() -> Result<()> {
        let tmp = tempfile::tempdir().unwrap();
        let db = Connection::open("")?;
        assert_eq!(Some(""), db.path());
        let db = Connection::open_in_memory()?;
        assert_eq!(Some(""), db.path());
        let db = Connection::open("file:dummy.db?mode=memory&cache=shared")?;
        assert_eq!(Some(""), db.path());
        let path = tmp.path().join("file.db");
        let db = Connection::open(path)?;
        assert!(db.path().map(|p| p.ends_with("file.db")).unwrap_or(false));
        Ok(())
    }
```

**Comment by rikhuijzer** [comment]
I'm actually running rusqlite 0.25.4 which was released way before https://github.com/rusqlite/rusqlite/pull/1248 and for me `url = "file:/some/path/rusqlite?mode=memory&cache=shared"` has no effect on the file location while `/some/path/rusqlite` has. Probably best then to change the example.

**Comment by SergioBenitez** [comment]
I think there's been a misunderstanding about the rusqlite PR in question. The PR simply changes how the database `path` is stored and retrieved in/from a given a `Connection` type. It does not change the semantic meaning or ensuing effect of the URL.

Previously, the database `path` was stored directly, based on the configured URL, and thus could be faithfully returned when requested. Although in-memory databases don't have a file path (since there's no file), SQLite allows configuring in-memory database URLs with a file path to allow distinguishing between two in-memory databases in a single
process - before that PR, rusqlite would return said distinct path as it stored it directly.

To save memory, the PR stops storing the path in the `Connection` struct and instead hinges on querying SQLite for the filename associated with a connection. As we've said, for in-memory databases, there is no associated file, and so SQLite returns null when the filename is requested for such a connection, which rusqlite transforms into `Some("")`. As a result of this change, it is no longer possible to determine via `Connection::path()` if two in-memory database connections are configured for distinct in-memory databases as all connections for in-memory databases will have a `Some("")` return value from `path()`.

The net effect is a change in the fidelity of the `path()` method, not in how the url is used.
