### ISSUE TITLE
Async, tracked  local `Client` docs outdated on `Send` capability?

### ISSUE THREAD

**Issue by nlydv** [SergioBenitez/Rocket#2444]
Hi there, I’m currently looking into Rocket’s `local` module and there *appears* to be some divergence with the documented guidance regarding `Client` and its async cookie tracking functionality.

Specifically:

https://github.com/SergioBenitez/Rocket/blob/162fafa0f1b5d9045bf342356671859f0f21c4cc/core/lib/src/local/asynchronous/client.rs#L15-L30

When looking into the source code for further information though, I saw that the tracked `CookieJar` was protected by a parking_lot `RwLock`, which shouldn’t (in and of itself) raise multi-threaded synchronization concerns.

Indeed, after rummaging through the issues/PRs it looks like commit https://github.com/SergioBenitez/Rocket/commit/64ba2056ef3678152646483c28a20231ad7ae98d implemented the `RwLock` as a fix to the non-`Send` behavior brought up in issue #814.

So I just wanted to confirm whether the documented warnings about multi-threaded `Client` tracking really are just outdated. Assuming that is the case, it’d be good to update those docs with current information.

If there are other reasons that make async cookie tracking non-deterministic that I’m not aware of however, I’d be interested in learning more about why that may be.

Thanks in advance!

**Comment by SergioBenitez** [comment]
>
> Indeed, after rummaging through the issues/PRs it looks like commit [64ba205](https://github.com/SergioBenitez/Rocket/commit/64ba2056ef3678152646483c28a20231ad7ae98d) implemented the `RwLock` as a fix to the non-`Send` behavior brought up in issue #814.

The main effect of that PR is to make the client `Sync`, not `Send`. Both clients are `Send`, but only the `async` client is `Sync`.

> When looking into the source code for further information though, I saw that the tracked `CookieJar` was protected by a parking_lot `RwLock`, which shouldn’t (in and of itself) raise multi-threaded synchronization concerns.
> 
> So I just wanted to confirm whether the documented warnings about multi-threaded `Client` tracking really are just outdated. Assuming that is the case, it’d be good to update those docs with current information.

The concerns aren't safety related. Rust's type-system would prohibit that (or we would otherwise have a glaring safety issue brought on by `unsafe`). That is, the concerns we're alluding to aren't safety issues (data races) but logic issues (race conditions). In particular, using one `async` `Client` from many threads at once means, each dispatching requests that set cookies, can result in non-deterministically set cookie values.

For example, consider the pseudocode:

```rust
#[get("?<cookie>")]
fn set_cookie(cookie: &str, jar: &CookieJar) {
    jar.set("cookie", cookie);
}

let client: asynchronous::Client;
let t1 = task::spawn(client.get("/?cookie=1"));
let t2 = task::spawn(client.get("/?cookie=2"));
join(t1, t2).await;
```

What is the value of `client.cookies().get("cookie")` after execution? Because the value depends on the order of execution of `t1` and `t2`, the value is non-deterministic. It is guaranteed to be either `1` (if `t1` executes after `t2`) or `2` (if `t2` executes after `t1`), but it is not guaranteed to always be one or the other.

I hope this makes sense and clarifies the concern.

**Comment by nlydv** [comment]
Right on, that makes sense. Thanks for clarifying my misinterpretation!
