### ISSUE TITLE
`Status` cannot be used as a header in `#[derive(Responder)]`

### ISSUE THREAD

**Issue by ChayimFriedman2** [SergioBenitez/Rocket#2484]
**Description**

[The docs about `#[derive(Responder)]` state that](https://rocket.rs/v0.5-rc/guide/responses/#custom-responders):

> Because `ContentType` and `Status` are themselves headers, you can also dynamically set the content-type and status by simply including fields of these types.

**To Reproduce**

```rust
#[derive(rocket::Responder)]
struct ServerError {
    inner: String,
    status: rocket::http::Status,
}
```

**Expected Behavior**

This should compile, and set the status code with `status`, but this does not compile:
```
error[E0277]: the trait bound `rocket::http::Header<'_>: std::convert::From<rocket::http::Status>` is not satisfied
   --> src/main.rs:9:5
    |
9   |     status: rocket::http::Status,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<rocket::http::Status>` is not implemented for `rocket::http::Header<'_>`
    |
    = help: the following other types implement trait `std::convert::From<T>`:
              <rocket::http::Header<'static> as std::convert::From<&'a Cookie<'c>>>
              <rocket::http::Header<'static> as std::convert::From<AcceptCharset>>
              <rocket::http::Header<'static> as std::convert::From<AcceptEncoding>>
              <rocket::http::Header<'static> as std::convert::From<AcceptLanguage>>
              <rocket::http::Header<'static> as std::convert::From<AcceptRanges>>
              <rocket::http::Header<'static> as std::convert::From<AccessControlAllowCredentials>>
              <rocket::http::Header<'static> as std::convert::From<AccessControlAllowHeaders>>
              <rocket::http::Header<'static> as std::convert::From<AccessControlAllowMethods>>
            and 39 others
    = note: required for `rocket::http::Status` to implement `Into<rocket::http::Header<'_>>`
note: required by a bound in `rocket::Response::<'r>::set_header`
   --> /home/explorer/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.11/src/response/response.rs:766:34
    |
766 |     pub fn set_header<'h: 'r, H: Into<Header<'h>>>(&mut self, header: H) -> bool {
    |                                  ^^^^^^^^^^^^^^^^ required by this bound in `Response::<'r>::set_header`
```

**Additional Context**

First reported on StackOverflow: https://stackoverflow.com/q/75570877/7884305.

**Comment by freelon** [comment]
I think this is more about a mistake in the documentation: `Status` doesn't implement `Header`, but only `Responder`. Which is correct from an HTTP point of view, since the response code/status is not a header: 

> HTTP headers consists of its case-insensitive name followed by a colon (:), then by its value. ([source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers))

So if you do 

    #[derive(rocket::Responder)]
    struct ServerError {
        status: Status,
    }
it will compile but `Status` doesn't have a body, which you wanted.

---

To maybe help solving your practical problem at hand:

So you could either build your response dynamically with `Response::build::...`. 
_Or_, as the [stated in the Responder trait docs](https://api.rocket.rs/v0.5-rc/rocket/response/trait.Responder.html#implementation-tips) at the 3rd point it is advised
> You should avoid varying responses based on the Request value as much as possible
which, in combination with the `enum` example above, I would interpret as "make a type for each kind of answer". Since your type here is `ServerError` it would indeed by weird if one could return a `ServerError` response with `Status = 200` or something like that. So if you want to return different server errors, you could create an enum with all the cases that you actually want:

    #[derive(rocket::Responder)]
    enum ServerError {
        #[response(status = 500)]
        InternalServerError(String),
        #[response(status = 503)]
        ServiceUnavailable(String, RetryAfter),
    }
    
    struct RetryAfter(u32);
    
    impl From<RetryAfter> for Header<'static> {
        #[inline(always)]
        fn from(RetryAfter(retry_after): RetryAfter) -> Self {
            Header::new("Retry-After", retry_after.to_string())
        }
    }

**Comment by SergioBenitez** [comment]
Yes, this is indeed a bug in the docs! `Status` is not a header. If you know the status apriori, you should do exactly as @freelon proposed. If the status is determined dynamically, you can use `(Status, R)` as a response, where `R` is any `Responder`. I'll fix this in the docs shortly!
