### ISSUE TITLE
Easy question, how to return different type of response

### ISSUE THREAD

**Issue by sbwtw** [SergioBenitez/Rocket#253]
EXAMPLE:
```
#[get("/<id>")]
fn user(id: isize) -> ??? { 
    if id < 0 {
        // invalid
        return Redirect::to(...);
    } else {
        return Template
    }
}
```

I tried Outcome in ??? but get some errors.

**Comment by SergioBenitez** [comment]
Please see the [response section of the guide](https://rocket.rs/guide/responses/). This has answers to your question and much more.

**Comment by sbwtw** [comment]
@SergioBenitez I see the tutorial, I means how to return a Template in some case, and return Redirect in other.

should i write a response wrapper contains Redirect and Template, and impl the Responder trait?

**Comment by sbwtw** [comment]
I got the answer. just return `Result<Response<'static>, Status>`

**Comment by SergioBenitez** [comment]
You should be returning `Result<Template, Redirect>` in your example. You should very, very rarely return a `Response` directly.

**Comment by sbwtw** [comment]
but i think sometimes need two different successful Response, like this:
```
if xxx {
    return Redirect; // success and do redirect.
} else if xxx {
    return Template; // success and render a template to display.
} else {
    return Err; // fail
}
```

**Comment by SergioBenitez** [comment]
@sbwtw That would require something like an `Either` type. Then you could return a `Result<Either<Redirect, Template>, Error>`. Unfortunately Rust doesn't have an `Either` type in the standard library, but it's trivial to implement one.

**Comment by sbwtw** [comment]
yes, so thats a reason i use `Response` directly. i think if we have a example in tutorial to show this is very helpful.

**Comment by mehcode** [comment]
I use https://crates.io/crates/either @sbwtw; it works nicely. For something more complicated you should probably use your own enum type.

**Comment by sbwtw** [comment]
thanks @mehcode I will try this.

**Comment by Korvox** [comment]
Anyone got an example of using Either in handler return types?

**Comment by raboof** [comment]
@Korvox I've added such a sample as a PR to the docs, let me know if you have any comments or an idea for a more representative example!

**Comment by LorenzV** [comment]
Hello, i also had this problem and i'm kinda disappointed that people put so little effort in posting decent examples here and in the rocket docs. Anyway, here's my solution, but i only started learning rust yesterday, so sorry if it's bad code.

responses.rs
```rust

use rocket_contrib::Template;
use rocket::response::{Redirect, Responder, Response};
use rocket::request::{Request};
use rocket::http::{Status};

pub struct AnyResponse {
    resType: &'static str,
    template: Option<Template>,
    redirect: Option<Redirect>
}

impl AnyResponse{
    fn getDefault() -> Self {
        AnyResponse{ resType: "", template: None, redirect: None }
    }
    pub fn template (temp: Template) -> Self {
        let mut res = AnyResponse::getDefault();
        res.resType = "template";
        res.template = Some(temp);
        return res
    }
    pub fn redirect (redi: Redirect) -> Self {
        let mut res = AnyResponse::getDefault();
        res.resType = "redirect";
        res.redirect = Some(redi);
        return res
    }
}

impl Responder<'static> for AnyResponse {
    fn respond_to(self, req: &Request) -> Result<Response<'static>, Status> {
        if self.resType == "template" {
            return Some(self.template).respond_to(req)
        }
        return Some(self.redirect).respond_to(req)
    }
}
```

main.rs
```rust
use std::collections::HashMap;
mod responses;

fn empty_hashmap() -> HashMap<String, isize> {
    let map = HashMap::<String, isize>::new();
    return map
}

#[get("/")]
fn index(mut cookies: Cookies) -> responses::AnyResponse {
    let uid = cookies.get_private("user_id");
    if uid == None {
        return responses::AnyResponse::redirect(Redirect::to("/login"))
    }
    return responses::AnyResponse::template(Template::render("app", empty_hashmap()))
}
```

**Comment by Giesch** [comment]
For the benefit of anyone else coming here from google:

It seems like the most ergonomic way to do this in v0.4 is to make an enum for your response or error type, and derive Responder, as documented here:
https://rocket.rs/v0.4/guide/responses/#custom-responders
https://api.rocket.rs/v0.4/rocket_codegen/derive.Responder.html

So you can do something similar to AnyResponse like this:
```rust
use rocket::http::Cookies;
use rocket::response::Redirect;
use rocket_contrib::templates::Template;
use std::collections::HashMap;

#[derive(Debug, Responder)]
pub enum ExampleResponse {
    Template(Template),
    Redirect(Redirect),
}

#[get("/example")]
pub fn example(mut cookies: Cookies) -> ExampleResponse {
    if let Some(user_id) = cookies.get_private("user_id") {
        let ctx: HashMap<...> = HashMap::new();
        // add something to ctx with user id
        return ExampleResponse::Template(Template::render("app", ctx));
    }

    return ExampleResponse::Redirect(Redirect::to("/login"));
}
```

**Comment by mhfowler** [comment]
is this still the easiest way to do this in rocket 0.5 or is there any new syntax to make this easier?

> For the benefit of anyone else coming here from google:
> 
> It seems like the most ergonomic way to do this in v0.4 is to make an enum for your response or error type, and derive Responder, as documented here: https://rocket.rs/v0.4/guide/responses/#custom-responders https://api.rocket.rs/v0.4/rocket_codegen/derive.Responder.html
> 
> So you can do something similar to AnyResponse like this:
> 
> ```rust
> use rocket::http::Cookies;
> use rocket::response::Redirect;
> use rocket_contrib::templates::Template;
> use std::collections::HashMap;
> 
> #[derive(Debug, Responder)]
> pub enum ExampleResponse {
>     Template(Template),
>     Redirect(Redirect),
> }
> 
> #[get("/example")]
> pub fn example(mut cookies: Cookies) -> ExampleResponse {
>     if let Some(user_id) = cookies.get_private("user_id") {
>         let ctx: HashMap<...> = HashMap::new();
>         // add something to ctx with user id
>         return ExampleResponse::Template(Template::render("app", ctx));
>     }
> 
>     return ExampleResponse::Redirect(Redirect::to("/login"));
> }
> ```

**Comment by Foorack** [comment]
> ```rust
> 
> #[derive(Debug, Responder)]
> pub enum ExampleResponse {
>     Template(Template),
>     Redirect(Redirect),
> }
> ```

Just ran into this today, am I missing something fundamental? Deeply disappointed over how there is no `-> AnyResponse` or `-> Response` return type. Forcing everyone to define their own enum for this is unnecessary boilerplate.

**Comment by PorkSausages** [comment]
For anybody trawling through Google trying to figure this out - I don't know if it's the "correct" way to do things, but returning `status::Custom<T>` is the least painful way of handling responses that I can find. 

Example:
```rust 
#[post("/endpoint", data = "<mydata>")]
pub fn endpoint(mydata: Json<MyData>) -> status::Custom<String> {
    match some_validation(&mydata) {
        Ok(_) => status::Custom(Status::Ok, "Everything is OK!",
        Err(e) => status::Custom(Status::BadRequest, "Everything is not OK!",
    }
}

**Comment by joxoby** [comment]
Thanks @PorkSausages, that's perfect.

**Comment by the10thWiz** [comment]
> > ```rust
> > #[derive(Debug, Responder)]
> > pub enum ExampleResponse {
> >     Template(Template),
> >     Redirect(Redirect),
> > }
> > ```
> 
> Just ran into this today, am I missing something fundamental? Deeply disappointed over how there is no `-> AnyResponse` or `-> Response` return type. Forcing everyone to define their own enum for this is unnecessary boilerplate.

I disagree. Forcing people to define their own enums is fine, but I would argue that you are probably not designing your API well if you need to return multiple types like this. An easy solution for status codes is shown above, as well as I believe something like `(Status, impl Responder)` achieves the same behavior. If the data type is actually different, they should likely be different routes anyway. The primary advantage to forcing people to create their own enum types is documentation: the rust code should be pretty easy to turn into the HTTP API documentation.

The redirect option is a little more complicated, and could potentially be added to Rocket itself, i.e. a `RedirectOr<T>` type. This seems like it is more likely than most other use cases, since the data type is only present in one possibility.

If you want to allow the client to request a serialization format (i.e. `?format=json`), you either need to create a route for each data type (which may not be desirable), or maybe we can come up with a better solution. I think this could be explored, but it would likely just come down to creating an enum like this:
```rust
#[derive(Debug, Responder)]
pub enum Serialized<T: Serialize> {
    Json(Json<T>),
    Xml(Xml<T>),
}
```
This could be augmented by adding a `FromParam` implementation for `Serialized<()>`, that selects the appropriate variant from the parameter, and a `map` function to insert whatever the actual return type is. This would lead to code that looks something like:
```rust
#[get("/some/api/route?format=<format>")]
fn some_api_route(format: Serialized<()>) -> Serialized<SomeData> {
    format.map(get_some_data())
}
```
This is only likely worthwhile doing if it is used across the project. I could build up a proper range of definitions for this, but I'm not sure how widely useful it would be.

**Comment by dertuxmalwieder** [comment]
With Rocket 0.5 (and the demise of a generic `Result<Response>` return type), having varying routes has become slightly less easy, it seems.

Use case: Routing to `/file`, but all the contents come from a virtual file system. On each request, a check is made in a database which contains the "files":

* `/index.htm` should return the HTML string with a `text/html` content type from the database.
* `/image.png` should return the binary contents with an `image/png` content type from the database.
* `/thisfiledoesnotexist` should return a *status 404* because the file does not have an entry in the database.

In theory, I could probably build a working response with `response::Builder`, but Rocket 0.5 made `Response` a non-working responder anymore (I guess this does not only confuse *me*, as it literally *is* a builder for a response...), so my routes cannot use it.

The documentation is not really helpful here, as it assumes different routes for different contents. But in my case, every route can have any status code and any contents. Could anyone give me a hint on how to (simply) return a `Builder.finalize()` from a route?

**Comment by SergioBenitez** [comment]
Check out https://rocket.rs/master/guide/faq/#multiple-responses.

**Comment by elibroftw** [comment]
How do you use Either? Look at what google yields:
https://hceris.com/either-types-for-rust/

This person is certainly not talking about `Either<Left, Right` but is just talking about Result. 

How do I return an Either response from an Option?
```rs
return response.unwrap_or(Status::NoContent);
```

**Comment by elibroftw** [comment]
I can't even respond with a serde_json::Value?????
