### ISSUE TITLE
SurrealDB Driver

### ISSUE THREAD

**Issue by VandrerenErik** [SergioBenitez/Rocket#2558]
Just a request to add support for [SurrealDB](https://surrealdb.com/)

**Comment by SergioBenitez** [comment]
What kind of support are you requesting? Nothing prevents you from using SurrealDB in a Rocket application today.

**Comment by VandrerenErik** [comment]
I'm already using SurrealDB in a project with Rocker v5.rc3 without any issues. I was mostly asking for "support" in the documentation in the same way as other libraries:

https://api.rocket.rs/v0.5-rc/rocket_db_pools/index.html#supported-drivers

**Comment by SergioBenitez** [comment]
Got it. The db_pools crate exposes existing connection pools - it doesn't implement them itself. As far as I can tell, SurrealDB does no connection pooling or reuse of its own. The only external [crate that does support pooling connections to SurrealDB](https://lib.rs/crates/bb8-surrealdb) has major limitations that appear to be caused by SurrealDB itself. As such, there certainly not way for us to support it now, and it also sounds like there are architectural limitations in SurrealDB itself that make supporting it all unlikely.

If you can point in an opposing direction, then perhaps we can move this forward. Otherwise I would advocate for closing this issue until it becomes possible or ask that you implement support yourself which just requires an implantations of the [Pool](https://api.rocket.rs/v0.5-rc/rocket_db_pools/trait.Pool.html) trait. See also #2544 for a complete example.

**Comment by VandrerenErik** [comment]
I see, thanks for your answer.
