### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by fenhl** [SergioBenitez/Rocket#2612]
**Description**

Tests on the master branch fail with:

> panicked at 'failed to reload modified template in 1.5s', [contrib/dyn_templates/tests/templates.rs:388:9](https://github.com/SergioBenitez/Rocket/blob/26a3f00f82b6ddec2bbdb3ecb0c29d6ff0da7472/contrib/dyn_templates/tests/templates.rs#L388)

**To Reproduce**

```sh
bash scripts/test.sh
```

But reproducing this may be difficult, see the “Additional Context” section.

**Expected Behavior**

Tests should be passing as they do in CI.

**Environment:**

 - OS Distribution and Kernel: Windows 11 Pro version 22H2, build 22621.2283
 - Rocket Version: master @ 26a3f00f82b6ddec2bbdb3ecb0c29d6ff0da7472

**Additional Context**

Given that the panic message occurs after a thread sleep timeout, this looks like a race condition to me. This may make it difficult to reproduce, e.g. the test seems to be passing in GitHub Actions.

**Comment by SergioBenitez** [comment]
I don't think there's a race condition here, at least not one we're not accounting for already. More likely, there's an OS issue at play, since we don't test on Windows 11.

Does the test fail consistently for you? If so, can you run just that test (`cargo test template_reload` inside the `dyn_templates` directory) and post the complete output?
