### ISSUE TITLE
Serve static files with query parameters

### ISSUE THREAD

**Issue by misaelnieto** [SergioBenitez/Rocket#293]
Hi
I implemented the static files route based on the guide and the examples.
```
#[get("/static/<file..>")]
fn static_files(file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/").join(file)).ok()
}
```
It worked very well until some scss code requested a font with a query parameter:
`http://localhost:8000/static/fonts/thefont.woff?v=0.1`

Rocket returned 404. Initially I thought that `FileBuff` was trying to open the file `thefont.woff?v=0.1`, but to my surprise the error is because the route doesn't match because of the query parameters.

At the end I added another route:
```
#[get("/static/<file..>?<q>")]
fn static_files_q(file: PathBuf, q: &str) -> Option<NamedFile> {
    static_files(file)
}
```
That does the trick, but rustc complains
```
[Running cargo run]
   Compiling pallet_jack v0.1.0 (file:///home/nnieto/Code/pu/palletjack)
warning: unused variable: `q`
  --> src/main.rs:22:34
   |
22 | fn static_files_q(file: PathBuf, q: &str) -> Option<NamedFile> {
   |                                  ^
   |
   = note: #[warn(unused_variables)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 10.6 secs
     Running `target/debug/pallet_jack`
```
**What is the elegant way to serve static files and ignore query ?**

Note: This is similar to issue #239 But I didn't want to hijack the thread.

**Comment by SergioBenitez** [comment]
In Rocket 0.2, there is, unfortunately, no elegant way. You'd have to implement `FromForm` for some `Dummy` structure that throws away the query string and then have two routes: one with and one without the query string. In Rocket 0.3, on the other hand, what you wrote will work as you wanted. Full details for this change can be found in https://github.com/SergioBenitez/Rocket/commit/9160483554ef49586802bab66e112598efd8a509.

Since this is resolved in master, I'm closing this out.
