### ISSUE TITLE
[Feature Request] Add "charset=utf-8" to Content-Type for application/json

### ISSUE THREAD

**Issue by shalugin** [SergioBenitez/Rocket#304]
Adding `charset=utf-8` to response Content-Type will make browsers show the JSON correctly.

see also https://github.com/SergioBenitez/Rocket/issues/111#issuecomment-304679114

**Comment by SergioBenitez** [comment]
According to [RFC #4627](https://tools.ietf.org/html/rfc4627), the [official MIME type](https://tools.ietf.org/html/rfc4627#section-6) for JSON is `application/json` with no parameters. The [default encoding is UTF-8](https://tools.ietf.org/html/rfc4627#section-3). A browser that is not respecting the standard is outside of our control.

**Comment by shalugin** [comment]
I've tested Chrome, FF, Safari. Only FF shows JSON correctly.

**Comment by SergioBenitez** [comment]
It's unfortunate that these browsers are not standard compliant in this area. If you'd like, you can tackle the issue browser-side. Here's the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=438464), for instance. Another workaround is to use a browser plugin that correctly interprets the media type.

Rocket will stick to being standards compliant. We won't implement incorrect workarounds because other software _isn't_ standards compliant; that's a slippery slope we won't go down.
