### ISSUE TITLE
[Feature Request] Suggest javascript examples for MessagePack

### ISSUE THREAD

**Issue by mothsART** [SergioBenitez/Rocket#308]
Hi,

I think that using a web framework need a lot of ajax interactions.
To Intercept and transform correctly MessagePack streams to javascript objets need me some researchs. (scattered doc, Jquery doesn't like binary stream...)

An example like this (need [axios](https://github.com/mzabriskie/axios) and [mesgpack-lite](https://github.com/kawanet/msgpack-lite)) could be a good entry-point :

Javascript code :

```javascript
function r() {
  axios.post(
    '/r', null,
    {
      responseType: 'blob',
      headers: {'Content-Type': 'application/msgpack; charset=utf-8'}
    }
  ).then(function(response) {
    var reader = new FileReader();
    reader.onload = function (e) {
        var pack = msgpack.decode(new Uint8Array(reader.result));
        console.log(pack);
    }
    reader.readAsArrayBuffer(response.data);
  });
}
```
Rust code :

```rust
#[derive(Serialize)]
pub struct MsgPackResponse {
    pub compact: bool,
    pub schema: i32,
    pub text  : String
}

#[post("/", format = "application/msgpack")]
fn r() -> MsgPack<MsgPackResponse> {
    let response = MsgPackResponse {
        compact: true,
        schema :  0,
        text   : "hello msgPack !".to_string()
    };
    MsgPack(response)
}
```

**Comment by shssoichiro** [comment]
As the person who added the MsgPack support into Rocket, I will say the reason I chose not to use Javascript as an example is because Javascript comes with built-in support for encoding and decoding JSON, which makes JSON the obvious choice there. MsgPack requires extra work on that front. MsgPack is a more suitable option, in my opinion, for server-to-server communication where either JSON or MsgPack would require the same amount of effort to implement.

I also think it's outside of the scope of Rocket to give examples of how to implement Javascript code.

**Comment by SergioBenitez** [comment]
Material that combines Rocket with client-side integration would be phenomenal! However, I'm in agreement with @shssoichiro here: Rocket's documentation isn't the right place. Anything like this would need to be external. For this reason, I'm denying this request. But, if anyone feels like writing a guide/tutorial/book on integrating Rocket with a front-end, I'd be more than happy to encourage its spread in any way I can!
