### ISSUE TITLE
Multiple forms on the same page results in BadParse

### ISSUE THREAD

**Issue by MrAsler** [SergioBenitez/Rocket#312]
Good day.

First of all, thanks for writing Rocket. It's a very powerful and easy to web framework.
Now, I think I found a bug, although I'm not sure if this is supposed to happen.

  1. Rocket version: Rocket Version: 0.2.8

  2. Operating system: Windows 7 Service pack 1

  3. A brief description of the bug that includes:
    Having a page with two forms, by writing and posting the second form the response will be a bad parse, as Rocket expects to receive the fields from the first form and it receives the fields of the second. The behavior I expected would be for rocket to attempt to parse the first form, and failed that, attempt to parse the second.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
  https://gist.github.com/MrAsler/1429d3d470b0bda02847c4eea108a4e7
  In this example, there are two forms, the first with two fields and the second with one. Attempting to post the second will result in said BadParse.

  5. Ideas, if any, about what Rocket is doing incorrectly.
  I believe Rocket doesn't see if there are multiple forms on a page, so the moment it fails, it doesn't try to parse another form.

**Comment by SergioBenitez** [comment]
As detailed at the bottom of the [`Form` documentation](https://api.rocket.rs/rocket/request/struct.Form.html) in the `impl FromData for Form` section:

> If the form data cannot be parsed into a T, a Failure with status code UnprocessableEntity is returned. 

In other words, if a form fails to parse in a route, the request won't be forwarded. Instead, the request will be aborted, and the error catcher will be called. To accomplish what you're trying to do, you should either use two routes or create a custom `FromForm` implementation that can return either structure. The latter is similar to what @rbalicki2 was trying to do in #298 and will be made easier once #242 lands.

The reason that we must abort the request if a form fails to parse is because we've consumed the incoming `Data`. Recall that all data is streamed in and out of Rocket; once the incoming stream is consumed, it's gone! We have to consume the stream in a `FromData for Form impl` to see if it parses. If we would allow the consumed stream to be forwarded anyway, the next `data` attribute would find an empty stream, which would be incorrect.

**Comment by MrAsler** [comment]
I see. Thank you for the detailed explanation and for offering a solution!

**Comment by SergioBenitez** [comment]
Certainly! I'm closing this issue out, but I'm happy to offer any additional help on this issue. :)
