### ISSUE TITLE
Accessing Config from Request Guard

### ISSUE THREAD

**Issue by dbettin** [SergioBenitez/Rocket#321]
Is it possible to access the active config from request guards?

**Comment by SergioBenitez** [comment]
No. In `0.3`, _some_ of the configuration information is available to access, but not arbitrary information. This is intentional: config information should be parsed and validated _before_ a Rocket application is launched. The parsed, validated value should be made available through managed state which _can_ be access from a request guard. The [fairings example (in 0.3)](https://github.com/SergioBenitez/Rocket/blob/master/examples/fairings/src/main.rs#L70) does this for some hypothetical `Token` config value.

**Comment by dbettin** [comment]
Excellent. I didn't realize you could access managed state from request guards.  

Is a `0.3` release coming soon?

Thanks!

**Comment by SergioBenitez** [comment]
The release _is_ coming soon! I'd give you a more specific timeframe, but that hasn't proven effective. Instead, I'll just say _very_ soon. :)
