### ISSUE TITLE
Middleware support. Not only via Fairings.

### ISSUE THREAD

**Issue by kokinarido** [SergioBenitez/Rocket#335]
I'm aware of Fairings. 

Does Rocket have **full support for creating custom** middleware? Namely, middleware I wish, of any kind. **Not only** middleware most people might need and which Rockets supports out of the box or by Fairings. 

Note that the question isn't why I need this and what I'm trying to accomplish.

**Comment by SergioBenitez** [comment]
Yes, that's what fairings are: custom, but structured middleware. You can implement any fairing you want.

We use the name "fairings" instead of "middleware" so that folks don't erroneously reach for them when they're the wrong solution.

**Comment by kokinarido** [comment]
Do "fairings" allow the same flexibility as middleware in Iron? Is there anything one can implement with middleware in Iron and can't with Fairings in Rocket?

**Comment by xentec** [comment]
@kokinarido I think this new [guide about Fairings](https://github.com/SergioBenitez/Rocket/blob/master/site/guide/fairings.md) explains it fairly well.

**Comment by kokinarido** [comment]
@xentec @SergioBenitez  It doesn't.

**Comment by SergioBenitez** [comment]
Yes, there are things you can implement with Iron's middleware that you can't with Rocket's fairings. This is by design. Middleware is the only mechanism available in Iron; as such, everything has to be implemented through middleware. Rocket has richer, safer, and more robust mechanisms, so middleware becomes a subpar solution to many problems.  I'll copy the "considerations" section from the guide, which hopefully explains this a bit better:

> Fairings are a large hammer that can easily be abused and misused. If you are considering writing a Fairing implementation, first consider if it is appropriate to do so. While middleware is often the best solution to some problems in other frameworks, it is often a suboptimal solution in Rocket. This is because Rocket provides richer mechanisms such as request guards and data guards that can be used to accomplish the same objective in a cleaner, more composable, and more robust manner.
>
> As a general rule of thumb, only globally applicable actions should be implemented via fairings. For instance, you should not use a fairing to implement authentication or authorization (preferring to use a request guard instead) unless the authentication or authorization applies to the entire application. On the other hand, you should use a fairing to record timing and/or usage statistics or to implement global security policies.

It's very unclear to me what you're seeking from this issue, @kokinarido. What are you trying to determine? Rocket is not a middleware-based framework, like Iron. If you're unwilling to rethink how you would structure your application in the absence of a middleware-catch-all design, Rocket may not be the framework for you. On the other hand, if you're open to new ideas that ideally result in your application being safer, more robust, and more correct, I encourage you to read through Rocket's [guides](https://rocket.rs/guide) and [documentation](https://api.rocket.rs).

**Comment by kokinarido** [comment]
@SergioBenitez thanks.
