### ISSUE TITLE
Consider returning HTTP 400 when no route matches

### ISSUE THREAD

**Issue by ssokolow** [SergioBenitez/Rocket#387]
Currently, the front page says as follows:

> If someone visits a path with an <age> that isn’t a u8, Rocket doesn’t blindly call hello. Instead, it tries other matching routes or returns a 404.

From personal experience on my own websites, I can tell you that this is less than ideal for the "no routes match" case, because GoogleBot will sometimes attempt to guess values to uncover new pages and Error 404 prompts it to keep guessing ad nauseum.

(In my case, it was guessing short random strings similar to YouTube video IDs for a field which only accepted single-character title prefixes.)

[According to RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5.1), one of the situations in which Error 400 should be returned is "malformed request syntax" and configuring my request router to return 400 if no routes matched caused GoogleBot to stop guessing new values for that field immediately.

**Comment by SergioBenitez** [comment]
A `400` should only be returned when the message contained invalid syntax, _not_ when it was understood build nothing was available. `404` is indeed the correct response to use here, so I don't see this changing.

Nonetheless, if this causes a problem for you, you can easily implement a `404` catcher than returns a `400`:

```rust
#[error(404)]
fn error() -> status::Custom<&'static str> {
    status::Custom(http::Status::BadRequest, "Sorry, we don't like this request.")
}
```

**Comment by ssokolow** [comment]
Do you have a citation for that? I was never able to find comprehensive enough documentation to feel fully satisfied in my understanding of things.

(My interpretation of the acceptable uses of error 400 was based on examining everything I *could* find on the 400-series errors and the way they seem to fit together as a cohesive system, which suggested that interpreting an invalid route as an error in the higher-level syntax defined by application would be in line with the intent, as a way to express "that request will *never* be satisfiable in its current form".)

**Comment by ssokolow** [comment]
Also, I don't want to reroute all 404 errors to error 400.

404 should continue to be returned for routes that are structurally valid, don't have corresponding records in the data store, but may have them added in the future.

In other words:

* 200: Yes
* 404: Not yet
* 410: Not anymore
* 400: Never was and never will as long as the application remains in its current form.

**Comment by SergioBenitez** [comment]
[RFC7231 S6.5.1](https://tools.ietf.org/html/rfc7231#section-6.5.1) defines `400` while [RFC7231 S6.5.4](https://tools.ietf.org/html/rfc7231#section-6.5.4) defines `404`. The RFC says that the server should return a 400 when a request "...is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)." In the previous RFC, 2616, `400` was defined saying: "The request could not be understood by the server due to malformed [HTTP] syntax," which is a bit more explicit (I inserted "HTTP" there to make it clear that they refer to HTTP syntax, not some application's notion of syntax). Nonetheless, both definitions make it fairly clear that if the request is understood by the server, it doesn't fall in the category of `400`.

**Comment by ssokolow** [comment]
Thank you.
