### ISSUE TITLE
What's the policy on requests that come while all workers are busy with CPU work?

### ISSUE THREAD

**Issue by mkpankov** [SergioBenitez/Rocket#403]
Hello. I'm currently participating in a programming contest developing a highload web server.

Please bear with me, as I use Rocket for the first time and don't have thorough understanding of it, neither I have complete information and results of tests due to lack of time.

I see that my Rocket-backed server with default worker configuration (2*cpu cores) "misses" a lot of requests when under heavy load (think 500+ concurrent users spamming different requests, up to 2000 users). What "missing" looks like is either timeout (benchmarking engine waits for 2 seconds) or just an empty response. To reiterate: no response is received from Rocket in 2 seconds. Benchmarking engine sees no header for 2 seconds and proceeds with other requests.

When repeating same request w/o heavy concurrent load, it succeeds. Increasing number of workers substantially (think ~1000) helps a lot.

So, the concrete question I have at the moment is: what does Rocket do to requests that come in while all workers are busy? Some of my request handlers are actually CPU-bound. I understand this is not the best architecture.

Overall, in case I have 4 cores, 8 workers, of these 8 workers all are busy with number crunching, and another request comes in, what happens? Is it queued somewhere? Does this queue have any bound size?

**Comment by SergioBenitez** [comment]
It's queued, indeed, but not by Rocket. Instead, the TCP connection is queued by your OS. Because Rocket is busy doing useful work, it can't ask the OS if there's a new connection available. As such, the OS will keep it around until it decides to do something else with it.

When you increase the worker count, your OS will multiplex more threads for Rocket, so Rocket has more opportunities to ask for new connections. That being said, the time it takes for the OS to multiplex these threads is taken away from your application, so you may see less work happening, on average, but more connection having _some_ work happening. The 2x CPU default is a value that tends to work pretty well, but the optimal worker count depends on your application and on which values you're trying to optimize for.

**Comment by mkpankov** [comment]
Thank you for explanation.

It's not completely clear however, how many connections can be queued by OS. Is it `listen()` that does that queuing by default? Can you point me to line where rocket does this?

I'm looking for soft/hard limits on this queue and ways to configure it.

**Comment by SergioBenitez** [comment]
Yes, on Unix, `listen()` is generally the call that takes the backlog argument. Rocket doesn't call `listen()` directly; it uses Hyper to do this. Even then, `Hyper` never calls `listen()` directly, since Rust's `std::net` doesn't expose that kind of interface for cross-platform compatibility. But you can look at its source code, in particular [here](https://github.com/rust-lang/rust/blob/dead08cb331343b84564628b139b657f93548320/src/libstd/sys_common/net.rs#L354), to determine that it passes `128` for the backlog parameter. There's no way to configure it, unfortunately. [`net2`](https://github.com/rust-lang-nursery/net2-rs/), an experimental revamp of `std::net`, does in fact allow you to set the backlog, as you can see [here](https://github.com/rust-lang-nursery/net2-rs/blob/master/src/tcp.rs#L67).

**Comment by mkpankov** [comment]
Thank you!
