### ISSUE TITLE
Allow generics in route handlers

### ISSUE THREAD

**Issue by golddranks** [SergioBenitez/Rocket#408]
Currently only free functions can be registered as route handlers. I believe that expanding that to support static methods, also known as associated functions, would bring some nifty benefits. Basically, it would allow defining generic functionality and express that as static methods of a generic type. Rust's type system allows defining and exporting type aliases where the generics are applied, which means that the generic functionality is easy to instantiate and the instances looks like ordinary functions, which would then registered as routes.

Here's an example: let's have a generic type `Crud<I: CrudItem>`, which has a CRUD-like API defined on it as static methods. We can then then instantiate it like

```
pub type member = Crud<Member>;
pub type device = Crud<Device>;
pub type org = Crud<Organization>;
```

and register the routes like:

```
        .mount("/api/items/organizations", routes![
                api::crud::org::get_all,
                api::crud::org::get_one,
                api::crud::org::put_one,
                api::crud::org::post_new,
        ])
```

...etc. This is just one example, but you can hopefully see that allowing to have generics used this way can reduce a lot of boilerplate.

It would be nice if Rust also supported defining aliases for generic free functions with the type parameters applied, which would be a more straightforward way to achieve this, but as far as I know, it doesn't, and I think that while supporting that would be reasonable, it would need an RFC.

I briefly looked at the implementation in the codegen. It seems that while normal functions are `syntax::ast::Items`, methods are `syntax::ast::ImplItems`. It currently emits the code using `quote_item!` macro. I couldn't find any macro that would support emitting `ImplItems`; maybe someone with more experience with compiler plugins could help?

**Comment by golddranks** [comment]
Another, possibly more straightforward thing to do would be to allow type parameters in the `route!` macro.

**Comment by SergioBenitez** [comment]
Seems like a reasonable request, though I'm not sure how this would work.

Before I start, I want to note that if we took an `impl` and wrote the following, things would work as you might like:

```rust
impl<T: Resource + Serialize> Crud<T> {
    fn get_one(id: usize) -> CrudResult<T> {
        T::find(id).into()
    }    
}

#[get("/<id>")]
fn get_one_org(id: usize) -> CrudResult<Org> {
    Crud<Ord>::get_one(id)
}

fn main() {
    rocket::ignite().mount("/api/items/org", routes![get_one_org]).launch()
}
```

and, what's more, we can rather easily write a macro to generate those "wrapper" implementations:

```rust
macro crud_for($T) {
    mod $T {
        #[get("<id>")]
        fn get_one(id: usize) -> CrudResult<$T> {
            Crud<$T>::get_one(id)
        }
    }
}
```

which we'd then use as:

```rust
crud_for!(Org);

fn main() {
    rocket::ignite().mount("/", routes![Org::get_one]);
}
```

Please consider whether this user-side work-around is enough for your use case.

Okay, let's continue. Let's run through a quick but more complete example of how I imagine you'd want this to work:

```rust
struct Crud<T>(T);

impl<T: Resource + Serialize> Crud<T> {
    #[get("/<id>")]
    fn get_one(id: usize) -> CrudResult<T> {
        T::find(id).into()
    }
    
    fn routes() -> Vec<Route> {
        routes![Crud<T>::get_one]
    }
}

struct Org;
impl Resource for Org { .. }

fn main() {
    rocket::ignite().mount("/api/items/org", Crud<Org>::routes()).launch()
}
```

I've left out a few details, but I think this example gives us something to work with. The primary question is: _What code does Rocket generate for the `get_one` function?_

First, note that `T` is a free-variable as far as the `get_one` function declaration is concerned. As a result, when the plugin for the `get` decorator is called, Rocket will see an un-bound `T`. Maybe that's okay, because we can generate some code into the `impl` item where `T` is bound. So what code will we generate? If we follow the path of today, the `impl` above would be translated into something like:

```rust
struct Crud<T>(T);

impl<T: Resource + Serialize> Crud<T> {
    pub static rocket_route_get_one_info: ::rocket::StaticRouteInfo =
        ::rocket::StaticRouteInfo {
            name: "get_one",
            method: Get,
            path: "/<id>",
            handler: Self::rocket_route_get_one,
            format: None,
            rank: None,
        };

    fn rocket_route_get_one<'r>(req: &'r Request, date: Data) -> handler::Outcome<'r> {
        let id = req.param(0).map(usize::from_param)?;
        let responder = Self::get_one(id);
        ::rocket::handler::Outcome::from(req, responder)
    }
    
    fn routes() -> Vec<Route> {
        routes![Route::from(&Crud<T>::rocket_route_get_info)]
    }
}
```

At a first glance, this seems like it'll work as long as we change `static` to `const` for the `StaticRouteInfo` structure. Unfortunately, when we add #263 into the mix, we'll also need to generate a macro for each route. Unless associated macros are added to Rust (which _is_ a possibility, but requires lots of thought and a good RFC), we won't be able to generate that macro, and so we won't be able to implement this functionality, at least not as directly as one might like.

Perhaps there's a work-around here. For instance, if we required an annotation on the `impl` itself, would we be able to generate items _outside_ of the `impl` block and have everything work out? The answer is probably no since then resolving paths to those items wouldn't work as expected in all cases.

So it seems like using a `struct` + `impl` is riddled with problems.

I'm curious if there's a way to resolve these issue with generic, non-`impl` functions. For instance, would it be possible to get something like the following to work as expected?

```rust
#[get("/<id>")]
fn get_one<T: Resource + Serialize>(id: usize) -> CrudResult<T> {
    T::find(id).into()
}

fn main() {
    rocket::ignite().mount("/", routes![get_one<Org>])
}
```

One idea (and I hope you or someone else will think of more), is to transform generic functions into macros like the one I showed at the beginning of this comment. For the short code above, we could generate:

```rust
fn get_one<T: Resource + Serialize>(id: usize) -> CrudResult<T> {
    T::find(id).into()
}

macro rocket_get_one_route($T:ty) {
    #[get("/<id>")]
    fn get_one_T(id: usize) -> CrudResult<T> {
        get_one::<$T>(id)
    }

    pub static get_one_info: ::rocket::StaticRouteInfo =
        ::rocket::StaticRouteInfo {
            name: concat!("get_one<", stringify!($T), ">"),
            method: Get,
            path: "</id>",
            handler: get_one_T,
            format: None,
            rank: None,
        };
}

macro rocket_uri_for_get_one!(..);

fn main() {
    rocket::ignite().mount("/", routes![{
        rocket_get_one_route!(Org);
        &get_one_info
    }])
}
```

I'd be curious to explore this secondary route. It seems promising, powerful, and familiar. The devil's in the details, of course. I'd be happy to mentor anyone who wants to explore this further.

**Comment by SergioBenitez** [comment]
I decided to give the generic function code generation I posted in my previous comment a shot. Turns out it works! Here's the experiment:

```rust
trait Resource: Sized { fn get_one() -> CrudResult<Self>; }
trait Serialize {  }

struct CrudResult<T>(T);
struct Request;
struct Outcome<'a>(&'a str);
struct StaticRouteInfo { handler: fn(&Request) -> Outcome }

struct Org;
impl Serialize for Org {  }
impl Resource for Org { fn get_one() -> CrudResult<Org> { unimplemented!("Org") } }

struct Person;
impl Serialize for Person {  }
impl Resource for Person { fn get_one() -> CrudResult<Person> { unimplemented!("Person") } }

fn get_one<T: Resource + Serialize>(id: usize) -> CrudResult<T> {
    T::get_one()
}

macro_rules! rocket_get_one_route {
    ($T:ty) => {
        fn rocket_route_for_get_one<'r>(req: &'r Request) -> Outcome<'r> {
            let responder = get_one::<$T>(100);
            unimplemented!("rocket_route_for_get_one")
        }

        static get_one_info: StaticRouteInfo = StaticRouteInfo {
            handler: rocket_route_for_get_one
        };
    }
}

fn main() {
    {
        rocket_get_one_route!(Org);
        let x: &'static StaticRouteInfo = &get_one_info;
        (x.handler)(&Request);
    }

    {
        rocket_get_one_route!(Person);
        let x: &'static StaticRouteInfo = &get_one_info;
        (x.handler)(&Request);
    }

    let x: &'static StaticRouteInfo = {
        rocket_get_one_route!(Person);
        &get_one_info
    };
}
```

Unfortunately this can't actually be implemented today. This is because we need to use `decl_macro` to get properly namespaced macros, but `decl_macro` macros don't yet support unhygenic item generation, so we wouldn't be able to refer to items generated by the macro outside of the macro. The other drawback is that aliasing won't work; you'll need to refer to the generic types directly in the route name used in `routes![..]`. That is, you'll always need to do `routes![get_one<Org>]` and so on. This same restriction exists today as well, so it's probably not a big deal.

Once the ability to create unhygenic names in decl macros lands, assuming there is enough demand for something like this, we should consider implementing this! I'd be happy to mentor someone through this at that time. Of course, if there are other implementations that could potentially be implemented today, please feel free to chime in.

**Comment by SergioBenitez** [comment]
I'm closing this as there has been little to no demand for a feature of this nature. Should that not be the case, I'd be happy to reopen.

**Comment by rw** [comment]
@SergioBenitez I think there's a concrete use case for this that's important for "glue" services as well as testing.

Let's say I'm writing an app and I want to create multiple implementations of a backend service, to make sure we can deploy our code in multiple environments.

Here's an example:

```rust
// create a trait that abstracts over a key/value store like redis:
trait KeyValueBackend { ... }

// define structs for each implementation of our k/v operations:
struct RedisConnection { ... }
struct CassandraConnection { ... }

// implement the key/value trait for the backends: 
impl KeyValueBackend for RedisConnection { ... }
impl KeyValueBackend for CassandraConnection { ... }

// define handlers that can work with an KeyValueBackend:
#[get("/get_key/<key>")]
fn get_key<S: KeyValueBackend + Clone + Send + Sync + 'static>(state: &State<S>, key: &[u8]) -> ... { ... }

// launch an application with redis:
fn launch_with_redis() {
    rocket::build().mount("/", routes![get_key]).manage(RedisConnection::new());
}

// launch an application with cassandra:
fn launch_with_cassandra() {
    rocket::build().mount("/", routes![get_key]).manage(CassandraConnection::new());
}
```

Right now, I think I can do this the hard way by implementing Handler myself. Is there a way to get the macro to work with this, instead?

Thank you!

**Comment by SergioBenitez** [comment]
Your example has no reasonable type-safe interpretation. Thus, that example, or any like it, will _never_ be supported. This is fundamental to type systems in general. In your example, it is impossible to answer the question, during dispatch, of: what is the concrete type of `S`?

My example in https://github.com/SergioBenitez/Rocket/issues/408#issuecomment-327653677 illustrates how to write "generic" routes today. My comment in https://github.com/SergioBenitez/Rocket/issues/408#issuecomment-327968568 illustrates an approach to emulating the same in Rocket itself. For your specific example, you might find that either 1) a trait object like `Box<dyn KeyValueBackend>` or 2) an enum with `Redis` and `Cassandra` variants and unifying methods are better alternatives altogether.

**Comment by rw** [comment]
@SergioBenitez Thanks for the quick and thorough response!

I think my misunderstanding stems from where I thought types would be resolved at compile time versus at runtime.

My expectation (coming from `tide`) was that the state would be a type parameter on a Rocket: something like `Rocket<S: State>`. However, after reading some of the code, I see that [`fn manage`](https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/rocket.rs#L392-L402) works by using `std::any::type_name::<T>()` to figure out the type of the state at runtime, and then (I believe) store the state object under that typename.

So, that's a very different model than I was expecting (especially because `fn manage` can panic), but I understand how that may be a more ergonomic interface for some users.

(My view is that it's more ergonomic and typesafe to use type parameters like `Rocket<S: State>`, but as someone attempting to use rocket for the first time, I may not understand the tradeoffs involved.)

**Comment by SergioBenitez** [comment]
> My expectation (coming from `tide`) was that the state would be a type parameter on a Rocket: something like `Rocket<S: State>`.

As as I stated before, this is a fundamental limit of the type system in general, and no Rust library can get around this. For example, Tide allows you to have _one_ state type (Rocket allows you to have any number of managed values). Thus, in your example, with Tide you would either have `RedisConnection` or `CassandraConnection`, but you wouldn't be able to dynamically choose between the two _and_ have the generic route be callable. You can accomplish the same in Rocket via the example in my first comment. The two approaches are isomorphic.

> However, after reading some of the code, I see that [`fn manage`](https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/rocket.rs#L392-L402) works by using `std::any::type_name::<T>()` to figure out the type of the state at runtime, and then (I believe) store the state object under that typename.

The `type_name` is used _only_ to emit a nice error message and for nothing else. There is no "state object" in Rocket, and type names are not unique and therefore cannot be used as lookup keys. The implementation of managed state is somewhat nuanced, but if your curious, you can read the implementation in the `state` crate.

> So, that's a very different model than I was expecting (especially because `fn manage` can panic), but I understand how that may be a more ergonomic interface for some users.
> 
> (My view is that it's more ergonomic and typesafe to use type parameters like `Rocket<S: State>`, but as someone attempting to use rocket for the first time, I may not understand the tradeoffs involved.)

There is an iota of increased type safety obtained by carrying around a type generic representing the state, but only if we don't impose the same constraints the approach in Tide enjoins. If we do, then Rocket's [sentinels](https://api.rocket.rs/v0.5-rc/rocket/trait.Sentinel.html) result in the two approaches being equally type-safe while functionality in Rocket that's impossible in Tide. Among these include:
  * The ability to manage more than one concrete type of value.
  * The ability to manage state unknown to the application, for example, via plug-ins.
  * The ability to dynamically manage values.
  * The ability to inspect managed state by type.
  * Not needing to parameterize the application based on state.
  * Better error messages.

**Comment by audunhalland** [comment]
I'm interested in creating a Rocket example for [entrait](https://github.com/audunhalland/entrait/), an inversion-of-control library. For that to work, I think I would need generic handlers:

```rust
#[get("/foo")]
fn get_foo<F>(state: &State(F)) -> Foo
where F: FetchFoo + Send + Sync + 'static
{
    state.fetch_foo()
}
```

I don't fully understand how this has to work.

> Rocket allows you to have any number of managed values

This enables easy injection of data, but injecting behaviour is harder, since there seems to be no way to have a generic Rocket.
