### ISSUE TITLE
Question: is there something like `filter` for Spring in Rocket?

### ISSUE THREAD

**Issue by samrayleung** [SergioBenitez/Rocket#424]
+. Rust version: nightly-x86_64-unknown-linux-gnu - rustc 1.22.0-nightly (ca94c75c5 2017-09-10)
+. Rocket version: 0.3.2
+. I have posted a text post in [reddit](https://www.reddit.com/r/rust/comments/6s4uv9/question_about_rocket_login_session_management/) and ask for help in IRC, but still could not solve my question Any questions.
+ My question is that: is there somethings like `filter` in Rocket, So I can
  filter request before controller handle it. Say, I have such methods 

  
```
#[get("/admin/post")]
pub fn get_posts(user: User, db: DB) -> Template {
    let result = Post::query_all(db.conn());
    let mut context = HashMap::new();
    context.insert("posts", result);
    Template::render("admin/post", &context)
}

#[post("/admin/post",data="<new_post>")]
pub fn add_post(db: DB, new_post: Json<NewPost>) -> &'static str {
    if NewPost::insert(&new_post.0, db.conn()) {
        "success"
    } else {
        "error"
    }
}

#[get("/admin/new_post")]
pub fn new_post() -> Template {
    let mut context = HashMap::new();
    context.insert("foo", "bar");
    Template::render("admin/form-general", &context)
}

#[get("/admin/<id>")]
pub fn edit_post(id: i32, db: DB) -> Template {
    let result = Post::query_by_id(db.conn(), id);
    let mut context = HashMap::new();
    context.insert("post", result.first());
    Template::render("admin/form-general", &context)
}
#[delete("/admin/post/<id>")]
pub fn delete_post(id: i32, db: DB) -> &'static str {
    if Post::delete_with_id(db.conn(), id) {
        "success"
    } else {
        "error"
    }
}
#[put("/admin/post",data="<update_post>")]
pub fn update_post(update_post: Json<Post>, db: DB) -> &'static str {
    println!("Call update");
    // println!("{:?}", &update_post.0);
    if Post::update_post(db.conn(), &update_post.0) {
        "success"
    } else {
        "error"
    }
}
  
```

If I have a filter, I could check the uri whether it begins with `/admin/`, if so, it means it needs 
an administrator privilege. So the filter could check permission before all controller start to work. This is 
what I always do in Java/Spring, I just wonder is there something similar in Rocket

**Comment by SergioBenitez** [comment]
This is generally what [request guards](https://rocket.rs/guide/requests/#request-guards) are for. You'd have an `Admin` request guard and then use the type in your `/admin` routes:

```rust
#[get("/admin/new_post")]
pub fn new_post(admin: Admin) -> Template {
    let mut context = HashMap::new();
    context.insert("foo", "bar");
    Template::render("admin/form-general", &context)
}

#[get("/admin/<id>")]
pub fn edit_post(admin: Admin id: i32, db: DB) -> Template {
    let result = Post::query_by_id(db.conn(), id);
    let mut context = HashMap::new();
    context.insert("post", result.first());
    Template::render("admin/form-general", &context)
}
```

In your code, it looks like you don't need any kind of proof of an administrator being logged in to perform actions on the database that require an administrator. As a result, you don't have a need for anything like an `Admin` type. This is error-prone; nothing prevents you from calling these methods even if there's no administrator logged in.

To prevent these kinds of issues, you should have your database methods require an `Admin` type so that the type acts as a capability; only when it exists can actions required from an administrator be performed, and by implication through Rocket's requests guards, only when an administrator is logged in can administrative actions occur.

What I've laid out is the _safest_ approach, and it's the one that Rocket advocates for, even if it seems a bit repetitive to mark everything with an `Admin` type. The reason Rocket forces this is because Rocket believes that handler function signatures should include all of the necessary information to handle a request; authorization is one of them.

If you'd like to go with a more unsafe route, take a look at [fairings](https://rocket.rs/guide/fairings/). With the fairing approach, you'd implement a request fairing that checks the URL and rewrites the request so that some fallback route gets called instead.

**Comment by samrayleung** [comment]
Actually, I have checked request guards and `session` example, and now this is my way to solve this question 
```rust
#[derive( Deserialize, Serialize)]
pub struct Login {
    pub username: String,
    pub password: String,
}

#[derive(Debug)]
pub struct User(usize);

impl<'a, 'r> FromRequest<'a, 'r> for User {
    type Error = ();

    fn from_request(request: &'a Request<'r>) -> request::Outcome<User, ()> {
        request
            .cookies()
            .get_private("user_id")
            .and_then(|cookie| cookie.value().parse().ok())
            .map(|id| User(id))
            .or_forward(())
    }
}

#[get("/admin/index")]
pub fn index(user: User) -> Template {
    let mut context = HashMap::new();
    // context.insert("user_id", user.0);
    context.insert("foo", "bar");
    Template::render("admin/index", &context)
}

#[get("/admin")]
pub fn index_redirect(user: User) -> Redirect {
    Redirect::to("/admin/index")
}

```
So I think the `User` type is similar with `Admin` type, but I think as you say so
> Rocket believes that handler function signatures should include all of the necessary information to handle a request; authorization is one of them.
If your request requires a lot of information, you have to set them all in the function signatures, don't you think this will be cumbersome ?

**Comment by SergioBenitez** [comment]
> If your request requires a lot of information, you have to set them all in the function signatures, don't you think this will be cumbersome?

I do not. :)

Sounds like this question has been answered! If so, please feel free to close the issue.

**Comment by samrayleung** [comment]
thanks for your answer, But I am just curious about the philosophy of Rocket, and its trade-off
