### ISSUE TITLE
Question : `#[derive(FromForm)]` requires `#![feature(custom_derive)]`

### ISSUE THREAD

**Issue by StyMaar** [SergioBenitez/Rocket#468]
When attempting to derive the FromForm trait (in rocket 0.3.3), I'm getting this error message from the compiler : 

```
error: `#[derive]` for custom traits is deprecated and will be removed in the future. (see issue #29644)
  --> src/main.rs:34:10
   |
34 | #[derive(FromForm)]
   |          ^^^^^^^^
   |
   = help: add #![feature(custom_derive)] to the crate attributes to enable

```

Since `proc_macro` (macro 1.1) has been stabilized several month ago, I'm surprised I need to enable the legacy `custom_derive` feature.

Is there anything in the `proc_macro` system that prevents using it for the `FromForm` trait ?

**Comment by SergioBenitez** [comment]
Syntax extensions and `proc_macro` have not yet reached feature parity: this will happen by `proc_macros` 2.0. I've already reimplemented the `FromForm` derive using `proc_macros` 1.0. You can see the work in the `syn-derive-form` branch. The main issues with actually switching over to this implementation are 1) lack of proper error messages in `proc_macro` (though this is already solved in nightly `rustc`) and more importantly, 2) doing so would require users to import a crate specifically to use the derive macro since derive macros must reside in independent crates.

**Comment by Celti** [comment]
The latter point (about multiple crates) is not 100% true. A crate (i.e., `rocket`) can re-export custom derives (such as would reside in a theoretical `rocket_derive` crate), so that the end-user only has to have a single `#[macro_use] extern crate rocket;` in their crate to use both Rocket and the custom derives it offers.

You can see an example of this brought up for the `failure` crate in withoutboats/failure#71 and withoutboats/failure#81.

**Comment by SergioBenitez** [comment]
That's fair, @Celti, but the idea is to be able to decouple codegen from the core library as much as possible. Still, it's a fair point, and certainly something to keep in mind.

Looks like this question has been answered. Closing this out.
