### ISSUE TITLE
Expose the SignedJar of http::Cookies

### ISSUE THREAD

**Issue by Korvox** [SergioBenitez/Rocket#471]
Right now `http::Cookies` provides access to the internal `cookie::CookieJar`'s insecure and private jars. There exists a third jar in the lib for a `SignedJar` (signed but not encrypted) that we can expose using the same api style as the current accessors of the `CookieJar`.

In practice you can use `PrivateJar` for anything you would use a `SignedJar` for, but being explicit about private data going in Private and non-private read only data going in Signed makes separation of responsibilities more concise when using a lot of cookies (ex, a private serial user id vs a public random UUID).

If @SergioBenitez  doesn't mind I could easily add these methods and a few tests in the same style as the current ones right quick.

**Comment by SergioBenitez** [comment]
Not including access to signed cookies was a conscious choice made to prevent misuse. It is not uncommon for developers to improperly use signed cookies to, for instance, store private data. It is this misunderstanding about when to use what that Rocket is trying to prevent by providing a single, safe choice. Because we use AEAD via AES-256-GCM, encryption will be very quick, so performance shouldn't be a concern. As such, I'm not in favor of introducing signed cookies to Rocket as I don't see any benefit to doing so.

**Comment by SergioBenitez** [comment]
@Korvox Does this make sense? Happy to reconsider if there's something I'm missing.
