### ISSUE TITLE
Support for Modules/Packages/Blueprints/Engines?

### ISSUE THREAD

**Issue by c410-f3r** [SergioBenitez/Rocket#472]
It is desirable for larger applications to split up code into different pieces and would be nice to have something similar for Rocket. E.g.: Rails does it using [engines](http://guides.rubyonrails.org/engines.html) and Flask with [blueprints](http://flask.pocoo.org/docs/0.12/blueprints/#blueprints).

**Comment by Korvox** [comment]
I would love something like this. I've kind of hacked it my own way by putting a PATH variable in every module and passing my `Rocket` object into all submodules to mount everything in per-module `init` methods, and each PATH is lazy_static'd into the tree path to where the module is using the parents `super::PATH` as a chain. You avoid a lot of code duplication that way - adding a mount tree is just adding a submodule wherever I want the mounts and adding a call to init that takes my Rocket object in my `main()`.

Being able to make a submodule, have its init() method start from nothing and return a `Blueprint` that behaves like a `Rocket` but can be mounted on a real `Rocket` object where its mounts are relative on some mount point in the blueprint add method would be super intuitive.

Only problem is that kind of breaks how a lot of the introspection in things like `uri!` works, because you cannot generate the actual canon uri! if its not known until runtime when all the Blueprints are added to the Rocket instance.

**Comment by SergioBenitez** [comment]
This sounds very similar to #394. Is this a dup?
