### ISSUE TITLE
Using Hashmap with State

### ISSUE THREAD

**Issue by hgrecco** [SergioBenitez/Rocket#478]
In the [guide](https://rocket.rs/guide/state/), an `AtomicUsize` is used inside the state structure. So I guess that this means that `State` is not thread safety, right? Is there any reason why it was designed this way as it seems it that `rw` thread safe access would be the most common case.

In particular, I would like to have a Hashmap.  Would this be the recommended way?

```rust
pub struct InternalState {
    cache: Mutex<HashMap<String, Vec<u32>>>,
}
```

**Comment by hgzimmerman** [comment]
https://api.rocket.rs/rocket/struct.State.html

`State` requires that the type that it is wrapping implement both Send and Sync.

A normal usize does not implement these traits, but an AtomicUsize does. 

A mutex can act as a wrapper around a type T that doesn't implement `Send` and `Sync`, and provide locking functionality that protects the T from synchronous access.

I believe that if you are using a type that wraps a mutex, you need to tell the compiler that your wrapper type is `Send` and `Sync` by implementing those unsafe Traits. They don't require any implementation work on your end, but by using them, you are telling the compiler that it must trust you that you are manually preventing synchronous access to the internals of your type.

It is probably recommended that you try not to keep a large state that you pass on to every function that needs a part of it. instead of that, you may want to declare `pub type InternalCache = Mutex<HashMap<String, u32>>;`.

**Comment by SergioBenitez** [comment]
@hgzimmerman provides valuable insight here. I want to clarify one thing, however:

> I believe that if you are using a type that owns a Mutex, you need to tell the compiler that your wrapper type is Send and Sync by implementing those unsafe traits. They don't require any implementation work on your end, but by using them, you are telling the compiler that it must trust you that you are manually preventing synchronous access to the internals of your type, as well as it being safe to send it across thread boundaries.

As long as you're doing synchronization using existing `Sync` types and no `unsafe`, you never need to unsafely implement `Sync`  (`unsafe impl Sync for T { }`) or `Send` for your types; they're automatically implemented by the compiler. For instance, in:

```rust
struct MyStruct<T: Send> {
    item: Mutex<T>
}
```

`MyStruct` will be `Sync + Send` automatically with no manual effort. In general, `unsafe impl` should be with exceeding rarity.

**Comment by SergioBenitez** [comment]
@hgrecco 
> So I guess that this means that State is not thread safety, right?

Rocket's managed state is _required_ to be thread safe, and Rust and Rocket enforce this, but Rocket doesn't enjoin _how_ thread safety is achieved. You can use exclusion primitives such as `Mutex` or `RwLock`, or you can use entirely custom synchronization schemes. Any value of a type that implements `Sync` is thread-safe. Rocket also requires `Send` so that a value of the given type can be moved between threads safely.

**Comment by SergioBenitez** [comment]
Looks like this has been answered. Closing out.

**Comment by emryx26** [comment]
hello, I tried to use Mutex in state, however rocket doesn't allow create mutable  reference, so how can I write to the Mutex data?
