### ISSUE TITLE
Using Flash in the same request

### ISSUE THREAD

**Issue by TheNeikos** [SergioBenitez/Rocket#512]
## Bug Reports
  1. **The version of Rocket you're using. Ensure it's the latest, if possible.**
 0.3.5
  2. **The operating system (distribution and version) where the issue occurs.**
Arch Linux

  3. **A brief description of the bug that includes:**
When setting a flash message it is only read on the next request when reflected from the request.

  4. **How you uncovered the bug. Short, reproducible tests are especially useful.**
I set a flash message in my handler, and extract in a fairing to feed it to my templates. It only shows when redirecting or on next page load.

The exact timeline:

- Users goes to `GET /login`
- Submits incomplete form to `POST /login`
- This sets a flash message telling them there is an error
- It then directly renders the login form, it shows no flash message
- User then goes to `/` and then the flash shows and gets deleted.  
  
  
**Ideas, if any, about what Rocket is doing incorrectly.**
It should be available to fairings after the handler ran, so that they can use it and stop the cookie from being set.

## General Comments

The logs currently show:
```
    => Flash: setting message: error:Something didn't seem right, please retry in a moment.
    => Flash: attemping to retrieve message.
```
But it doesn't find it.

**Comment by SergioBenitez** [comment]
Can you share the relevant code in your project? Does it effectively look like this?

```rust
fn handler(..) -> Flash<T> { .. }

impl Fairing for MyFairing {
    fn on_response(..) {
        let flash = req.guard::<FlashMessage>()?;
        // we never get here because `?` failed
    }
}
```

If so, then things are working as expected. Flash messages work through cookies. The `Flash` responder sets a cookie through a `Set-Cookie` header instead of the regular `request.cookies()` mechanism, so `FlashMessage` won't find the cookie until the next request. So while this isn't a bug, it's perhaps confusing behavior that we should amend.

There's no reason that `Flash` can't use the `request.cookies()` mechanism. If it did, it would immediately resolve your issue here. One positive nice side-effect of `Flash` not using `request.cookies()` is that it keeps the mechanism by which `Flash` works an implementation detail. The negative side-effect is that it doesn't use the regular cookies API.

I'll think about this one.

**Comment by TheNeikos** [comment]
I have since simplified my code to have the specific piece of code in a `Responder`. This still has the same issue, since yeah it gets set in the cookies.

Rails has the same 'problem' but since their interface is different they are able to work around it with `now`. [Link](http://guides.rubyonrails.org/action_controller_overview.html#the-flash) I am not sure it is something that can be done with the current `Flash`.

On a somewhat related mark, why is `Flash` in the handler return code? Is it because it needs access to the response?

**Comment by TheNeikos** [comment]
That looks like a great solution!

Thanks @SergioBenitez
