### ISSUE TITLE
Support brotli compression of responses

### ISSUE THREAD

**Issue by Martin1887** [SergioBenitez/Rocket#528]
Hello.

I think that brotli support will be great. A fast (though not as fast as original C Brotli) implementation in Rust is available in https://github.com/dropbox/rust-brotli. All modern browsers support Brotli compression, so it could speed up many applications!

This feature request is related to #195.

Maybe it could be implemented with custom responders as it is suggested in #195, but I think that this a feature that can be good for all requests, and therefore wrapping all responses in a custom Brotli responder could be boilerplate in many applications. 

Thanks and regards.

**Comment by SergioBenitez** [comment]
This can be implemented as both a `Responder` and as a `Fairing`, if you want all responses compressed. This can be done entirely outside of Rocket. I don't think something like this belongs in the core library, but perhaps a nice implementation can make its way into `contrib`. Because of this, I'm closing out this issue as declined.

If someone implements this as a `Fairing` and `Responder`, I'm happy to review it for inclusion in `contrib`!
