### ISSUE TITLE
Ability to disable "Rocket has launched" log?

### ISSUE THREAD

**Issue by valeriansaliou** [SergioBenitez/Rocket#553]
Rocket `v0.3.6` currently boots with an error log ie. `🚀  Rocket has launched from http://::1:8080`. There is no way to disable this, even when Rocket is instantiated via `Rocket::custom()` with `log` set to `false`.

This error log is passed to the common project logging facility, which gets printed to console / error log / etc in production environments. This is not an error per-say, but rather an informational message.

I'd like to see this log level lowered a bit, ie. to `info!()`, or at least being able to hide this message.

The reason for this: I used Rocket in 2 OSS projects: [valeriansaliou/vigil](http://github.com/valeriansaliou/vigil) and [valeriansaliou/raider](http://github.com/valeriansaliou/raider). I got a report ([#1](https://github.com/valeriansaliou/vigil/issues/1#issuecomment-360264846)) of an user asking about this weird behavior (thinking it came from a mis-configuration from my code). I share his point of view, this is quite annoying in projects that rely on Rocket and only need important error logs shown as output.

**Comment by SergioBenitez** [comment]
I wholeheartedly agree. The reason we do this now is because we want to always show the launch message (so you know something has happened) _unless_ something specifically disables it. We currently do this by hijacking the "error" log level. It may be possible to instead examine the log `target` and emit the message only when Rocket's logger is used and not when it's overwritten.

**Comment by SergioBenitez** [comment]
This is now fixed in master! I _believe_ we can backport this to Rocket 0.3, but I'll have to take a closer look to ensure it's not a breaking change.

**Comment by valeriansaliou** [comment]
Great! Thanks. I'll wait for `0.4` to bump my deps.
