### ISSUE TITLE
Tests failing to run on OS X - readpath util not default?

### ISSUE THREAD

**Issue by jtmarmon** [SergioBenitez/Rocket#56]
Running `./scripts/test.sh`:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
:: Ensuring all crate versions match...
:: Updating dependencies...
    Updating registry `https://github.com/rust-lang/crates.io-index`
:: Building and testing libraries...
Tried to build and test inside '', but it is an invalid path.
```

I fixed the issue by running `brew install coreutils` and then adding `alias greadpath=readpath`. Is this only a problem with my setup, or do other people get the same errors?

Just to clarify, this is now fixed for me, just bringing it up in case it affects other people.

**Comment by SergioBenitez** [comment]
OS X (from its BSD heritage) doesn't include either `readlink -f` or `realpath`. The `config.sh` script checks if you have `realpath` and uses that. If you don't, it uses `readlink -f`. If you don't have that, you get the error that you see now. I'll change it so that it prints out a nice message instead. But, in general, you need either or.
