### ISSUE TITLE
Revamp query string parsing and handling

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#608]
Rocket v0.4 will include revamped query string parsing and handling. The new design is underway. I will post the proposal for the design as soon as it's ready.

This is a rollup of the following issues:

  * Support ad-hoc query params (#15)
  * Route queries without ? for optional parameters (#376)
  * Change how query parameters are parsed. (#524)

The following pull requests are relevant:

  * Make query string parsing non-strict by default (#434)
  * unprovided "?" query should act like empty query (#454)

**Comment by lholden** [comment]
Looking forward to this a lot Sergio :D

**Comment by SergioBenitez** [comment]
The design is below. I am looking forward to feedback!

## Goals

  1. Be able to match static query strings.
  2. No special-casing of `Form` structures.
  3. Lenient parsing by default.
  4. Unsupplied query-strings are treated as empty query-strings.
  5. A `FromQuery` trait for parsing complete query strings.
  6. Ad-hoc matching of specific query key/value pairs.

## Design

The crux of the design centers around lenient parsing and using `&` as a
position-independent query parameter/segment separator where each query
parameter takes one of three forms:

  1. An arbitrary static string.
  2. One key/value parameter (`<ident>`).
  3. Multi-segment parameters (`<ident..>`).

Formally, the grammar for Rocket query parameters becomes:

```ebnf
QUERY := '?' PARAM ('&' PARAM)*

PARAM := '<' IDENT '>'    # single parameter
       | '<' IDENT '..>'  # trailing query-string text
       | STRING           # static string match
```

Query string handling hinges on two traits:

  * **`FromFormValue`** (as is now)

    Used to validate/parse a **single parameter** (`<ident>`).

  * **`FromQuery`** (**new!**)

    ```rust
    trait FromQuery<'q> {
        type Error: Debug;
        fn from_query(q: &'q Query) -> Result<Self, Self::Error>;
    }
    ```

    Used to validate/parse a **multi-segment parameter** (`<ident..>`).

### Segments

The term _segment_ or _query segment_ shall refer to a single string of text
delimited by `&` after `?` in a URL. Consider the following examples:

  * `?a&b=c&d`: three segments
    1. `a`
    2. `b=c`
    3. `d`
  * `?<a>&<b..>&hello&<c>`: four segments
    1. `<a>`
    2. `<b..>`
    3. `hello`
    4. `<c>`
  * `?<all..>`: one segment
    1. `<all..>`

Rocket considers segments as order-independent. As such, the following URLs are
considered identical:

  * `?<a>&hello&<b..>`
  * `?<b..>&<a>&hello`

Rocket considers empty segments as non-existent and will warn/error on empty
segments in route declarations.

### Static Strings

Static string parameters, declared using a string literal via `?string-literal`,
require a case-sensitive match of arbitrary text in a single query string
segment. There is no associated parameter in the route's handler. Multiple
static strings may be matched if separated by an `&`.

```rust
#[get("/user?new=yes&name=bob")]
fn get_user() -> User { .. }
```

This route requires a request's query string to contain the segments `new=yes`
and `name=bob`. This route will match the following requests:

  * `/user?new=yes&name=bob`
  * `/user?name=bob&new=yes`
  * `/user?new=yes&name=bob&name=michael`
  * `/user?new=yes&name=michael&name&name=bob`

### Single Parameters

Single query parameters, declared via `<ident>`, will match segment keys with
the name `ident` in a GET-like form. The declared type of `ident` must implement
the `FromFormValue` trait.

```rust
#[get(/user?<name>&<age>")]
fn get_user(name: String, age: u16) -> User { .. }
```

This route will match the following requests:

  * `/user?name=Mike&age=20`
    - **name**: "Mike"
    - **age**: 20
  * `/user?name=Mike&age=20&value=foo`
    - **name**: "Mike"
    - **age**: 20
  * `/user?age=20&name=Mike`
    - **name**: "Mike"
    - **age**: 20
  * `/user?name&age=20`
    - **name**: ""
    - **age**: 20
  * `/user?age=20&name`
    - **name**: ""
    - **age**: 20

If a value is missing, the `FromFormValue::default()` value will be used if it
is `Some`. Otherwise, parsing will fail and Rocket will forward the request. For
example, because the default value for `Option<T> where T: FromFormValue` is
`None`, the following route will match any `GET` requests with a path of
`/maybe_user`:

```rust
#[get("/maybe_user?<name>&<age>")]
fn get_user(name: Option<String>, age: Option<u16>) -> User { .. }
```

These include:

  * `/maybe_user`
  * `/maybe_user?`
  * `/maybe_user?name=Mike`
  * `/maybe_user?name=Mike&age=12`
  * `/maybe_user?name=Mike&age=12&bar=120`
  * `/maybe_user?age=12&bar=120`
  * `/maybe_user?foo=12&bar=120`

## Multi-Segment Parameters

Multi-segment parameters, declared via `<ident..>`, match all otherwise
unmatched segments. The declared type of `ident` must implement the `FromQuery`
trait. There can be at most one multi-segment parameter in query-string.

```rust
#[derive(FromFormValue)]
enum Color { Red, Blue, Green }

#[derive(FromForm)]
struct UserExtra {
    #[form(field = "fav-color")]
    fav_color: Color,
    nickname: String,
}

#[get("/maybe_user?<name>&<age>&<rest..>")]
fn get_user(name: String, age: Option<u16>, rest: Form<UserExtra>) -> User { .. }
```

This route matches the following requests:

  * `/user?name=Michael&fav-color=blue&nickname=Mike`
    - **name**: "Michael"
    - **age**: None
    - **rest**: { fav_color: Blue, nickname: "Mike" }
  * `/user?age=40name=Michael&fav-color=blue&nickname=Mike`
    - **name**: "Michael"
    - **age**: Some(40)
    - **rest**: { fav_color: Blue, nickname: "Mike" }
  * `/user?age=40&fav-color=blue&name=Michael&nickname=MM`
    - **name**: "Michael"
    - **age**: Some(40)
    - **rest**: { fav_color: Blue, nickname: "MM" }
  * `/user?age=40&fav-color=blue&name=Michael&nickname=MM`
    - **name**: "Michael"
    - **age**: Some(40)
    - **rest**: { fav_color: Blue, nickname: "MM" }

This route does not match if any of the following hold:

  * No `name` key is provided.
  * The value for `age` does not parse as a `u16`.
  * No `fav-color` or `nickname` key/pairs are provided or `fav-color`'s value
    isn't one of `red`, `blue` or `green`.
  * No parameters besides `name`, `age`, `fav-color`, or `nickname` are
    supplied. This can be changed by using `LenientForm` in place of `Form`.

## Default Trait Implementations

Rocket will implement the `FromQuery` trait for the following types:

  * `Form<T> where T: FromForm`
  * `LenientForm<T> where T: FromForm`
  * `Option<T> where T: FromQuery`
  * `Result<T, T::Error> where T: FromQuery`

## Implementation

Given the following:

  * P.I := [set of single parameter idents] (`ident` in `<ident>`)
  * P.T := [set of single parameter types] (types of `ident` in `<ident>`)
  * M.I := [set of multiple parameter idents] (`ident` in `<ident..>`)
  * M.T := [set of multiple parameter types] (type of `ident` in `<ident..>`)
  * S := [set of static strings]

With the following guarantees:

  * |M.I| = |M.T|
  * |P.I| = |P.T|
  * |M.I| <= 1

Rocket generates the following query string parser (in psuedocode)*:

```rust
  S.matched = [false for _ in S]
  P.parsed = [None for _ in P]
  M.parsed = None
  remaining = empty string

  match every parameter, key/value in query seperated by 'c&' {
    parameter in S => S.matched[parameter] = true,
    key in P => {
      if <P[key].T as FormFormValue>>::parse(value) as v:
        P.parsed[key] = Some(v)
      else:
        return and forward request
    }
    _ if key != "_method" => remaining = remaining.join('&', parameter),
    _ => continue
  }

  if |M| != 0:
    if <M[0].T as FromQuery>>::parse(remaining) as v:
      M.parsed = Some(v)
    else:
      return and forward request

  for key in P.T that is None in P.parsed:
    if <P[key].T as FormFormValue>::default() as d:
      P.parsed[key] = Some(d)
    else:
      return and forward request

  if false in S.matched or None in P.parsed or None is M.parsed:
      return and forward request

  unwrap all and pass to user's function
```

* In the actual implementation, there are no table lookups.
* As an optimization, we might handle specially the case where there is a single
  parameter of any kind.

Things to note:

  * Declaration order of query parameters is irrelevant.
  * Static query parameters imply that the static string must be present in the
    request's query string, but not in which position.
  * Parsing is lenient; any additional parameters are passed to the
    multi-argument parameter (`<ident..>`) if present, or is otherwise ignored.
  * Values may have _defaults_. The default is used if a corresponding key/value
    is not present.
  * Empty values are passed to both `FromFormValue` and `FromQuery` parsers.

## Unanswered Questions

  * Should static string matches be case-insensitive?

**Comment by jebrosen** [comment]
This looks good to me overall. I think examples and tests would make that certain.

I only have one major design question: what if the same query parameter (that is, same name) is specified multiple times by the client?

* Static string parameter (e.g. `name=bob`): The example shows that if the desired static string parameter is found, it will match, even if there is another with that name but a different value.
* "Single parameters": No example given. First one wins? Last one wins? An error if there are multiple matches? This is reminiscent of #205, where a `Vec` (or `FromIterator`) could receive a collection of the given values.
* "Multiple parameters": This should probably be left for `FromQuery` implementors to handle (including `FromForm`, the actual case I believe #205 describes).

Less significant questions, in my eyes:

Is the `Query` type that `FromQuery` receives going to be accessed like a string, like key-value pairs, or both? For comparison, I see that `FormItems` is an iterator type that also provides access to the underlying string.

Another nitpicky thing I thought of is the combination of static strings with single parameters, that is:
`"/?name=blue&<name>"` -- this seems redundant and looks like a mistake, since <name> should always have the value "blue" within the route. A possibility though is that the parser will match `name=blue` to the static string and be done, but then <name> will appear unspecified, or perhaps a subsequent name= parameter will be passed in, if one is present. Whatever the behavior, I think it should be documented if it's not a clear error.

And finally, "Values may have *defaults*." What does this mean, and how does one specify a default? What types can a "default" value be placed into (e.g. is it "anything that implements `Default`")? Is it different from `Option::unwrap_or` in any meaningful way?

I should mention that I only even use query strings in two routes across two projects, so I haven't experienced any of this in practice.

**Comment by SergioBenitez** [comment]
@jebrosen 
> I only have one major design question: what if the same query parameter (that is, same name) is specified multiple times by the client?

The current approach, and what I think we should continue doing, is to validate all of the values but use the last one. Once we support collections, we'll pass in all of the values to the `FromFormValue` implementation and let the implementation decide, but the default implementations of `FormFormValue` for non-collection types will likely do what they do now. The `FromQuery` implementations get to do whatever they want, but `Form` and `LenientForm` will work this way as well.

> Is the Query type that FromQuery receives going to be accessed like a string, like key-value pairs, or both? For comparison, I see that FormItems is an iterator type that also provides access to the underlying string.

Right, this is (somewhat purposefully) underspecified. The idea is that the `Query` type provides helpful methods, similar to `FormItems`. It's possible that `Query` can simply be `FromItems`, in fact.

> Another nitpicky thing I thought of is the combination of static strings with single parameters, that is: "/?name=blue&<name>" -- this seems redundant and looks like a mistake, since should always have the value "blue" within the route. A possibility though is that the parser will match name=blue to the static string and be done, but then will appear unspecified, or perhaps a subsequent name= parameter will be passed in, if one is present. Whatever the behavior, I think it should be documented if it's not a clear error.

This is a good point. As specified, static strings take precedence, but both will be parsed and validated, so unless the type for `<name>` has a default value, two `name` keys will be required in the incoming request where one's value is _not_ `blue`. Note that, as specified, static strings are opaque to Rocket; it wouldn't know that you're matching a `name` key twice since it sees `name=blue` as any other string.

> And finally, "Values may have defaults." What does this mean, and how does one specify a default?

This is [`FromFormValue::default()`](https://api.rocket.rs/rocket/request/trait.FromFormValue.html#method.default).

**Comment by lholden** [comment]
Some thought should be put into supporting query string arrays and maps.

### Arrays

It's common to want to return multiple values of the same name and have them treated as an array of values by the application. 

Forming an array is done by providing multiple params of the same name suffixed with []. This is commonly used in frameworks such as Rails.. This is also easy to do in a form without coercing params together via javascript.
```
?names[]=Sergio&names[]=Lori
```

### Hash Maps

This is done very similar to arrays. This is also something that Rails supports for example.

```
?nicknames[Sergio]=sbenitez&nicknames[Lori]=lholden
```

### Parsing

It might be helpful to indicate to rocket to expect 1 or more params of the same name with the [] suffix.

```
#[get("/people?<names[]>")]
```

Either way... there would have to be some sensing of multiple params having the same name with the [] suffix and applying them to a HashMap or Vec with the same name as appropriate.

**Comment by lholden** [comment]
> Should static string matches be case-insensitive?

I was looking over rfc3986 ( https://tools.ietf.org/html/rfc3986#section-6.2.2.1 ) to see if there was a recommendation for this and the only thing that came up was:

>    For all URIs, the hexadecimal digits within a percent-encoding
   triplet (e.g., "%3a" versus "%3A") are case-insensitive and therefore
   should be normalized to use uppercase letters for the digits A-F.
>
>   When a URI uses components of the generic syntax, the component
   syntax equivalence rules always apply; namely, that the scheme and
   host are case-insensitive and therefore should be normalized to
   lowercase.  For example, the URI <HTTP://www.EXAMPLE.com/> is
   equivalent to <http://www.example.com/>.  The other generic syntax
   components are assumed to be case-sensitive unless specifically
   defined otherwise by the scheme (see Section 6.2.3).

I presume query params are a "other generic syntax component". In practice the case sensitivity really comes down to whichever the application decided to support. I've seen it go either way.

**Comment by SergioBenitez** [comment]
@lholden 

> Some thought should be put into supporting query string arrays and maps.

Absolutely. We've started thinking seriously about support collections in forms. Support will be agnostic to whether we're parsing a query string or a regular form, however.

> It might be helpful to indicate to rocket to expect 1 or more params of the same name with the [] suffix.

This will be done at the type-level. That is, if you specify `param: Vec<T>`, then Rocket will match on `param[]`.

> I presume query params are a "other generic syntax component". In practice the case sensitivity really comes down to whichever the application decided to support. I've seen it go either way.

I'm leaning towards case-insensitivity. My only concern is whether being permissive here can create issues when it comes to: 1) what the programmer expects, and 2) security.

**Comment by supetronix** [comment]
Hi,

I was following this ticket and "https://github.com/SergioBenitez/Rocket/issues/376". I think I have similar question or request. This issue is for "Option Query string" but what about "optional request path"? I have ASP.Net Core background and in that we can declare an action like (just a pseudo code):

```
[get(api/user/<num>)]
public json user(int num = 10)

```
Now if client request "api/user/15" or "api/user/" , they both will hit the same API.

I tried to create the same in Rocket with "Result" and "Option" but it didn't work, I get "404 not found". Here is Rocket example:

```
#[get("/api/user/<num>", format = "application/json")]
fn user(num: Option<i32>) -> Json

```
It works if I request "api/user/5" or "api/user/abc" (invalid i32 value) but it doesn't work if I send "api/user/".

Workaround that I used so far was to create two API methods, one with "<num>" and one without, they both then call an internal method to get data. I didn't want to use "Query String" for this RESTful design.

I think it will be a good addition to Rocket.

Thanks

**Comment by supetronix** [comment]
I appreciate the quick reply. Your suggestion to allow last segment to be empty is what ASP.Net does too, so you are right about that. In fact ASP.Net allows multiple "nullable" segments, given they are the last segments (i.e. can't mix empty segment with fix path and then another empty segment).

If it doesn't fit well with Rocket's design then no biggie, I guess we can always use alternate options e.g. `api/user/0` means get default number of users (using zero or some -ve value).

I must acknowledge that I am so far quite impressed with Rocket web framework. If I have any more suggestion/feature requests etc, then should I open issue on github? or is there a better forum type option?
