### ISSUE TITLE
Update published ring dependency to 0.12

### ISSUE THREAD

**Issue by Perseus101** [SergioBenitez/Rocket#687]
Rocket currently uses the slightly outdated 0.11 version of Ring, which is conflict with another crate I am trying to use which requires 0.12.

It appears Rocket's dependency for version 0.11 comes from using version 0.9 of cookies. Upgrading cookies to 0.10 should solve the problem.

#615 also references the outdated version of ring as a possible problem causing compilation issues.

**Comment by Perseus101** [comment]
It looks like the most up to date version of rocket supports ring 0.10, but isn't published. What is the estimate for when a version with this updated dependency be published?

**Comment by SergioBenitez** [comment]
See #627, #516, #492, and https://github.com/SergioBenitez/Rocket/issues/492#issuecomment-351699847.

The hope is to release Rocket v0.4 by mid-August.

**Comment by jens1o** [comment]
@SergioBenitez Could you give an update on when you want to release `0.4`?

**Comment by SergioBenitez** [comment]
@jens1o As soon as humanly possible. A lot of things have come up since I last gave an estimate that have consumed my time in the last month, many of which are directly relevant to Rocket. I'm super excited to share these with the community. Until then, all I can realistically say is: as soon as possible.
