### ISSUE TITLE
Error retrieving secret key from rocket.toml

### ISSUE THREAD

**Issue by raintears** [SergioBenitez/Rocket#699]
I'm saved a secret key in rocket config file and was trying to retrieve it by accessing the rocket instance but was hit with the error.

```
error[E0616]: field `secret_key` of struct `rocket::config::config::Config` is private
  --> src\main.rs:11:20
   |
11 |     println!("{}", rocket.config().secret_key);
```
Is attaching ```Adhoc::on_attach``` the only way to retrieve secret key? Because I'm accessing it from other modules rather than main where my rocket instance is.

**Comment by mettke** [comment]
Please have a look at https://api.rocket.rs/rocket/config/#retrieving-configuration-parameters

You cannot access the secret_key as it is private. However, you can add it as managed state inside on_attach if you really need to access it inside a route

**Comment by raintears** [comment]
Yeap I tried that and still encounter private constraint error. I checked the source, it's having ```pub(crate)```. Does that mean it can only be used within rocket crate? This is what I have:

```
pub struct RocketConfig(pub Config);

...

/// another.rs
#[get("/config")]
pub fn my_rocket_config(config: State<RocketConfig>) -> Result<()> {
  let config = &config.0;
  println!("{}", config.secret_key);
}
```

**Comment by mettke** [comment]
You are misunderstanding what I'm trying to say. Please read the upper article again:

`configuration environment can be retrieved via the config method on an instance of Rocket and get_ methods`

**Comment by raintears** [comment]
So you mean instead of saving the entire config to state, I should just save the secret key ```on_attach```? because out of that instance there's no possible way to get the secret key from the config?

**Comment by SergioBenitez** [comment]
There is no way to retrieve the secret key. This is by design. We want to restrict how the random key material is used so that signing/encrypting cookies with the key is secure.

There is an open issue (https://github.com/SergioBenitez/Rocket/issues/477) that requests exposing some API to make use of the secret key. I'm not opposed to such an API as long as security is upheld. Let's track such requests there.

**Comment by NAThompson** [comment]
> There is no way to retrieve the secret key. This is by design. We want to restrict how the random key material is used so that signing/encrypting cookies with the key is secure.

I am confused about this. In the sessions example, the secret key is placed in the `Rocket.toml`, so the secret key is only as secure as the privileges of `Rocket.toml`. Since (presumably) most people don't run Rocket as root, then as soon as your server is pwned, the secret key is trivially pwned. I presume you meant that the randomly generated secret key cannot be recovered without resort to (say) running `strings` on the binary? Or are you making a broader claim that someone could misuse the framework once `secret_key` is marked `pub`?
