### ISSUE TITLE
Make ANSI logging opt-in optional

### ISSUE THREAD

**Issue by mattcollier** [SergioBenitez/Rocket#703]
I'd like to revisit this issue: https://github.com/SergioBenitez/Rocket/issues/639

Ran the rocket 'hello world' example on my Debian Stretch and none of the emojis are showing up properly and much of the important logging is displayed in white text on a white background.

I would suggest that ANSI should be an optional feature and should be disabled by default.

As a new user, running into this sort of nuisance out of the gate is very frustrating.

**Comment by SergioBenitez** [comment]
> Ran the rocket 'hello world' example on my Debian Stretch and none of the emojis are showing up properly

It's likely that you don't have a font with emoji support installed and/or your terminal doesn't support unicode. I'd suggest installing a font with emoji support. This isn't an issue with Rocket as much as it is with your environment.

>  I would suggest that ANSI should be an optional feature and should be disabled by default. ...much of the important logging is displayed in white text on a white background.

Presumably you mean coloring? I find colored logs helpful, just like I find syntax highlighting helpful: they help me distinguish between classes of information on the screen. As such, I don't foresee disabling coloring by default.

The argument that we shouldn't be explicitly using "white" or "black" colors because these are common background colors is interesting. On the one hand, I argue that this is a configuration issue: a user with a white terminal background shouldn't configure "white" to be the same color as their background. On the other hand, changing uses of "white" in Rocket to be the "neutral" color (usually white on black backgrounds and black on white backgrounds) might be a simpler solution that makes more people happy.

Another alternative solution is to provide a configuration option for disabling colors, say `ROCKET_COLORS=off` or similar. I'm not immediately opposed to this solution, either.

**Comment by jebrosen** [comment]
With updates to glibc, fontconfig, and other software a year or two ago, the worst thing emoji should do in commonly used terminals today is display as some kind of box and possibly confuse someone running `cargo run` for the first time. I don't have a strong opinion on this, since the emoji aren't necessary but don't do much harm either.

It is unfortunate that gnome-terminal's default color for "white" text is so close to the default white background color. Arguably that is GNOME's fault and not the fault of any application, but I doubt it will change soon. Especially not in a released version on Debian stable.

As far as Rocket's color choice goes, I think changing every occurrence of white or black to the normal text color, or another color not already used in a a given section, would probably solve most if not all issues with them.

Note also that #558 adds a "force_color" option (but not a "force_no_color" option).
