### ISSUE TITLE
How to signal separate thread more work is available?

### ISSUE THREAD

**Issue by Michael-Dutchband** [SergioBenitez/Rocket#714]
Rust nightly, nothing special yet - new to Rust in general, working my way through "the book" as I run into things I think I might need.

If a client posts new data some verification thread needs to post-process it. The client doesn't need to wait for this. I figured;
```rust
#[post("/ping")]
fn ping(trigger: State<mpsc::Sender<bool>>) -> JsonValue {
	// Do data things
	...
	// Signal there's new data to post-process
	trigger.send(true);
	...
}

fn worker(trigger: mpsc::Receiver<bool>) {
	loop {
		trigger.recv().unwrap();
		// Fetch work & get busy
		...
	}
}

fn main() {
	let (tx, rx) = mpsc::channel();

	let sep = conn.clone();
	thread::spawn(move || worker(sep, rx));

	rocket::ignite()
		...
		.manage(tx)
		.launch();
}
```
I'm actually not convinced mpsc is the best primitive to use here - it's just that the book gave some easy to digest examples for it, so figured I'd go with that for now.

However this gives me;
```rust
error[E0277]: `std::sync::mpsc::Sender<bool>` cannot be shared between threads safely
  --> src\main.rs:86:1
   |
86 | / fn ping(trigger: State<mpsc::Sender<bool>>) -> String {
87 | |     trigger.send(true);
...  |
96 | |     }
97 | | }
   | |_^ `std::sync::mpsc::Sender<bool>` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Sender<bool>`
   = note: required by `rocket::State`
```
This is a _multiple_ producer, single consumer primitive, so why can't it be shared? After some searching, I assume it's being seen as a single object and each thread isn't calling ```clone()``` - makes sense, I never told it to - and instead each thread is trying to use the same one.

Some other solutions I found suggest wrapping it in a mutex but I haven't come across a practical example yet (what would that look like?), and yet others suggest I should implement said missing trait. The underlying logic is most likely dealing with thread safety anyway. But implementing traits is (for me, for now) still magic.

An easy solution I also found was replacing ```channel()``` with ```sync_channel(10)``` and ```mpsc::Sender<bool>``` with ```mpsc::SyncSender<bool>```. And this works fine. But it also sets the number of messages to a fixed number; that means risking some connections to time out just because the background workers are busy. I mean, I don't expect this to happen, but why risk it? It feels... inelegant.

Is there a typical pattern to tackle problems like this?

**Comment by jebrosen** [comment]
Whatever managed state you put into Rocket must be usable from multiple threads (e.g. requests) simultaneously. This is why you see ```Sync... required by `rocket::State` ```. `Sender` is not `Sync`, that is, only one thread at a time can use the same `Sender`. A Mutex is probably one of the more straightforward ways to deal with this in general: instead of managing and retrieving `tx`, manage `Mutex::new(tx)` and retrieve a `Mutex<mpsc::Sender<bool>>`. You will have to then lock the Mutex (see [the Mutex documentation](https://doc.rust-lang.org/std/sync/struct.Mutex.html)) to access the `Sender`.

But `SyncSender` may work in this instance after all -- you can use `try_send` instead of `send` to avoid blocking. If you can guarantee that the only message you send means "wake up", then it doesn't matter that there are "too many" of that same message left. For that matter, you could probably use `Sender<()>` or `SyncSender<()>` since you don't actually use the value of the boolean.

Finally, creating your own wrapper types for managed state is always a good idea, as in "`struct WorkerSender(SyncSender<()>);`" This has two benefits: it's clear in the request handler what the value is actually used for, and it allows you to create another similar type if you need to manage two `SyncSender<()>`s.

**Comment by SergioBenitez** [comment]
In addition to what @jebrosen said above, you might find the [`managed_queue`](https://github.com/SergioBenitez/Rocket/blob/master/examples/managed_queue/src/main.rs) example useful.

**Comment by Michael-Dutchband** [comment]
Thanks! I now have;

```rust

struct JobSender(mpsc::SyncSender<()>);

#[get("/pong")]
fn pings(conn: State<mysql::Pool>, trigger: State<JobSender>) -> String {

	trigger.0.try_send(()).unwrap(); // Should be done _after_ queueing work
	...
}

fn worker(conn: mysql::Pool, trigger: mpsc::Receiver<()>) {
	loop {
		trigger.recv().unwrap();
		println!("Hello!");
	}
}


fn main() {
	let (tx, rx) = mpsc::sync_channel(1);

	thread::spawn(move || worker(sep, rx));

	rocket::ignite()
		....
		.manage(JobSender(tx))
		.launch();
}
```
Pretty sure that'll do the job.

I suppose I could similarly wrap the Receiver end in a newtype. I'm not sure I like the additional noise of ".0" etc but I get why this can work to your advantage.

**Comment by jebrosen** [comment]
The need for ".0" can be eliminated in many cases by implementing `Deref` for `JobSender` with `Target = mpsc::SyncSender<()>;`. Whether it's worth adding that implementation is largely down to personal preference and how often `JobSender` is used.

**Comment by SergioBenitez** [comment]
Looks like this has been figured out! Thanks, @jebrosen, @Michael-Dutchband.
