### ISSUE TITLE
static web page router question

### ISSUE THREAD

**Issue by Vincent-bin** [SergioBenitez/Rocket#723]
Rocket version : 0.3.15

When I use react and react-router to build a web page and use rocket static file router,

I found the main page "/index.html" can work but router function can't work, get 404 back, and log shows my router "/answers" match "/<file..>", then 404,

I've tried to use redirect but not useful.

**Comment by mettke** [comment]
You may want to give us a small example. It is quite hard to understand your problem without any bit of code showing what exactly you want to archive

**Comment by Yarn** [comment]
I think the issue he's having is that requests to a folder don't open index.html. This is standard default behavior for servers serving static assets like nginx and apache and some async web frameworks have static file serving with that behavior available built in.

You can see the lack of this feature in the example code in the guide.

I'll probably have some code to share for this soon.

**Comment by jebrosen** [comment]
If `react-router` behaves like other client-side routing frameworks, it probably expects all paths that aren't static assets or APIs to serve the application, and `react-router` will handle everything from there. [A react-router FAQ entry](https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-render-after-refreshing) suggests doing exactly that: serve the index.html page for any route that the server doesn't handle otherwise.

**Comment by Yarn** [comment]
ah, i misunderstood the issue

then it would just be 
```rs
#[get("/<_file..>")]
fn files(_file: PathBuf) -> Option<NamedFile> {
    NamedFile::open(Path::new("static/index.html")).ok()
}
```

**Comment by SergioBenitez** [comment]
I think this is #239?

**Comment by jebrosen** [comment]
@SergioBenitez: It's more than what appears planned with #239, but #239 could be extended to support it.

**Comment by SergioBenitez** [comment]
@jebrosen Indeed. That solution should support `index.html` files. Closing this in favor of #239.
