### ISSUE TITLE
Force requests to time out?

### ISSUE THREAD

**Issue by Riamse** [SergioBenitez/Rocket#750]
Is it possible for Rocket to cap the time a request can take before killing it and returning a 504 Gateway TIme-out?. I looked in the source and it seems possible to have an error catcher for 504s, but it doesn't give me much of a clue as to how to determine when they should be activated at all.

**Comment by jebrosen** [comment]
Sorry for the late response! I remember I promised a comment when you first asked this.

I don't have an obvious and happy answer to your question, because cancellation can be surprisingly hard. For anything involving I/O like a network or database request, platform-specific gotchas tend to pop up as well. The whole situation is made even *more* difficult right now because Rocket depends on an old synchronous version of hyper; I doubt that it's reliable, safe, or maybe even possible to interrupt any arbitrary running worker thread. When Rocket moves to an asynchronous system, possibly based on futures, cancellation of arbitrary tasks will hopefully be much easier and setting a request timeout might be a possibility.

You can, of course, ask for a timeout on any individual operation that accepts one, or implement your own timeout for anything your code does in a loop.

As for error catchers: Rocket provides the ability to register an error catcher for *any* status code, even non-standard ones. Rocket also provides a default error catcher for all standard status codes, but does not generate most of them; they will generally arise from one of your own handlers or from a request guard.

**Comment by Riamse** [comment]
Okay, that makes sense. Thanks for looking into it.

**Comment by SergioBenitez** [comment]
Let's make sure we make something like this configurable when we migrate to the next HTTP library.
