### ISSUE TITLE
Run CI on Windows

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#801]
Travis now supports Windows! This gives us an opportunity to test Rocket on Windows. The [`travis-windows`](https://github.com/SergioBenitez/Rocket/tree/travis-windows) branch enables support for Travis on Windows. What's more, recent commits have fixed several issues with the unit tests that resulted in failures on Windows. This should mean that, given the right environment, Rocket's test suite should pass on Windows.

Unfortunately, tests currently fail on Travis for Windows because of missing libraries. In particular, we need three native libraries to run all of Rocket's test suite:

  * `libmysqlclient`
  * `sqlite3`
  * `libpq` (postgres)

According to [windows-server-2016-ci-onion-packages.txt](https://github.com/travis-ci/packer-templates/blob/master/packer-assets/windows-server-2016-ci-onion-packages.txt), mysql and postgres are preinstalled, so it should be a matter of setting the correct environment variables or similar to get the Rust libraries to find them. `sqlite3` is installable via [Chocolatey](https://chocolatey.org/), which is preinstalled on the Travis image.

If anyone is particularly familiar with native library management in Windows and wants to take a stab at getting the right incantations in the `.travis.yml` file, your help would be much appreciated.

**Comment by Ambyjkl** [comment]
I'll try giving this a shot

**Comment by jebrosen** [comment]
@Ambyjkl Have you made any progress on this? I'm attempting this today but don't want to duplicate your efforts.

**Comment by Ambyjkl** [comment]
Well not a lot, was busy with work. I got Travis to give me debug access to my builds on my fork (you have to go through customer support, they are not active during the weekends) which would let me ssh into the containers to see what's going on. I can add you as a collaborator on my fork and you can attempt stuff there.

**Comment by jebrosen** [comment]
I did some tinkering this morning, figuring some things out about the CI environment using sophisticated tools like `ls -R`. I hoped it would be a quick process, but there are some serious issues that I would want to troubleshoot by replicating on a local machine first and I don't want to deal with Windows this weekend.

Here's what I could figure out:

## General

It takes Windows 4-5 minutes to install rust, compared to about 20 seconds on Linux. This made it very slow to test changes.

Travis appears to be installing the listed packages (https://github.com/travis-ci/packer-templates/blob/master/packer-assets/windows-server-2016-ci-onion-packages.txt) via chocolatey (https://github.com/travis-ci/packer-templates/blob/master/packer-scripts/Bootstrap-Windows.ps1#L18-L24).

## SQlite

This seems like it could work but I haven't tested it:
```
choco install sqlite
SQLITE3_LIB_DIR="$ChocolateyInstall/lib/SQLite/tools"
```

## MySQL

The [chocolatey mysql package](https://chocolatey.org/packages/mysql) hasn't been updated since April 2017, and there are numerous comments about it being broken and missing dependency specifications.

## Postgres

I have no idea why I can't find this. It's apparently not in `Program Files` or in the chocolatey directory. I didn't check `Program Files (x86)`, but I didn't think the 32-bit version would be selected. Maybe it's failing and not ending up in the Travis image.

**Comment by jebrosen** [comment]
Well, this has been a fun adventure. (see also https://github.com/jebrosen/Rocket/commits/travis-windows )

## sqlite

The chocolatey package for sqlite installs the binaries from the official sqlite downloads page, which includes a `.def` and a `.dll` but no corresponding `.lib` file. Supposedly a `.lib` file might have existed or could be regenerated from the `.def` file, but I'm out of my depth here.

It works with `features = ["bundled"]` on `libsqlite3-sys`, of course, but that's a bit tricky to set without setting it for everyone.

## MySQL

The chocolatey package for mysql installs to `C:\tools\mysql` on my machine. It looks like a bug in the install script, which also throws a bunch of warnings about using deprecated/renamed functions from chocolatey. Unfortunately, https://github.com/sgrif/mysqlclient-sys wants to run `mysql_config` but the package installs it as `mysql_config.pl`. It's annoying that perl would need to be installed as well.

## Postgres

I got this to work easily locally, but I don't see it actually installed on Travis.
Side note: Only the `diesel_` pools need the "official" client libraries; the `mysql` and `postgres` crates implement the respective protocols directly and should already work.

## vcpkg

At this point I've changed approaches entirely because the upstream/chocolatey packages aren't really working out for me. All of the rust crates support using `vcpkg` to install the libraries, so I'm trying that now.

**Comment by Ambyjkl** [comment]
Hmm that's fun. If you get bored I can take over.

On 17/11/2018, Jeb Rosen <notifications@github.com> wrote:
> Well, this has been a fun adventure. (see also
> https://github.com/jebrosen/Rocket/commits/travis-windows )
>
> ## sqlite
>
> The chocolatey package for sqlite installs the binaries from the official
> sqlite downloads page, which includes a `.def` and a `.dll` but no
> corresponding `.lib` file. Supposedly a `.lib` file might have existed or
> could be regenerated from the `.def` file, but I'm out of my depth here.
>
> It works with `features = ["bundled"]` on `libsqlite3-sys`, of course, but
> that's a bit tricky to set without setting it for everyone.
>
> ## MySQL
>
> The chocolatey package for mysql installs to `C:\tools\mysql` on my machine.
> It looks like a bug in the install script, which also throws a bunch of
> warnings about using deprecated/renamed functions from chocolatey.
> Unfortunately, https://github.com/sgrif/mysqlclient-sys wants to run
> `mysql_config` but the package installs it as `mysql_config.pl`. It's
> annoying that perl would need to be installed as well.
>
> ## Postgres
>
> I got this to work easily locally, but I don't see it actually installed on
> Travis.
> Side note: Only the `diesel_` pools need the "official" client libraries;
> the `mysql` and `postgres` crates implement the respective protocols
> directly and should already work.
>
> ## vcpkg
>
> At this point I've changed approaches entirely because the
> upstream/chocolatey packages aren't really working out for me. All of the
> rust crates support using `vcpkg` to install the libraries, so I'm trying
> that now.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SergioBenitez/Rocket/issues/801#issuecomment-439646514


-- 
Thanks,

Warm Regards,

Ambareesh Balaji

**Comment by jebrosen** [comment]
Here's the (in-progress) travis build status for my latest commit, which uses vcpkg: https://travis-ci.org/jebrosen/Rocket/builds/456684233 . I know it failed locally yesterday, as far as I can tell because the rust vcpkg adapter isn't emitting the right linking directives to cargo and/or cargo isn't applying them correctly. It also takes ridiculously long to compile everything through vcpkg, so it would have to be cached if we actually go that route for testing.

I'm not going to look at this again for at least another week, it's even more draining than I expected it to be.

**Comment by messense** [comment]
Any progress on this issue?

**Comment by jebrosen** [comment]
Unfortunately not. It's been a good six months, so maybe the chocolately packages are actually working well enough we can use them. Azure Pipelines was suggested as another option as well, but I don't believe anyone has made an attempt. IIRC @dgriffen has mentioned it in IRC, and it looks like diesel is using Azure Pipelines as well.

**Comment by messense** [comment]
I think @SergioBenitez had done some Azure Pipelines tests here: https://github.com/SergioBenitez/Rocket-Azure

**Comment by SergioBenitez** [comment]
@messense I got Linux and macOS working, but Windows is still a mystery.

**Comment by messense** [comment]
Maybe we could take inspiration from `diesel`'s Azure Windows CI setup: https://github.com/diesel-rs/diesel/blob/1fe9487c92a73c26f26d3ce7e6924d2659101a34/azure-pipelines.yml#L110

**Comment by jebrosen** [comment]
The key takeaways from that: they use the visual studio tools to generate a `.lib` file for sqlite based on the `.def` file, postgres "just works" via chocolatey, and they run the regular mysql msi installer.

We don't have any tests that use a database other than sqlite -- the mysql zip archive might be enough to get the client libraries which is all we (currently) need.
