### ISSUE TITLE
behavior of Uri::percent_encode seems incompatibile with uri parsing  in 0.4-rc

### ISSUE THREAD

**Issue by macpp** [SergioBenitez/Rocket#808]
i have following example build using rocket v0.3.17 :
```rust 
#![feature(plugin)]
#![plugin(rocket_codegen)]
extern crate rocket;
use rocket::response::Redirect;
use rocket::http::uri::URI;

#[get("/hello/<name>")]
fn hello(name: String) -> String {
    format!("Hello, {} !", name)
}
#[get("/")]
fn redirect() -> Redirect {
    let name = "John[]|\\";
    Redirect::to(&format!("/hello/{}", URI::percent_encode(name)))
}

fn main() {
    rocket::ignite().mount("/", routes![hello, redirect]).launch();
}
```
browsing localhost:8000 simply results in redirect and  seeing `Hello, John[]| !`
i tried to migrate it to rocket 0.4-rc (i hope that this migration is not messed up) :
```rust
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use]
extern crate rocket;
use rocket::response::Redirect;
use rocket::http::uri::Uri;

#[get("/hello/<name>")]
fn hello(name: String) -> String {
    format!("Hello, {} !", name)
}
#[get("/")]
fn redirect() -> Redirect {
    let name = "John[]|\\";
    Redirect::to(format!("/hello/{}", Uri::percent_encode(name)))
}
fn main() {
    rocket::ignite().mount("/", routes![hello, redirect]).launch();
}
```
this time, browsing localhost:8000 results in Internal server error, and no redirect. This seems incorrect. 
console output :
```
    => Matched: GET / (redirect)
Error: Invalid URI used for redirect.
    => Outcome: Failure
    => Warning: Responding with 500 Internal Server Error catcher.
```
additionaly, if i try browse `http://localhost:8000/hello/John[]|` directly i get 
```
400: Bad Request
The request could not be understood by the server due to malformed syntax.
```
 console output: 
```
Error: Bad incoming request: expected EOF but found '[' at index 11
    => Warning: Responding with 400 Bad Request catcher.
```
this (calling /hello without encoding `John[]|`)  worked in v0.3.17

i checked rocket's source code, and it seems that percent_encode doesn't encode following symbols : `[` , `]` , `|`, `\`. It seems that in v0.4-rc  any of this symbols causes some kind of uri parsing error. 

ad-hoc solution to this problem is using extended encode set:
```rust
percent_encoding::define_encode_set! (
    pub EXTENDED_ENCODING_SET = [percent_encoding::PATH_SEGMENT_ENCODE_SET] | {'[', ']' ,'|' , '\\'  }
);
pub fn encode_uri(to_encode: &str) -> String {
    percent_encoding::utf8_percent_encode(to_encode, EXTENDED_ENCODING_SET).to_string()
}
```
with this encoding set, exaple works again. I have no information about any other symbol that causes this problem, but there can be more.

This problem seems like mismatch between uri parsing and current encoding set in Uri::percent_encode.

Anyway, thank you for developing rocket. I really like this framework !

**Update:**
I also tried to use uri! macro :
```rust
Redirect::to(uri!(hello: name = "John[]|\\"))
```
with uri! macro Redirect works, but /hello still fails with 
```
Error: Bad incoming request: expected EOF but found '[' at index 11
    => Warning: Responding with 400 Bad Request catcher.
```

**Comment by SergioBenitez** [comment]
Rocket isn't doing quite the right thing here. Before I discuss that, I want to note that `[` and `]` are _not_ valid URI characters in that position. In particular, [RFC 3986](https://tools.ietf.org/html/rfc3986#appendix-D.1) is fairly clear about this (emphasis mine):

>    IPv6 (and later) literals have been added to the list of possible
   identifiers for the host portion of an authority component, as
   described by [RFC2732], with the addition of "[" and "]" to the
   reserved set and a version flag to anticipate future versions of IP
   literals.  **Square brackets are now specified as reserved within the
   authority component and are not allowed outside their use as
   delimiters for an IP literal within host.**  In order to make this
   change without changing the technical definition of the path, query,
   and fragment components, those rules were redefined to directly
   specify the characters allowed.

What's more, `|` and `\` are also not valid URI characters. The implication is that 1) the browser should not send those character in-the-raw (are you sending a request from a browser), and 2) Rocket's `Uri::percent_encode()` (and transitively, `uri!`) should percent-encode these characters. It seems that Rocket isn't doing the latter, which we should fix.

I'll have a fix ASAP.
