### ISSUE TITLE
Start without working directory

### ISSUE THREAD

**Issue by jethrogb** [SergioBenitez/Rocket#809]
Is there currently no way to start Rocket without a working directory? I looked in https://api.rocket.rs/v0.4/rocket/config/struct.ConfigBuilder.html and https://api.rocket.rs/v0.4/rocket/struct.Config.html but I couldn't find a way.

I want to start Rocket without filesystem access for security reasons.

**Comment by jebrosen** [comment]
> Is there currently no way to start Rocket without a working directory?

I'm not sure if I understand your question correctly. Off the top of my head, I can't think of any situation where a process can be completely without a working directory on operating systems Rocket supports. If you mean you want to *change* the working directory, that can be done before starting the server or by using [std::env::set_current_dir](https://doc.rust-lang.org/std/env/fn.set_current_dir.html).

> I want to start Rocket without filesystem access for security reasons.

Changing the working directory doesn't really help much on its own, since the application can access files via absolute paths. Routes that use [FromSegments](https://api.rocket.rs/v0.4/rocket/request/trait.FromSegments.html#impl-FromSegments%3C%27a%3E) in conjunction with a known safe starting point should be safe from trivial path traversal attacks, however.

**Comment by SergioBenitez** [comment]
@jebrosen My understanding is that @jethrogb wants to run a Rocket application inside of a container without a file system.

@jethrogb I don't believe this is currently possible. Several configuration components assume access to the file system. For instance, TLS configuration occurs through files (though #551 and #508 advocate for changing this in various wise), and templates are discovered from the file system. We could certainly change Rocket to work without a file system, but I wonder if it's worth it. Why not create an empty, zero-sized file system?

**Comment by jethrogb** [comment]
I think it's really good to have a default configuration that tries to read things from the filesystem, this is very convenient for development etc. However, I think all configuration should be able to be done by either calling builder methods or passing in configuration files as strings.

> Why not create an empty, zero-sized file system?

I want to disable all filesystem-related system calls using Linux security features. Filesystems are a non-feature for most microservices. Besides, if it's already possible to start Rocket in an empty working directory, why is it an error to not have one? I manually deleted some of the code that deals with config file handling and Rocket seems to work perfectly fine.

**Comment by jethrogb** [comment]
To test starting without a working directory (on Linux):
```c
// no-cwd.c
#include <unistd.h>

char *getcwd(char *buf, size_t size) {
	return NULL;
}
```

```
$ gcc -fPIC -shared no-cwd.c
$ LD_PRELOAD=./a.out ./rocket-binary
```

**Comment by jethrogb** [comment]
I think not depending on a filesystem is also a requirement for supporting platforms such as CloudABI. cc @EdSchouten

**Comment by SergioBenitez** [comment]
I think this is a reasonable request. Let's do it.

**Comment by jethrogb** [comment]
Thanks, I tested the changes, and it works perfectly!
