### ISSUE TITLE
What is the best way to integrate the MongoDB in Rocket

### ISSUE THREAD

**Issue by jianjian01** [SergioBenitez/Rocket#831]
I'm new to Rust, and Rocket.

Reading through the [guide](https://rocket.rs/guide/state/#databases)， There are support for MySQL, Postgres, Sqlite and Redis.

Then,  What is the best way to integrate the MongoDB. 
In addition, Is there any plan to add the official support for MongoDB and other NoSQL Database？

**Comment by SergioBenitez** [comment]
@ELD Would it be simple to add support to mongodb via https://github.com/mongodb-labs/mongo-rust-driver-prototype and https://gitlab.com/petoknm/r2d2-mongodb?

**Comment by ELD** [comment]
@SergioBenitez So, spiking a bit on this this morning and remembering why we didn't ship with MongoDB was because the r2d2 driver didn't accept a URI. Instead, it required we parse out the URI and feed it in separately. I'm more than happy to revisit adding support for it, though. I assume they're still compatible with one another (the Rust MongoDB driver has a couple recent updates).

I can continue working on this, if we'd like to make this a priority for `rocket_contrib`.

**Comment by SergioBenitez** [comment]
@ELD Yes, we should add support for mongodb; it's at least as popular as the other databases we support.

Aside from parsing the connection URL itself (`user:pass@host:port/db` into `user`, `host`, `db`, etc) we can submit a PR to the r2d2 crate and add support for this kind of URL. My feeling is that submitting a PR is the better approach; this seems like something that crate should support anyway. Should they refuse, we can implement the parsing here.

**Comment by ELD** [comment]
@SergioBenitez Sounds good. I can cook up a PR for `r2d2-mongodb` to handle the parsing. I agree that it should be handled there since the original adapter has a method to accept a connection from a URI.

Worst case, yes, we can implement the parsing within `rocket_contrib`, but having it upstream would be better.

**Comment by karasjoh000** [comment]
Use r2d2 and r2d2-mongodb. I am using it works fine, but it is a little slow. 

`
pub struct Conn(pub PooledConnection<MongodbConnectionManager>);

impl Deref for Conn {
    type Target = <r2d2_mongodb::MongodbConnectionManager as ManageConnection>::Connection;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<'a, 'r> FromRequest<'a, 'r> for Conn {
    type Error = ();

    fn from_request(request: &'a Request<'r>) -> request::Outcome<Conn, ()> {
        let pool = request.guard::<State<Pool<MongodbConnectionManager>>>()?;
        match pool.get() {
            Ok(db) => Outcome::Success(Conn(db)),
            Err(_) => Outcome::Failure((Status::ServiceUnavailable, ())),
        }
    }
}
`

**Comment by jebrosen** [comment]
I think this has been resolved now that #838 is merged.
