### ISSUE TITLE
Note that database connection deref might require `&*`

### ISSUE THREAD

**Issue by SergioBenitez** [SergioBenitez/Rocket#855]
Depending on the context where an `&impl Deref<Target = Connection>` is used, the auto-deref may or may not happen. We should make it clear to users that `&*` might be required.

**Comment by anthonyray** [comment]
That would be a great addition ! I got stuck several hours on this !

**Comment by ELD** [comment]
Yeah, this is a point of friction I did run into, too. It's sad that the `Deref` coercion doesn't always happen 😢

**Comment by jebrosen** [comment]
A "nicer" solution might be to implement `Connection` for each connection type:

```rust
impl Connection for #request_guard_type {
    ...
}
```

This actually turns out to be hard for several reasons:

* `Connection` has the supertrait `SimpleConnection`, so that would need to be implemented too.
* The `Connection` trait can only even be named when compiling with a diesel-related feature enabled. `rocket_contrib` currently does not know about the enabled features.
  * So we pass the feature along to rocket_contrib, and rocket_contrib can only emit the `impl` when the diesel feature is enabled.
  * Another possibility *might* have been to implement a trait in contrib, not contrib_codegen, for all request guard types (I'll call it `RocketPooledConnection` for the sake of argument). This would allow us to `impl<T> Connection for T where T: RocketPooledConnection` in rocket_contrib... oops, that violates the orphan rules.


* But wait a minute! What about non-diesel pools?
  * You're absolutely right! We actually need to write this impl instead:
    ```rust
    impl Connection for #request_guard_type where #connection_type: Connection {
        ...
    }
    ```
    But that requires `#[feature(trivial_bounds)]` -- which, funnily enough, is happening because diesel wants to generate `impl`s similar to these via macros. So I'm going to throw in the towel on this whole idea for the third or fourth time, finally documenting it now so nobody (including myself) makes the same mistakes I have, *again*.

... but not all hope is lost. I think it would still be possible to do this manually at the database-type-definition-site with yet another macro, maybe called as `#[derive(DieselConnectionPassThru)]` or `impl_diesel_connection_for!(type, inner_type);`. The implementation of these macros is left as an exercise for the reader.
