### ISSUE TITLE
Guard to block video display

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#925]
I want to prevent videos from being displays if entering using full `url` path, the idea I got is to make `API guard`, and implementing it as:

```rust
#[get("/static/videos/<path>")]
pub fn legal_call(key: Logged, path: &RawStr) -> &'static str {
    "legal action"
}

#[get("/static/videos/<path>", rank = 2)]
pub fn illegal_call(path: &RawStr) -> &'static str {
    "ah ah ah, you are doing illegal action"
}
``` 

The above prevented the video from being displayed/run in all cases, even if it is called with API, I think my `legal_call` function above is wrong, any idea?

**Comment by jebrosen** [comment]
The only relevant difference between them appears to be `Logged`. You should debug the implementation of `FromRequest` for `Logged` and ensure it is activating when it should be.

**Comment by hajsf** [comment]
@jebrosen  The guard I made work fine for returning FULL page, I doubt the error is in the `return` type, but do not know what shall I return to make it accessible once the `Logged` guard is passed!

**Comment by jebrosen** [comment]
I had forgotten about this issue. Are you still having trouble with this?

**Comment by hajsf** [comment]
Thanks @jebrosen for coming back, actually yes, I still could not resolve it.

**Comment by jebrosen** [comment]
Given the original code:

```rust
#[get("/static/videos/<path>")]
pub fn legal_call(key: Logged, path: &RawStr) -> &'static str {
    "legal action"
}

#[get("/static/videos/<path>", rank = 2)]
pub fn illegal_call(path: &RawStr) -> &'static str {
    "ah ah ah, you are doing illegal action"
}
```

The `FromRequest` implementation for `Logged` can return one of three `Outcomes`:

* `Outcome::Success`: `legal_call` route will run.
* `Outcome::Forward`: `illegal_call` route will be checked next in the list (because it is next in `rank`), and in this case always run.
* `Outcome::Failure`: An error will be returned, skipping `illegal_call` but processing error catchers.

I believe you said it always goes to `illegal_call`, which as far as I can see will only happen if `legal_call` was not mounted, or if `Logged` returned `Outcome::Forward`.

Can you post the log output from when you access `/static/videos/<path>`, both logged in and logged out? It should look like this (logged in):

```
GET /static/videos/... text/html:
    => Matched: GET /static/videos/<path> (legal_call)
    => Outcome: Success
    => Response succeeded.
```

and (logged out):

```
GET /static/videos/... text/html:
    => Matched: GET /static/videos/<path> (legal_call)
    => Outcome: Forward
    => Matched: GET /static/videos/<path> [2] (illegal_call)
    => Outcome: Success
    => Response succeeded.
```

The actual log output should make it clear which part is or isn't working as expected.

**Comment by SergioBenitez** [comment]
Looks like this was answered! Closing out.
