### ISSUE TITLE
Need a way to prevent credentials in config from showing up on start up

### ISSUE THREAD

**Issue by llk89** [SergioBenitez/Rocket#932]
## Feature request

Currently if any credential is loaded with `Rocket::config`, it will be printed in plain text at the start up. It is quite uncommon to treat logs as confidential data, so I'd think it'd be better to be masked, or don't show up at al, to prevent the leak of passwords.

For now, `rocket_conrib::database` seems to be the number one victim as almost all database require some form of password. 

For implementation, I'd propose to add a function to `Config` to mark the configuration keys with confidential information. e.g.

```rust
// At command line: ROCKET_DB_PASS=foobar cargo run
let mut config = /* ... */
config.set_as_credential("db_pass");
```

**Comment by jebrosen** [comment]
As far as I can tell the `secret key` (previously `session key`) has always been protected, but Rocket currently has no way of knowing which "extras" are sensitive.

Rocket also can't currently rely on fairings to inform that since the configuration is printed before fairings can even be attached.

This should be considered as #852 progresses. Perhaps configuration (or just the `extras`) could be printed only after fairings/applications have had a chance to "mark" data as sensitive. But tracking whether or not data is sensitive can be pretty complex when nesting gets invovled, so maybe printing only keys in `extras` would be a sufficient compromise.

**Comment by llk89** [comment]
I wouldn't pretend as if I know much about rocket internals, but I'd agree just printing keys will be sufficient in all cases.

**Comment by jrmiller82** [comment]
I noticed this too; I don't like that my database password gets printed to stdout / log file each time at start up. This needs to be easy for the user to disable to increase security.

**Comment by SergioBenitez** [comment]
I agree. This will be handled in #852. Let's discuss it there.
