### ISSUE TITLE
No way to pass Request into handlers

### ISSUE THREAD

**Issue by unordered** [SergioBenitez/Rocket#939]
# Questions

I want to get some header (like: Accept) from request in my controller, but i can't find a way to pass request parameter into handler. maybe i missed something?

**Comment by jebrosen** [comment]
Rocket encourages usage of [Request Guards](https://rocket.rs/guide/requests/#request-guards), which encode validation logic in a route-agnostic way. In this situation, one of the following is preferred (applies equally to `Accept` or any other header:

1. Make a request guard type that would check the `Accept` header value and return an enum whose variants correspond to valid `Accept` values recognized by the application.
2. Make a request guard for each possible recognized value of the `Accept` header. These types could be generated with a macro since the implementation will be similar between them. Each route would be duplicated once for each `Accept` value that the route is valid for, using `rank` to control the order in which they are tested.

The choice between 1 and 2 depends on how much of the route's logic changes based on the header value and how much repetition multiple routes would be.

Another option is to provide the value of the `Accept` header directly to routes, but in my experience that more easily leads to difficult-to-maintain duplicated code between routes.

**Comment by unordered** [comment]
@jebrosen thanks!
