### ISSUE TITLE
Templates in single-file-binary application

### ISSUE THREAD

**Issue by TotalKrill** [SergioBenitez/Rocket#943]
I am using rocket 0.4.0, and I am using handelbar templates in my application, along with some static files (.css, .js, images etc). My goal is to have this app I am building become a single-binary application. 

With that I mean, there is only one binary needed after compilation, no extra files that I somehow have to define paths to, be it absolute or relative paths. In my hunt for this I was pointed towards [rust-embed](https://github.com/pyros2097/rust-embed), and it works fine for most of my static files. 

However, I am at a loss on how to get the handlebars Template to load the templates from this instead of trying to find them in the folder. 

Currently i am using this to the templates ( from the examples )

    rocket::ignite()
        .attach(Template::fairing())

and in routes i use to present the page,

    context.insert("FLASH", error);
    Template::render("setup", &context)

 is there any way I could get the render function to accept either a string with the contents instead of a filename or something? I saw the Template::custom(), but a bit lost if I could use that to modifiy where the templates are loaded from.

**Comment by jebrosen** [comment]
> In my hunt for this I was pointed towards rust-embed, and it works fine for most of my static files.

It sounds like rust-embed is working for you, so I won't dwell on it. `include_bytes!` or something based on it would be a dependency-free solution if you ever need it.

> However, I am at a loss on how to get the handlebars Template to load the templates from this instead of trying to find them in the folder.
> I saw the Template::custom(), but a bit lost if I could use that to modifiy where the templates are loaded from.

I'm afraid `Template` won't help you much in its current state. `Template::fairing` loads templates from files only, and templates added to `Template::custom` can't be used with `Template::render` later (see also https://github.com/SergioBenitez/Rocket/issues/850#issuecomment-447676229).

There are a few options for dealing with templates:

* Continue using `Template` by doing something clever, like unpacking templates to a temporary directory and then loading them from there. This is my least favorite solution because of complexity.
* Use handlebars manually and put an instance of `Handlebars` in managed state. This gives you complete control over the template registration and rendering system, but you will have to do yourself a few of the things Rocket enables "for free" (i.e. mixed template engine support, filesystem watching).
* Use a compile-time template engine, such as askama, maud, or something else listed at http://www.arewewebyet.org/topics/templating/.

**Comment by TotalKrill** [comment]
Thank you for the answer, I think that your second alternative might be the best, and for that purpose using include_bytes! for only the templates might be an idea. I just liked the rust-embed because of the similarity to a file system, but the files are constant and always included with the application. 

I will see if I can get it to work, I am currently not doing that much advanced stuff with the templates

**Comment by TotalKrill** [comment]
#227 Is quite similar to this and shows how to return a string as Html, I use this but first i create the String using handlebars and include_str!("path/to/template");
example: 
```
#[get("/get_status")]
pub fn get_status() -> content::Html<String> {
    let context = TemplateContext::new();

    let reg = Handlebars::new();
    let html = reg.render_template(STATUS, &context).unwrap_or("".to_string());

    content::Html(html)
}

```
There is also more of this topic in #234 

My static files are now supplied like this using rust-embed

```
#[get("/static/<file..>")]
pub fn file<'r>(file: PathBuf) -> response::Result<'r>  {
    //NamedFile::open(Path::new("static/").join(file)).ok()

    let filename = file.display().to_string();
    Asset::get(&filename).map_or_else(
        || Err(Status::NotFound),
        |d| {
            let ext = file
                .as_path()
                .extension()
                .and_then(OsStr::to_str)
                .ok_or(Status::new(400, "Could not get file extension"))?;
            let content_type = ContentType::from_extension(ext).ok_or(Status::new(400, "Could not get file content type"))?;
            response::Response::build().header(content_type).sized_body(Cursor::new(d)).ok()
        },
        )
}
```
Thank you for your help jebrosen! I can now embed everything except the Rocket.toml file

**Comment by opeolluwa** [comment]
I'm using version 0.5 of rocket and Im looking for a way to include template and static files `.csd` `.js` in the binary when deployed to Heroku
