### ISSUE TITLE
Making Rocket rewrite URLs internally to proxy to another application

### ISSUE THREAD

**Issue by drenghel** [SergioBenitez/Rocket#945]
Hi, 
I have a question, it may sounds silly, but I'm mostly newbie when it comes to web apps, RESTfull stuff, ... :)

I have a website that used to run only with Apache & PHP  
with for sole path used a root "/" and  "/services/piwigo/"

Worked all swell but then I wanted to replaced the logic that handles the root website with Rocket **(currently 0.4.0)**. 

So I changed Apache listening port to 81 and build a request handler as follows : 

```
#[get("/services/piwigo")]
fn piwigo() -> Redirect {
    Redirect::to("http://www.snip.foo:81/services/piwigo/")
}
```

But to my disappointment requests like `services/piwigo/picture.php?/1661/category/32` would fail into a 404 (Not surprising now that I get it better)

So after trying to make out how work multiples segments and such, I put together a another method

```
#[get("/services/piwigo/picture.php?/<foo>/category/<bar>")]
fn piwigo(foo: String, bar: String)-> String {
    format!(" {} {} ", foo, bar)
    // No redirection here, I'im just trying out
 }

```
And still no luck, I'm getting 

```
error: malformed parameter or identifier
  --> src/main.rs:26:37
   |
26 | #[get("/services/piwigo/picture.php?/<foo>/category/<bar>")]
   |                                     ^^^^^^^^^^^^^^^^^^^^^
   |
   = help: parameters must be of the form '<param>'
   = help: identifiers cannot contain '<' or '>'
```

Because of that pesky '?' in my URL, that's followed by a '/' and I can't make out what it means, it goes beyond my basic understanding ^^"  
(And neither does Rocket, getting mixed signals, param or identifier?).  

Here we are, I tried to be clear although I'm not proficient at that kind of programming.  
Thanks in advance for any help.  

Cheers.

**Comment by drenghel** [comment]
I've been digging a bit tonight, I'm wondering if it could get done by implementing a custom [`Handler`](https://api.rocket.rs/v0.4/rocket/trait.Handler.html)  :thinking:

**Comment by drenghel** [comment]
Having one server being a reverse proxy looks pretty good too ^^  
(Noob learning by himself here o7 )

**Comment by drenghel** [comment]
Solved it with the reverse proxy
```
<LocationMatch "aFolder/myService">  
  ProxyPass "!"  
</LocationMatch>
```

Leaving it open because I'm still wondering if it could be done the ugly way (with 2 ports and dealing with the weird "\")

**Comment by jebrosen** [comment]
I've updated the title to better describe the problem. A `Redirect` is external (sent to the browser in the `Location` header), but you wanted an internal redirect aka a rewrite. Generally, whatever performs the rewrite must query the target - in Rocket, this can be done with `StaticFiles` for serving a directory or with an external library such as `reqwest` for HTTP. As you found though, Apache (or ngnix) can do this as well, and is often a better place to do this than inside Rocket.

In your case, you need something to run the PHP code - Apache's `mod_php` and `php-fpm` are the two main ways to do this off the top of my head, and I think php-fpm would be even more to set up than what you already have.

---

The error you ran into was because Rocket does not natively support `?/<foo>/category/<bar>` query strings, only form-like queries (`?name=value&name2=value2`). In this situation, you can use [`Origin::query()`](https://api.rocket.rs/v0.4/rocket/http/uri/struct.Origin.html#method.query) to access the raw query string, where you could parse it manually or forward it as-is somewhere else.

**Comment by drenghel** [comment]
I'll try it out for science ;)  

Thanks a lot for the elaborated answer !
