### ISSUE TITLE
mysql_pool Error: DriverError { Unexpected packet }

### ISSUE THREAD

**Issue by kswope** [SergioBenitez/Rocket#952]
Everything was running fine using diesel_mysql_pool,

switching over to mysql_pool started a packet apolocalpyse

```
[Running 'cargo run']
Configured for development.
    => address: 127.0.0.1
    => port: 8080
    => log: normal
    => workers: 10
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 60s
    => tls: disabled
    => [extra] databases: { mydb = { url = "mysql://root:@localhost/wheatt_development" } }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
Error: DriverError { Unexpected packet }
...
```

OSX High Sierra

.env
```
ROCKET_DATABASES={mydb={url="mysql://root:@localhost/wheatt_development"}}
```

Cargo.toml
```
[dependencies]
dotenv = "0.13.0"
serde = "*"
serde_json = "*"
serde_derive = "*"
rocket = "*"
[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["mysql_pool", "json"]
```

main.rs
```
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use]
extern crate rocket;
#[macro_use]
extern crate rocket_contrib;
use rocket_contrib::databases::mysql;
extern crate serde_derive;

use dotenv::dotenv;

#[database("mydb")]
pub struct DbConn(mysql::Conn);

#[get("/")]
fn index() -> String {
        String::from("hello")
}

fn main() {
        dotenv().ok();
        rocket::ignite()
                .attach(DbConn::fairing())
                .mount("/", routes![index])
                .launch();
}
```

**Comment by kswope** [comment]
This might be related
https://github.com/blackbeam/rust-mysql-simple/issues/160

**Comment by jebrosen** [comment]
What version of MySQL is the server running? What version of the mysql crate is being used (i.e. in `Cargo.lock`)? Diesel uses the system mysql client libraries and `rust-mysql-simple` is an alternative implementation, so it's not surprising to see different behavior.

The linked bug was supposedly already fixed in version 14.2.0, so you may be experiencing a different bug.

@ELD the error message (`Error: DriverError { Unexpected packet }`) looks pretty unhelpful, and I can't figure out where it's getting logged or why it looks that way. Do you have any insight into that?

**Comment by kswope** [comment]
Server version: 8.0.15 Homebrew

[[package]]
name = "mysql"
version = "14.2.0"

**Comment by ELD** [comment]
Sadly, I don't have any additional insight. I used your minimal repro above against MySQL 8.0.15 installed via Homebrew. I couldn't repro the packet apocalypse. My `Cargo.lock` contained the same stanza for the `mysql` package as well. I'm at a loss for why you're seeing this.

Looking at the library, there are a few ways that the `DriverError { Unexpected package }` can be generated. In all cases it deals with authentication with the server. My only guess is that the package isn't smart enough to not try password auth since you have an empty password in your connection string.

If you change your connection string to `mysql://root@localhost/wheatt_development` (no ":" after the username), do you see any change when you run your project?

**Comment by kswope** [comment]
Ok guys I got it, not sure if its actually a bug or not, or where actually the problem is, but this info is going to help somebody someday.

@ELD - removing the colon didn't help.

A blank password only works in this situation if your mysql user is set to use the mysql_native_password authentication plugin, which I think was common before mysql 8.0


The below combination works

.env
```
ROCKET_DATABASES={mydb={url="mysql://root@127.0.0.1/wheatt_development"}}                                    
```
```


mysql root@localhost:mysql> select user, plugin from user where User='root';
+------+-----------------------+
| user | plugin                |
+------+-----------------------+
| root | mysql_native_password |
+------+-----------------------+
```

This doesn't work, give the Unexpected packet error
```
mysql root@localhost:mysql> select user, plugin from user where User='root';
+------+-----------------------+
| user | plugin                |
+------+-----------------------+
| root | caching_sha2_password |
+------+-----------------------+
```

So, if you are following in the rails tradition of no root password on your dev machine, you need to do this ( this is the old, weaker way of doing things, but if its just your dev machine I don't see the harm )
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';          
```

**Comment by jebrosen** [comment]
> the error message looks pretty unhelpful, and I can't figure out where it's getting logged or why it looks that way.

My question there was really about why the error message showed up so many times and used Display instead of Debug. It turns out r2d2 itself uses `error!("{}", error)` in the default configuration (https://github.com/sfackler/r2d2/blob/master/src/lib.rs#L116) - combined with the default connection timeout of 30 seconds, this explains the noise.

---

The only thing I would truly classify as a bug is that mysql says "unexpected packet" instead of something clearer like "unrecognized authentication method". Or maybe it does, but only in the error type's `Debug` and not `Display`. Or maybe it doesn't fully support that version of MySQL, and it would be nice if the error message said that instead.

Other ideas: Rocket could change some defaults or expose more of them as options - different log formatting, quicker timeout, etc.
