### ISSUE TITLE
compile error of raw_sqlite example (failure to link)

### ISSUE THREAD

**Issue by bar9** [SergioBenitez/Rocket#959]
## Bug Report

Rocket Version: 0.4.0

OS: Ubuntu 18.04.2 LTS

Description: Executing `cargo run` on the raw_sqlite example exits with a compile error: `linking with 'cc' failed; /usr/bin/ld: cannot find -lsqlite3`
Potential solution: adding `features = ["bundled"]` to the dependency worked for me, as described [here](https://users.rust-lang.org/t/linker-cannot-find-lsqlite3/23230/8l)

**Comment by bar9** [comment]
The same happens for the todo example via diesel/r2d2. Installing libsqlite3-dev with apt as suggested [here](https://github.com/diesel-rs/diesel/issues/673) worked as well.

**Comment by SergioBenitez** [comment]
This is expected. To use sqlite, you need sqlite installed.

**Comment by bar9** [comment]
I understand that you need sqlite for using it. However, I have always had sqlite installed, just not the dev version. Having to install dev versions of linked libraries may be a common practice in C/C++ development, but for developers coming from other languages, this breaks the otherwise very smooth cargo experience and can leave you clueless. Obviously, this might not be am issue specific to rocket, so maybe you have an idea where to place this?

**Comment by jebrosen** [comment]
We could easily use the `bundled` feature for `raw_sqlite` (and also `todo`), which will change the build dependency from `libsqlite3[-dev] to` `gcc`. `gcc` is a bit more likely to be installed, but just as perplexing when it's missing.

---

> Obviously, this might not be am issue specific to rocket, so maybe you have an idea where to place this?

As it turns out we do document this for the todo example (https://github.com/SergioBenitez/Rocket/blob/master/examples/todo/README.md). The bindings used by raw_sqlite (https://github.com/jgallagher/rusqlite) explain build options as well.

The main pain point I experience with documenting 3rd party interop issues like these is that the problems and solutions are specific to each operating system/library combination. It's difficult to come up with a good blanket explanation, let alone put it somewhere where people will actually read it.
