### ISSUE TITLE
Allow for optional PathBuf in paths

### ISSUE THREAD

**Issue by TheSilvus** [SergioBenitez/Rocket#985]
Currently it is not possible to catch "no path" in the same request as "any path" (using `<path..>`). I would suggest to implement this using `Option<PathBuf>`: 

```rust
#[get("/<path..>")]
fn everything(path: Option<PathBuf>) -> String {
    format!("{:?}", path)
}
```

This should respond to any subpath of `/` as usual, but also respond to an access to `/` with `path=None`.

Current behavior seems to be ignoring the `Option<>` entirely and treating the argument as usual, so it shouldn't break backwards compatibility (badly).

You can work around the issue by internally redirecting another route:
```rust
#[get("/")]
fn index() -> String {
    everything(None)
}
#[get("/<path..>")]
fn everything(path: Option<PathBuf>) -> String {
    format!("{:?}", path)
}
```
This is neither ergonomic nor intuitive.

A relatively simple usecase could be file access with a directory listing: accessing a directory lists its contents. Access to the root dir would require this feature.

**Comment by TheSilvus** [comment]
Correction here: It could also be implemented by passing an empty `PathBuf`, but this would break backwards compatibility.

**Comment by SergioBenitez** [comment]
We absolutely cannot special-case what syntax means based on the type of arguments because we do not have type information in the procedural macro. Sure, `Option` is probably `std::option::Option`, but what if there's a rogue:

```rust
type Option<T> = my::Option<T>;
```

That being said, we could have the `PathBuf` be empty or otherwise fail (which can be caught by `Optional`) if the path is empty. This would mean that while `/<a>` and `/<b>/<path..>` don't collide today, they would, without explicit ranking, collide in the future. On the other hand, `/` and `/<a..>` would continue to not collide due to their default rankings. As such, I don't see a downside towards accepting this request. @jebrosen, do you have any thoughts? Are there consequences to this change that I'm forgetting?

Note that these arguments _do not_ apply to singular path segments. See my comments in https://github.com/SergioBenitez/Rocket/issues/608#issuecomment-385083836 for why.

**Comment by jhpratt** [comment]
I'll be taking a look into implementing it so `PathBuf` can match `/`, returning the equivalent to `PathBuf::new()`. No idea how easy or hard it will be.

**Comment by SergioBenitez** [comment]
A recent refactoring made this easy to implement. We'll be getting this in 0.5 soon!
