### ISSUE TITLE
Getting Started - everything broken all over, unbelievable, NO CI/CD?

### ISSUE THREAD

**Issue by GoRustafari** [SergioBenitez/Rocket#999]
First time user, heard how great this crap was.

Did a git checkout, went the the examples and: 
``` 
$cd examples/hello_world
$cargo run
``` 
and boom, splats crap all over as well as the other examples.  Please install and start using a CI/CD system for the examples, it sucked three hours out of my evening going down a path trying to get a web framework in place and now I have to start all over.

you had to have seen warnings on this for eons, with plenty of time to fix.

die

You should be on top of each and every language update.
---

```Compiling devise v0.2.0
error: ambiguous associated item
  --> core/http/src/ext.rs:97:28
   |
97 |     fn into_owned(self) -> Self::Owned {
   |                            ^^^^^^^^^^^ help: use fully-qualified syntax: `<std::borrow::Cow<'a, B> as Trait>::Owned`
   |
   = note: #[deny(ambiguous_associated_items)] on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #57644 <https://github.com/rust-lang/rust/issues/57644>
note: `Owned` could refer to variant defined here
note: `Owned` could also refer to associated type defined here
  --> core/http/src/ext.rs:78:5
   |
78 |     type Owned: 'static;
   |     ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `rocket_http`.

To learn more, run the command again with --verbose.```

**Comment by jebrosen** [comment]
> you had to have seen warnings on this for eons, with plenty of time to fix.

rust-lang/rust#57644 was first introduced as a warning in early January. We do have a CI/CD system that caught it, and the warning was fixed in February in the master branch (f0c6c9b). It is one of several fixes that has not yet made it into a released version of Rocket; @SergioBenitez is working toward that again and we will make sure the fix gets into 0.4.1.

This warning recently became deny-by-default a few days ago in rust-lang/rust#59928, and it is still not a hard error. As far as I know the only way to be affected by this with Rocket today is to run code from the 0.4 branch of Rocket directly. `master` is already fixed, and projects that use Rocket 0.4 as a crate (the most common and recommended way to use Rocket) are not yet affected because deny-by-default-lints do not apply to dependencies.

> You should be on top of each and every language update.

CI for 0.4 has been failing for another unrelated reason, so I didn't notice until you pointed it out herethat it had become deny-by-defualt. Otherwise this would have been seen sooner, but not necessarily fixed in a published release.

---

Thank you for bringing this to our attention. Let's leave this open until the fix is in a released version of Rocket.

**Comment by SergioBenitez** [comment]
This is a wonderful issue. Exemplary! We should make this the default issue template.

**Comment by SergioBenitez** [comment]
Fixed.
